### ISSUE TITLE
Conflicting data-reader mapping

### ISSUE THREAD

**Issue by itkach** [xtdb/crux#1629]
Following either https://xtdb.com/howto/quickstart.html or https://xtdb.com/howto/command-line-crux.html results in 
xtdb 1.19.0-beta1 failing to start with the following error:

```
Downloading: org/eclipse/jetty/jetty-alpn-server/9.4.36.v20210114/jetty-alpn-server-9.4.36.v20210114.jar from central
Downloading: com/xtdb/xtdb-http-server/1.19.0-beta1/xtdb-http-server-1.19.0-beta1.jar from central
clojure.lang.ExceptionInfo: Conflicting data-reader mapping {:url #object[java.net.URL 0x22356acd "jar:file:/Users/itkach/.m2/repository/juxt/crux-core/21.06-1.17.1-beta/crux-core-21.06-1.17.1-beta.jar!/data_readers.clj"], :conflict crux/id, :mappings {crux/id #'xtdb.codec/id-edn-reader, xtdb/id #'xtdb.codec/id-edn-reader, crux/base64 #'xtdb.codec/base64-reader, xtdb/base64 #'xtdb.codec/base64-reader}}
	at clojure.core$load_data_reader_file$fn__8825.invoke(core.clj:7826)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8162.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8162.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$load_data_reader_file.invokeStatic(core.clj:7815)
	at clojure.core$load_data_reader_file.invoke(core.clj:7806)
	at clojure.core.protocols$fn__8181.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8181.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
```

```
❯ clojure -version
Clojure CLI version 1.10.3.933
```

```
❯ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

**Comment by itkach** [comment]
The error was caused by me having 
```
juxt/crux-core {:mvn/version "RELEASE"}
```

in `~/.clojure/deps.edn` from some previous experiments with CruxDB.
