### ISSUE TITLE
XTDB listener not closing properly

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#1730]
from @arichiardi on [Zulip](https://juxt-oss.zulipchat.com/#narrow/stream/194466-xtdb-users/topic/XTDB.20Listener.20testing)

----

Dear XTDB users, I am trying to integration test a listener to `::xt/indexed-tx events.`

I am not 100% sure of this but I think the problem that I am facing is that I don't have a way to "wait" for the polling code to be down before closing the connection with the database.

My test is failing, it shuts down the db connection and then I keep getting:

```
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 1000ms.
    at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
    at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.connection$make_connection.invokeStatic(connection.clj:393)
    at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.connection$make_connection.invoke(connection.clj:377)
    at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.connection$eval34604$fn__34605.invoke(connection.clj:416)
    at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc.protocols$eval34358$fn__34359$G__34349__34366.invoke(protocols.clj:24)
    at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$get_connection.invokeStatic(jdbc.clj:167)
    at juxt.clojars_mirrors.nextjdbc.v1v2v674.next.jdbc$get_connection.invoke(jdbc.clj:146)
    at xtdb.jdbc.JdbcTxLog.open_tx_log(jdbc.clj:152)
    at xtdb.tx.subscribe$handle_polling_subscription$fn__36713$fn__36714.invoke(subscribe.clj:47)
    at xtdb.tx.subscribe$handle_polling_subscription$fn__36713.invoke(subscribe.clj:46)
    at xtdb.tx.subscribe$completable_thread$fn__36702.invoke(subscribe.clj:19)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

Is there a way to be sure the XTDB polling is done?

**Comment by jarohen** [comment]
The bus doesn't have an explicit dependency on the tx-log etc, because it doesn't need them - but its listeners might. Have added these as deps so that the bus waits for them to start, and waits for its listeners to closing before allowing the system to close their potential dependents. 

Will include this one as part of the next beta release.

Thanks again @arichiardi :pray: 

James
