### ISSUE TITLE
IXtdb.startNode() throws GCrypt error when starting :xtdb/tx-log (Found interface org.objectweb.asm.ClassVisitor, but class was expected)

### ISSUE THREAD

**Issue by theronic** [xtdb/crux#1738]
Calling `IXtdb.startNode()` throws from a Java project (macOS, using XTDB v1.20.0, OpenJDK v15):

```
10:42:45.487 [main] DEBUG xtdb.system - Starting [:xtdb/index-store :canonical-buffer-cache]
10:42:45.491 [main] DEBUG xtdb.system - Starting [:xtdb/index-store :kv-store :checkpointer]
10:42:45.491 [main] DEBUG xtdb.system - Starting [:xtdb/index-store :kv-store]
10:42:45.491 [main] DEBUG xtdb.system - Starting [:xtdb/index-store :cav-cache]
10:42:45.491 [main] DEBUG xtdb.system - Starting [:xtdb/index-store]
10:42:45.496 [main] DEBUG xtdb.memory - :pool-allocation-stats {:allocated 131072, :deallocated 0, :in-use 131072}
10:42:45.496 [main] DEBUG xtdb.mem-kv - Using fsync on MemKv has no effect.
10:42:45.496 [main] DEBUG xtdb.system - Starting [:xtdb/node :index-store]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/bus]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/document-store :document-cache]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/query-engine :bus]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/query-engine :index-store]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/document-store :kv-store :checkpointer]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/document-store :kv-store]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/query-engine :pull-cache]
10:42:45.497 [main] DEBUG xtdb.system - Starting [:xtdb/tx-indexer :index-store]
10:42:45.498 [main] DEBUG xtdb.system - Starting [:xtdb/document-store]
10:42:45.498 [main] DEBUG xtdb.system - Starting [:xtdb/query-engine :query-cache]
10:42:45.498 [main] DEBUG xtdb.system - Starting [:xtdb/query-engine :conform-cache]
10:42:45.498 [main] DEBUG xtdb.system - Starting [:xtdb/query-engine :document-store]
10:42:45.498 [main] DEBUG xtdb.system - Starting [:xtdb/query-engine]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-indexer :query-engine]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-indexer :document-store]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-indexer :bus]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-indexer]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-ingester :tx-indexer]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-log :kv-store :checkpointer]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-log :kv-store]
10:42:45.499 [main] DEBUG xtdb.system - Starting [:xtdb/tx-log]

clojure.lang.ExceptionInfo: Error starting system
 {:k [:xtdb/tx-log]}
	at xtdb.system$start_system$fn__6412.invoke(system.clj:220)
	at clojure.core.protocols$fn__8181.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8181.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$reduce.invoke(core.clj:6812)
	at xtdb.system$start_system.invokeStatic(system.clj:203)
	at xtdb.system$start_system.invoke(system.clj:197)
	at xtdb.api$start_node.invokeStatic(api.clj:246)
	at xtdb.api$start_node.invoke(api.clj:223)
	at clojure.lang.Var.invoke(Var.java:384)
	at xtdb.api.XtdbFactory.startNode(XtdbFactory.java:16)
	at xtdb.api.IXtdb.startNode(IXtdb.java:45)
	at xtdb.api.IXtdb.startNode(IXtdb.java:97)
	at xtdb.api.IXtdb.startNode(IXtdb.java:31)
	at myproject.AuditTest.setUp(AuditTest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: Syntax error macroexpanding at (jnr.clj:68:28).
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3711)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7186)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$serialized_require.invokeStatic(core.clj:6068)
	at clojure.core$requiring_resolve.invokeStatic(core.clj:6077)
	at clojure.core$requiring_resolve.invoke(core.clj:6071)
	at xtdb.hash$init_id_hash.invokeStatic(hash.clj:39)
	at xtdb.hash$init_id_hash.invoke(hash.clj:32)
	at xtdb.hash$lazy_id_hash$fn__5036.invoke(hash.clj:56)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.alterRoot(Var.java:308)
	at clojure.core$alter_var_root.invokeStatic(core.clj:5499)
	at clojure.core$alter_var_root.doInvoke(core.clj:5494)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at xtdb.hash$lazy_id_hash.invokeStatic(hash.clj:55)
	at xtdb.hash$lazy_id_hash.invoke(hash.clj:52)
	at xtdb.codec$id_function.invokeStatic(codec.clj:111)
	at xtdb.codec$id_function.invoke(codec.clj:109)
	at xtdb.codec$eval5480$fn__5481.invoke(codec.clj:561)
	at xtdb.codec$eval5182$fn__5183$G__5173__5190.invoke(codec.clj:76)
	at xtdb.codec$eval5541$fn__5542.invoke(codec.clj:682)
	at xtdb.codec$eval5145$fn__5157$G__5136__5162.invoke(codec.clj:72)
	at xtdb.kv.index_store$read_meta_snapshot.invokeStatic(index_store.clj:375)
	at xtdb.kv.index_store$read_meta_snapshot.invoke(index_store.clj:372)
	at xtdb.kv.index_store$read_meta.invokeStatic(index_store.clj:383)
	at xtdb.kv.index_store$read_meta.invoke(index_store.clj:379)
	at xtdb.kv.index_store$read_meta.invokeStatic(index_store.clj:380)
	at xtdb.kv.index_store$read_meta.invoke(index_store.clj:379)
	at xtdb.kv.tx_log$latest_submitted_tx.invokeStatic(tx_log.clj:37)
	at xtdb.kv.tx_log$latest_submitted_tx.invoke(tx_log.clj:36)
	at xtdb.kv.tx_log$__GT_tx_log.invokeStatic(tx_log.clj:128)
	at xtdb.kv.tx_log$__GT_tx_log.invoke(tx_log.clj:124)
	at xtdb.system$start_system$fn__6412.invoke(system.clj:211)
	... 46 more
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.ClassVisitor, but class was expected
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:104)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:89)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
	at xtdb.hash.jnr$init_gcrypt.invokeStatic(jnr.clj:46)
	at xtdb.hash.jnr$init_gcrypt.invoke(jnr.clj:44)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3706)
	... 103 more
```

This looks like a missing GCrypt library. Is there a hidden dependency I need to add to my pom.xml file?

`mvn clean compile` runs just fine. This is the dependency in my pom.xml file:

 `<dependency>
            <groupId>com.xtdb</groupId>
            <artifactId>xtdb-core</artifactId>
            <version>1.20.0</version>
        </dependency>`

**Comment by refset** [comment]
Hi @theronic are you on OSX by any chance? If so, there's an existing issue which seems related and that may offer you a useful solution or two: https://github.com/xtdb/xtdb/issues/894

**Comment by jarohen** [comment]
This looks like a version incompatibility with ASM - as the error message suggests, `ClassVisitor` used to be an interface (pre [4.0rc2](https://asm.ow2.io/versions.html#4.0rc2)) and is now an abstract class. Suspect there are two dependencies trying to pull in different versions of ASM...

Time to play the dependency game :sweat_smile:

**Comment by jarohen** [comment]
the one I can see in XT's `lein deps :tree` is as follows:

```clojure
 [com.xtdb/xtdb-rocksdb "dev-SNAPSHOT"]
   [com.github.jnr/jnr-ffi "2.1.12"]
     [com.github.jnr/jffi "1.2.23"]
     [com.github.jnr/jffi "1.2.23" :classifier "native" :scope "runtime"]
     [com.github.jnr/jnr-a64asm "1.0.0"]
     [com.github.jnr/jnr-x86asm "1.0.2"]
     [org.ow2.asm/asm-analysis "7.1"]
     [org.ow2.asm/asm-commons "7.1"]
     [org.ow2.asm/asm-tree "7.1"]
     [org.ow2.asm/asm-util "7.1"]
     [org.ow2.asm/asm "7.1"]
```

@theronic: I wonder if something you're pulling in requires an older version?

**Comment by theronic** [comment]
@jarohen, output of `mvn dependency:tree`:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ myproject ---
[INFO] myproject:jar:0.1
[INFO] +- org.clojure:clojure:jar:1.10.1:compile
[INFO] |  +- org.clojure:spec.alpha:jar:0.2.176:compile
[INFO] |  \- org.clojure:core.specs.alpha:jar:0.2.44:compile
[INFO] +- org.eclipse.jetty:jetty-server:jar:11.0.0:compile
[INFO] |  +- org.eclipse.jetty.toolchain:jetty-jakarta-servlet-api:jar:5.0.1:compile
[INFO] |  +- org.eclipse.jetty:jetty-http:jar:11.0.0:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:11.0.0:compile
[INFO] |  \- org.eclipse.jetty:jetty-io:jar:11.0.0:compile
[INFO] +- org.eclipse.jetty:jetty-servlet:jar:11.0.0:compile
[INFO] |  \- org.eclipse.jetty:jetty-security:jar:11.0.0:compile
[INFO] +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] +- org.apache.maven.plugins:maven-jar-plugin:jar:3.2.2:compile
[INFO] |  +- org.apache.maven:maven-plugin-api:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-model:jar:3.1.0:compile
[INFO] |  |  \- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M2a:compile
[INFO] |  |     +- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |  |     |  +- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |  |     |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  |     +- com.google.guava:guava:jar:10.0.1:compile
[INFO] |  |     |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  |     +- org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[INFO] |  |     |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |     \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a:compile
[INFO] |  |        \- asm:asm:jar:3.3.1:compile
[INFO] |  +- org.apache.maven:maven-core:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-settings:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-settings-builder:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-repository-metadata:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-model-builder:jar:3.1.0:compile
[INFO] |  |  +- org.apache.maven:maven-aether-provider:jar:3.1.0:compile
[INFO] |  |  |  \- org.eclipse.aether:aether-spi:jar:0.9.0.M2:compile
[INFO] |  |  +- org.eclipse.aether:aether-impl:jar:0.9.0.M2:compile
[INFO] |  |  +- org.eclipse.aether:aether-api:jar:0.9.0.M2:compile
[INFO] |  |  +- org.eclipse.aether:aether-util:jar:0.9.0.M2:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.16:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.4.2:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[INFO] |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[INFO] |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] |  +- org.apache.maven:maven-artifact:jar:3.1.0:compile
[INFO] |  +- org.apache.maven.shared:file-management:jar:3.0.0:compile
[INFO] |  |  \- org.apache.maven.shared:maven-shared-io:jar:3.0.0:compile
[INFO] |  |     +- org.apache.maven:maven-compat:jar:3.0:compile
[INFO] |  |     |  \- org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[INFO] |  |     |     \- org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[INFO] |  |     |        \- org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[INFO] |  |     \- org.apache.maven.wagon:wagon-provider-api:jar:2.10:compile
[INFO] |  +- org.apache.maven:maven-archiver:jar:3.5.2:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  |  +- org.apache.commons:commons-compress:jar:1.20:compile
[INFO] |  |  \- org.codehaus.plexus:plexus-archiver:jar:4.2.7:compile
[INFO] |  |     \- org.codehaus.plexus:plexus-io:jar:3.2.0:compile
[INFO] |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:compile
[INFO] |  \- org.codehaus.plexus:plexus-utils:jar:3.3.1:compile
[INFO] +- com.xtdb:xtdb-core:jar:1.20.0:compile
[INFO] |  +- pro.juxt.clojars-mirrors.com.stuartsierra:dependency:jar:1.0.0:compile
[INFO] |  +- pro.juxt.clojars-mirrors.com.taoensso:nippy:jar:3.1.1:compile
[INFO] |  |  +- org.iq80.snappy:snappy:jar:0.4:compile
[INFO] |  |  \- org.tukaani:xz:jar:1.8:compile
[INFO] |  +- org.clojure:tools.reader:jar:1.3.5:compile
[INFO] |  +- org.clojure:data.json:jar:2.3.1:compile
[INFO] |  +- org.clojure:tools.cli:jar:1.0.206:compile
[INFO] |  +- org.agrona:agrona:jar:1.11.0:compile
[INFO] |  \- pro.juxt.clojars-mirrors.edn-query-language:eql:jar:2021.02.28:compile
[INFO] +- com.xtdb:xtdb-rocksdb:jar:1.20.0:compile
[INFO] |  +- org.rocksdb:rocksdbjni:jar:6.12.7:compile
[INFO] |  \- com.github.jnr:jnr-ffi:jar:2.1.12:compile
[INFO] |     +- com.github.jnr:jffi:jar:1.2.23:compile
[INFO] |     +- com.github.jnr:jffi:jar:native:1.2.23:runtime
[INFO] |     +- org.ow2.asm:asm:jar:7.1:compile
[INFO] |     +- org.ow2.asm:asm-commons:jar:7.1:compile
[INFO] |     +- org.ow2.asm:asm-analysis:jar:7.1:compile
[INFO] |     +- org.ow2.asm:asm-tree:jar:7.1:compile
[INFO] |     +- org.ow2.asm:asm-util:jar:7.1:compile
[INFO] |     +- com.github.jnr:jnr-a64asm:jar:1.0.0:compile
[INFO] |     \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[INFO] +- com.xtdb:xtdb-http-server:jar:1.20.0:compile
[INFO] |  +- org.clojure:data.csv:jar:1.0.0:compile
[INFO] |  +- com.cognitect:transit-clj:jar:1.0.324:compile
[INFO] |  |  \- com.cognitect:transit-java:jar:1.0.343:compile
[INFO] |  |     +- org.msgpack:msgpack:jar:0.6.12:compile
[INFO] |  |     |  \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  |     \- javax.xml.bind:jaxb-api:jar:2.3.0:compile
[INFO] |  +- com.nimbusds:nimbus-jose-jwt:jar:9.7:compile
[INFO] |  |  \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  +- pro.juxt.clojars-mirrors.hiccup:hiccup:jar:2.0.0-alpha2:compile
[INFO] |  +- pro.juxt.clojars-mirrors.crux:crux-http-server-deps:jar:0.0.2:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-alpn-openjdk8-server:jar:9.4.36.v20210114:compile
[INFO] |  |  +- org.eclipse.jetty.http2:http2-server:jar:9.4.36.v20210114:compile
[INFO] |  |  |  \- org.eclipse.jetty.http2:http2-common:jar:9.4.36.v20210114:compile
[INFO] |  |  |     \- org.eclipse.jetty.http2:http2-hpack:jar:9.4.36.v20210114:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-server:jar:9.4.36.v20210114:compile
[INFO] |  |  |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.36.v20210114:compile
[INFO] |  |  |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.4.36.v20210114:compile
[INFO] |  |  |     \- org.eclipse.jetty:jetty-client:jar:9.4.36.v20210114:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-servlet:jar:9.4.36.v20210114:compile
[INFO] |  |  |  +- org.eclipse.jetty.websocket:websocket-api:jar:9.4.36.v20210114:compile
[INFO] |  |  |  \- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-alpn-server:jar:9.4.36.v20210114:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.1:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.1:compile
[INFO] |  |  +- org.clojure:core.rrb-vector:jar:0.0.14:compile
[INFO] |  |  +- commons-fileupload:commons-fileupload:jar:1.4:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  +- crypto-equality:crypto-equality:jar:1.0.0:compile
[INFO] |  |  \- crypto-random:crypto-random:jar:1.2.0:compile
[INFO] |  \- pro.juxt.clojars-mirrors.camel-snake-kebab:camel-snake-kebab:jar:0.4.2:compile
[INFO] +- com.xtdb:xtdb-lucene:jar:1.20.0:compile
[INFO] |  +- org.apache.lucene:lucene-core:jar:8.9.0:compile
[INFO] |  \- org.apache.lucene:lucene-queryparser:jar:8.9.0:compile
[INFO] |     +- org.apache.lucene:lucene-queries:jar:8.9.0:compile
[INFO] |     \- org.apache.lucene:lucene-sandbox:jar:8.9.0:compile
[INFO] +- org.quartz-scheduler:quartz:jar:2.3.2:compile
[INFO] |  +- com.mchange:c3p0:jar:0.9.5.4:compile
[INFO] |  +- com.mchange:mchange-commons-java:jar:0.2.15:compile
[INFO] |  \- com.zaxxer:HikariCP-java7:jar:2.4.13:compile
[INFO] +- junit:junit:jar:4.13.2:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- org.apache.kafka:kafka-clients:jar:3.1.0:compile
[INFO] |  +- com.github.luben:zstd-jni:jar:1.5.0-4:runtime
[INFO] |  +- org.lz4:lz4-java:jar:1.8.0:compile
[INFO] |  \- org.xerial.snappy:snappy-java:jar:1.1.8.4:runtime
[INFO] +- org.clojure:tools.logging:jar:1.1.0:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] \- org.slf4j:slf4j-api:jar:1.7.30:compile
```

I can't tell if there is a JNI conflict. Maybe in Maven plugin?

**Comment by jarohen** [comment]
@theronic: yep, that looks like the culprit - it's bringing in ASM 3.3.1.

**Comment by theronic** [comment]
Fixed by removing `maven-jar-plugin`! Thanks, @jarohen. Is there a way to see any potentially conflicting versions in one place using `mvn`?

**Comment by jarohen** [comment]
great, glad to hear it's resolved :slightly_smiling_face: 

and pass, I'm afraid - it's been a while since I've used Maven itself...
