### ISSUE TITLE
In-memory IXtdb.startNode with HTTP server options throws "xtdb.IllegalArgumentException: Error locating module" in Java

### ISSUE THREAD

**Issue by theronic** [xtdb/crux#1739]
Attempting to run an in-memory XTDB with HTTP server (v1.20.0) like the sample from the docs, throws:
```
var server = IXtdb.startNode(n -> {
            n.with("xtdb.http-server/server", http -> {
                http.set("port", 3000);
            });
        });
```
=>

```
xtdb.IllegalArgumentException: Error locating module
	at xtdb.error$illegal_arg.invokeStatic(error.clj:12)
	at xtdb.error$illegal_arg.invoke(error.clj:3)
	at xtdb.system.ModuleRef$fn__6322.invoke(system.clj:109)
	at xtdb.system.ModuleRef.prepare_dep(system.clj:106)
	at xtdb.system$opts_reducer$f__6360.invoke(system.clj:134)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6829)
	at clojure.core$reduce.invoke(core.clj:6812)
	at xtdb.system$prep_system.invokeStatic(system.clj:156)
	at xtdb.system$prep_system.invoke(system.clj:141)
	at xtdb.system$prep_system.invokeStatic(system.clj:142)
	at xtdb.system$prep_system.invoke(system.clj:141)
	at xtdb.api$start_node.invokeStatic(api.clj:236)
	at xtdb.api$start_node.invoke(api.clj:223)
	at clojure.lang.Var.invoke(Var.java:384)
	at xtdb.api.XtdbFactory.startNode(XtdbFactory.java:16)
	at xtdb.api.IXtdb.startNode(IXtdb.java:45)
	at xtdb.api.IXtdb.startNode(IXtdb.java:97)
	at xtdb.api.IXtdb.startNode(IXtdb.java:94)
	at co.saltpay.checksum.RuleTest.tempTest(RuleTest.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: Syntax error compiling at (juxt/clojars_mirrors/ring_jetty_adapter/v0v14v2/ring/adapter/jetty9.clj:120:5).
	at clojure.lang.Compiler.analyze(Compiler.java:6812)
	at clojure.lang.Compiler.analyze(Compiler.java:6749)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1020)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7099)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyze(Compiler.java:6749)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6122)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6440)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7099)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyze(Compiler.java:6749)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6124)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6440)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7099)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyze(Compiler.java:6749)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6124)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5471)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4033)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7109)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7099)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:596)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
	at clojure.lang.Compiler.analyze(Compiler.java:6793)
	at clojure.lang.Compiler.analyze(Compiler.java:6749)
	at clojure.lang.Compiler.eval(Compiler.java:7185)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:3894)
	at xtdb.http_server$eval15545$loading__6737__auto____15546.invoke(http_server.clj:1)
	at xtdb.http_server$eval15545.invokeStatic(http_server.clj:1)
	at xtdb.http_server$eval15545.invoke(http_server.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$serialized_require.invokeStatic(core.clj:6068)
	at clojure.core$requiring_resolve.invokeStatic(core.clj:6077)
	at clojure.core$requiring_resolve.invoke(core.clj:6071)
	at xtdb.system.ModuleRef$fn__6322.invoke(system.clj:107)
	... 43 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/Trie
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3220)
	at java.base/java.lang.Class.privateGetPublicFields(Class.java:3247)
	at java.base/java.lang.Class.getFields(Class.java:1906)
	at clojure.lang.Reflector.getField(Reflector.java:487)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7313)
	at clojure.lang.Compiler.analyze(Compiler.java:6772)
	... 133 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.Trie
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 140 more
```

XT Dependencies in pom.xml:

```
...
        <dependency>
            <groupId>com.xtdb</groupId>
            <artifactId>xtdb-core</artifactId>
            <version>1.20.0</version>
        </dependency>
        <dependency>
            <groupId>com.xtdb</groupId>
            <artifactId>xtdb-rocksdb</artifactId>
            <version>1.20.0</version>
        </dependency>
        <dependency>
            <groupId>com.xtdb</groupId>
            <artifactId>xtdb-http-server</artifactId>
            <version>1.20.0</version>
        </dependency>
        <dependency>
            <groupId>com.xtdb</groupId>
            <artifactId>xtdb-http-client</artifactId>
            <version>1.20.0</version>
        </dependency>
        <dependency>
            <groupId>com.xtdb</groupId>
            <artifactId>xtdb-lucene</artifactId>
            <version>1.20.0</version>
        </dependency>
```

Do I need to add some Jetty

**Comment by theronic** [comment]
Jetty conflict. Resolved by pegging Jetty version to same as XT. (Why are things like this on JVM?):

    <properties>
        ...
        <jetty.version>9.4.36.v20210114</jetty.version>
    </properties>
<jetty.version>9.4.36.v20210114</jetty.version>

    <dependencies>

        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>${jetty.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>${jetty.version}</version>
        </dependency>

    ...
    </dependencies>

**Comment by jarohen** [comment]
Ah man, you're not having much luck with these recently! :exploding_head:
