### ISSUE TITLE
slow-query? fn, NullPointerException: Cannot invoke "java.util.Date.toInstant()" because "started_at" is null

### ISSUE THREAD

**Issue by theronic** [xtdb/crux#1764]
Running my tests against XTDB 1.20.0 throws this exception:
```
18:06:35.215 [main] DEBUG xtdb.query - :vars-in-join-order [?entry ?currency ?account ?tx ?amount]
18:06:35.215 [main] DEBUG xtdb.query - :var->bindings {?amount #xtdb.query.VarBinding{:e-var nil, :var ?amount, :attr nil, :result-index 4, :result-name xtdb.query.value/?amount, :type :pred, :value? true}, ?account #xtdb.query.VarBinding{:e-var ?entry, :var ?account, :attr :entry/account, :result-index 2, :result-name ?entry, :type :entity, :value? false}, ?currency #xtdb.query.VarBinding{:e-var ?entry, :var ?currency, :attr :entry/currency, :result-index 1, :result-name ?entry, :type :entity, :value? false}, ?entry #xtdb.query.VarBinding{:e-var ?entry, :var ?entry, :attr :crux.db/id, :result-index 0, :result-name ?entry, :type :entity, :value? false}, ?tx #xtdb.query.VarBinding{:e-var ?entry, :var ?tx, :attr :entry/tx, :result-index 3, :result-name ?entry, :type :entity, :value? false}}
18:06:35.216 [main] INFO xtdb.tx - Shut down tx-ingester
18:06:35.216 [bus-listener-1] ERROR xtdb.io - Uncaught exception:
java.lang.NullPointerException: Cannot invoke "java.util.Date.toInstant()" because "started_at" is null
        at xtdb.node$slow_query_QMARK_.invokeStatic(node.clj:72)
        at xtdb.node$slow_query_QMARK_.invoke(node.clj:71)
        at xtdb.node$swap_finished_query_BANG_.invokeStatic(node.clj:258)
        at xtdb.node$swap_finished_query_BANG_.invoke(node.clj:253)
        at xtdb.node$attach_current_query_listeners$fn__14689.invoke(node.clj:293)
        at xtdb.bus.EventBus$fn__7251$fn__7252.invoke(bus.clj:105)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
18:06:35.216 [main] INFO xtdb.tx - Shut down tx-ingester
```

**Comment by jarohen** [comment]
Thanks for the report @theronic - are you able to post a minimal repro for this one?

**Comment by refset** [comment]
My guess would be that an initial `swap!` to register a query as in-progress, i.e. https://github.com/xtdb/xtdb/blob/6fb56faaa612b68ba1d6c84c6323bfde26358b7a/core/src/xtdb/node.clj#L290
...is _still_ retrying (due to multi-threaded contention) by the time the (very fast?) query has finished. If that's the case then perhaps an alternative data structure could help, rather than a single top-level atom.

How many threads are querying concurrently in your tests?
