### ISSUE TITLE
Lucene indexing should not halt

### ISSUE THREAD

**Issue by refset** [xtdb/crux#1916]
An underlying `FileLock` error is happening (quite possibly due to non-JVM OS activity) but it is causing an error that can't be recovered from without manually deleting the lock file and restarting the node.

This symptom only surfaced _after_ upgrading from `1.20.0` to `1.22.2-rc1` (and there was a minor Lucene bump in the intervening changes).

For more information and speculation about causes, see https://juxt-oss.zulipchat.com/#narrow/stream/194466-xtdb-users/topic/Lucene.20indexer.20fail.20leads.20to.20need.20to.20fully.20reindex

```
2023-02-16 22:49:46.047+0000 [WARN ][xtdb-lucene-refresh-1][] xtdb.lucene: error during Lucene IndexWriter commit
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
    at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:877)
    at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:891)
    at org.apache.lucene.index.IndexWriter.nrtIsCurrent(IndexWriter.java:5241)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:289)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:268)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:258)
    at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:173)
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
    at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
    at org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:225)
    at xtdb.lucene$refresh.invokeStatic(lucene.clj:319)
    at xtdb.lucene$refresh.invoke(lucene.clj:318)
    at xtdb.lucene$refresh_loop$fn__291867.invoke(lucene.clj:327)
    at xtdb.lucene$refresh_loop.invokeStatic(lucene.clj:325)
    at xtdb.lucene$refresh_loop.invoke(lucene.clj:321)
    at xtdb.lucene$__GT_lucene_store$fn__291883.invoke(lucene.clj:376)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.lucene.store.AlreadyClosedException: FileLock invalidated by an external force: NativeFSLock(path=/var/xtdb/core-data/admin/lucene-dir/write.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive invalid],creationTime=2023-01-27T18:29:49.417418Z)
    at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:178)
    at org.apache.lucene.store.LockValidatingDirectoryWrapper.createOutput(LockValidatingDirectoryWrapper.java:43)
    at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:43)
    at org.apache.lucene.codecs.lucene80.Lucene80NormsConsumer.<init>(Lucene80NormsConsumer.java:45)
    at org.apache.lucene.codecs.lucene80.Lucene80NormsFormat.normsConsumer(Lucene80NormsFormat.java:85)
    at org.apache.lucene.index.DefaultIndexingChain.writeNorms(DefaultIndexingChain.java:389)
    at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:221)
    at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:350)
    at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:476)
    at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:656)
    at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:605)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:293)
    ... 15 common frames omitted
```

**Comment by kevinmershon** [comment]
For now we are using a scheduled job that runs every 10 seconds checking for a backlog > 10k transactions and if it occurs the job deletes the write lock and kills the kubernetes pod. Quite a hack job but it lets us stay up in production finally.

**Comment by refset** [comment]
Thanks for the follow-up @kevinmershon and confirming the current situation / impact.

(Briefly thinking out loud while I'm here...) with the ingestion error handling improvements in 1.23.1 there should at least be a nicer way to detect / surface this error - even if we can't manage to reproduce it at this end.

**Comment by avocade** [comment]
We're getting this as well now in production, just FYI.

**Comment by refset** [comment]
Hey @kevinmershon see the workaround fix in the commit referenced above https://github.com/jarohen/xtdb/commit/bc0eac1446e58a327d761e18c8c8d139230ef6b3 - there's a snapshot release of this change available if that's of any use: `com.xtdb/xtdb-lucene {:mvn/version "1.24.1-20230801.100426-1"}`

**Comment by wotbrew** [comment]
@kevinmershon Hi Kevin, I would like to get verbose IndexWriter logs from Lucene to better illuminate the issue.

I can create a snapshot release that would provide the option to emit these logs. If you are interested could you confirm the version of XTDB you are currently on (i.e are you still on `1.22-rc1`?) so I can create the correct snapshot?

**Comment by kevinmershon** [comment]
@wotbrew Hi Dan, apologies for the delay. We have moved our production systems off XTDB so I cannot help with this any further.

**Comment by avocade** [comment]
@kevinmershon would be interested in hearing your rationale for that switch, just a TL;DR at least :)

**Comment by kevinmershon** [comment]
@avocade Aside from the issues I've already reported here and on the Zulip chat, I don't think this is actually a good forum for discussing all the reasons. That said, we also don't have a Ride Health company tech blog so if you want details I'm happy to share them if you email me. Firstname at ridehealth dot com will reach me.
