### ISSUE TITLE
Fail in `test-cast-to-time`

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2241]
just when I commit the fix to xtdb/xtdb#2240 

```
FAIL in (test-cast-to-time) (temporal_test.clj:239)
expected: {:result true}
  actual: {:shrunk {:total-nodes-visited 812, :depth 20, :pass? false, :result false, :result-data nil, :time-shrinking-ms 357, :smallest [#time/time "02:00" #time/zone "US/Michigan" #time/instant "2033-03-13T05:00:00Z"]}, :failed-after-ms 173, :num-tests 74, :seed 1661504631511, :fail [#time/time "02:57:19.832072" #time/zone "MST7MDT" #time/instant "2033-03-13T18:46:29.360639Z"], :result false, :result-data nil, :failing-size 73, :pass? false, :test-var "test-cast-to-time"}
```

**Comment by FiV0** [comment]
Seems to be back. Error message
```clj
FAIL in (test-cast-to-time) (temporal_test.clj:242)
expected: {:result true}
  actual: {:shrunk {:total-nodes-visited 529, :depth 15, :pass? false, :result false, :result-data nil, :time-shrinking-ms 136, :smallest [#time/date-time "2025-03-09T02:00" #time/zone "America/Boise" #time/instant "2020-01-01T00:00:00Z"]}, :failed-after-ms 82, :num-tests 45, :seed 1679900150033, :fail [#time/date-time "2025-03-09T02:29:24.728996" #time/zone "America/Indiana/Marengo" #time/instant "2020-05-25T02:24:32.826506Z"], :result false, :result-data nil, :failing-size 44, :pass? false, :test-var "test-cast-to-time"}
```

**Comment by FiV0** [comment]
Comment from duplicate:
```clj


FAIL in (test-cast-to-time) (temporal_test.clj:242)
expected: {:result true}
  actual: {:shrunk {:total-nodes-visited 980, :depth 27, :pass? false, :result false, :result-data nil, :time-shrinking-ms 187, :smallest [#time/date-time "2035-03-25T03:00" #time/zone "Europe/Riga" #time/instant "2020-01-01T00:00:00Z"]}, :failed-after-ms 9, :num-tests 8, :seed 1675870531633, :fail [#time/date-time "2035-03-25T03:34:36.653210" #time/zone "Europe/Riga" #time/instant "2028-01-16T12:17:33.992060Z"], :result false, :result-data nil, :failing-size 7, :pass? false, :test-var "test-cast-to-time"}

```

**Comment by Akeboshiwind** [comment]
[Same again](https://github.com/xtdb/xtdb/actions/runs/21093868322/job/60668907725)
```
org.opentest4j.AssertionFailedError: FAIL in  (test-cast-to-time) (temporal_test.clj:724)
expected:  {:result true}
  actual:  {:shrunk {:total-nodes-visited 721, :depth 22, :pass? false, :result false, :result-data nil, :time-shrinking-ms 970, :smallest [#xt/ldt "2026-09-27T02:45" #xt/zone "NZ-CHAT" #xt/instant "2020-01-01T00:00:00Z"]}, :failed-after-ms 75, :num-tests 53, :seed 1768651403829, :fail [#xt/ldt "2026-09-27T03:23:45.269622" #xt/zone "NZ-CHAT" #xt/instant "2039-02-12T23:00:32.135973Z"], :result false, :result-data nil, :failing-size 52, :pass? false, :test-var "test-cast-to-time"}
```

<details><summary>Trace</summary>

```
at dev.clojurephant.jovial.engine.clojure_test$eval912$fn__913.invoke(clojure_test.clj:75)
	at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at app//clojure.test$do_report.invokeStatic(test.clj:357)
	at app//clojure.test$do_report.invoke(test.clj:351)
	at app//clojure.test.check.clojure_test.assertions$check_results.invokeStatic(assertions.cljc:37)
	at app//clojure.test.check.clojure_test.assertions$check_results.invoke(assertions.cljc:32)
	at app//clojure.test.check.clojure_test$assert_check.invokeStatic(clojure_test.cljc:22)
	at app//clojure.test.check.clojure_test$assert_check.invoke(clojure_test.cljc:18)
	at app//xtdb.expression.temporal_test$fn__16846.invokeStatic(temporal_test.clj:724)
	at app//xtdb.expression.temporal_test$fn__16846.invoke(temporal_test.clj:724)
	at dev.clojurephant.jovial.engine.clojure_test$eval884$fn__887.invoke(clojure_test.clj:34)
	at dev.clojurephant.jovial.engine.clojure_test$eval842$fn__854$G__833__859.invoke(clojure_test.clj:16)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__897$fn__898.invoke(clojure_test.clj:53)
	at app//xtdb.test_util$with_allocator$fn__23861.invoke(test_util.clj:52)
	at app//xtdb.test_util$with_allocator.invokeStatic(test_util.clj:50)
	at app//xtdb.test_util$with_allocator.invoke(test_util.clj:49)
	at app//clojure.test$compose_fixtures$fn__9892$fn__9893.invoke(test.clj:694)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at app//clojure.test$compose_fixtures$fn__9892.invoke(test.clj:694)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__897.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__897$fn__898.invoke(clojure_test.clj:55)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__897.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__897$fn__898.invoke(clojure_test.clj:55)
	at dev.clojurephant.jovial.engine.clojure_test$eval870$fn__871$fn__872.invoke(clojure_test.clj:22)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__897.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test.Engine.execute(clojure_test.clj:113)
	at dev.clojurephant.jovial.engine$eval659$fn__686$G__651__689.invoke(engine.clj:23)
	at dev.clojurephant.jovial.engine$eval659$fn__686$G__650__693.invoke(engine.clj:23)
	at app//clojure.lang.AFn.applyToHelper(AFn.java:156)
	at app//clojure.lang.AFn.applyTo(AFn.java:144)
	at app//clojure.lang.Var.applyTo(Var.java:707)
	at app//clojure.core$apply.invokeStatic(core.clj:667)
	at app//clojure.core$apply.invoke(core.clj:662)
	at app//clojure.lang.Var.invoke(Var.java:390)
	at app//dev.clojurephant.jovial.util.SimpleClojure.invoke(SimpleClojure.java:21)
	at app//dev.clojurephant.jovial.BaseClojureEngine.execute(BaseClojureEngine.java:32)
```

</details>
