### ISSUE TITLE
Error handling for inserting strings into time cols

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2252]
```
jdt=> start transaction read write;                                                                                                                                                INSERT INTO Prop_Owner (id, customer_number, property_number, application_time_start, application_time_end)
VALUES (1, 145, 7799997, '1998-01-03', '1999-01-01');
commit;
BEGIN
INSERT 0 0
ERROR:  internal error on commit (report as a bug)
```

```
5:36:52 | ERROR core2.util | Uncaught exception:
java.lang.AbstractMethodError: Receiver class core2.vector$eval4732$fn$reify__4734 does not define or inherit an implementation of the resolved method 'abstract long readLong(int)' of interface core2.vector.IMonoVectorReader.
	at core2.indexer$$reify__17557$fn$reify__17564.accept(indexer.clj:473)
	at core2.operator.rename.RenameCursor$reify__12434.accept(rename.clj:41)
	at core2.operator.table.TableCursor$fn__12741.invoke(table.clj:33)
	at core2.operator.table.TableCursor.tryAdvance(table.clj:31)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator.ResultCursor.tryAdvance(operator.clj:38)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at core2.indexer$$reify__17557$fn__17563.invoke(indexer.clj:451)
	at core2.indexer$$reify__17557.indexOp(indexer.clj:450)
	at core2.indexer$$reify__17796.indexOp(indexer.clj:613)
	at core2.indexer.Indexer.indexTx(indexer.clj:686)
	at core2.ingester$eval17984$fn$reify__17988.acceptRecord(ingester.clj:76)
	at core2.log$tx_handler$fn__17917.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.log$handle_polling_subscription$fn__17923.invoke(log.clj:48)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
15:36:52 | DEBUG core2.pgwire | Error on await-tx
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: Ingestion stopped: Receiver class core2.vector$eval4732$fn$reify__4734 does not define or inherit an implementation of the resolved method 'abstract long readLong(int)' of interface core2.vector.IMonoVectorReader. {}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at clojure.core$deref_future.invokeStatic(core.clj:2317)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at core2.pgwire$cmd_commit$fn__19327.invoke(pgwire.clj:1594)
	at core2.pgwire$cmd_commit.invokeStatic(pgwire.clj:1594)
	at core2.pgwire$cmd_commit.invoke(pgwire.clj:1576)
	at core2.pgwire$cmd_exec_stmt.invokeStatic(pgwire.clj:1690)
	at core2.pgwire$cmd_exec_stmt.invoke(pgwire.clj:1661)
	at core2.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1739)
	at core2.pgwire$cmd_simple_query.invoke(pgwire.clj:1734)
	at core2.pgwire$conn_loop.invokeStatic(pgwire.clj:1906)
	at core2.pgwire$conn_loop.invoke(pgwire.clj:1827)
	at core2.pgwire$connect$fn__19445.invoke(pgwire.clj:1971)
	at core2.pgwire$connect.invokeStatic(pgwire.clj:1969)
	at core2.pgwire$connect.invoke(pgwire.clj:1923)
	at core2.pgwire$accept_loop$fn__19459$fn__19460$fn__19461.invoke(pgwire.clj:2044)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: clojure.lang.ExceptionInfo: Ingestion stopped: Receiver class core2.vector$eval4732$fn$reify__4734 does not define or inherit an implementation of the resolved method 'abstract long readLong(int)' of interface core2.vector.IMonoVectorReader.
	at core2.await$__GT_ingester_ex.invokeStatic(await.clj:17)
	at core2.await$__GT_ingester_ex.invoke(await.clj:16)
	at core2.await$notify_ex.invokeStatic(await.clj:58)
	at core2.await$notify_ex.invoke(await.clj:54)
	at core2.ingester$eval17984$fn$reify__17988.acceptRecord(ingester.clj:81)
	at core2.log$tx_handler$fn__17917.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.log$handle_polling_subscription$fn__17923.invoke(log.clj:48)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 common frames omitted
Caused by: java.lang.AbstractMethodError: Receiver class core2.vector$eval4732$fn$reify__4734 does not define or inherit an implementation of the resolved method 'abstract long readLong(int)' of interface core2.vector.IMonoVectorReader.
	at core2.indexer$$reify__17557$fn$reify__17564.accept(indexer.clj:473)
	at core2.operator.rename.RenameCursor$reify__12434.accept(rename.clj:41)
	at core2.operator.table.TableCursor$fn__12741.invoke(table.clj:33)
	at core2.operator.table.TableCursor.tryAdvance(table.clj:31)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator.ResultCursor.tryAdvance(operator.clj:38)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at core2.indexer$$reify__17557$fn__17563.invoke(indexer.clj:451)
	at core2.indexer$$reify__17557.indexOp(indexer.clj:450)
	at core2.indexer$$reify__17796.indexOp(indexer.clj:613)
	at core2.indexer.Indexer.indexTx(indexer.clj:686)
	at core2.ingester$eval17984$fn$reify__17988.acceptRecord(ingester.clj:76)
	... 10 common frames omitted
```

Also breaks ingestion xtdb/xtdb#2221

**Comment by jarohen** [comment]
let's add an analyzer error for this one

**Comment by jarohen** [comment]
on second thoughts, in the general case we can only do this at runtime. could make a plan-time error for string literals, as a special case, if that'd help

**Comment by jarohen** [comment]
as discussed - even the workaround is complex and not without risk - let's shoot for xtdb/xtdb#2256.
