### ISSUE TITLE
DML from_subquery returning app time causes `core2.IllegalArgumentException: Unknown symbol: 'tmp__93_application_time_start'`

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2273]
It seems there's a related fix needed, following on from xtdb/xtdb#2259 

```
Exception in thread "core2-tx-subscriptionpool-1-thread-6" core2.IllegalArgumentException: Unknown symbol: 'tmp__93_application_time_start'
	at core2.error$illegal_arg.invokeStatic(error.clj:13)
	at core2.error$illegal_arg.invoke(error.clj:4)
	at core2.error$illegal_arg.invokeStatic(error.clj:8)
	at core2.error$illegal_arg.invoke(error.clj:4)
	at core2.expression$form__GT_expr.invokeStatic(expression.clj:42)
	at core2.expression$form__GT_expr.invoke(expression.clj:35)
	at core2.expression$eval14003$fn__14005$fn__14009.invoke(expression.clj:181)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.lang.PersistentList.reduce(PersistentList.java:141)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at core2.expression$eval14003$fn__14005.invoke(expression.clj:181)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.expression$form__GT_expr.invokeStatic(expression.clj:59)
	at core2.expression$form__GT_expr.invoke(expression.clj:35)
	at core2.expression$eval14003$fn__14005$fn__14009.invoke(expression.clj:181)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.lang.PersistentList.reduce(PersistentList.java:141)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at core2.expression$eval14003$fn__14005.invoke(expression.clj:181)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.expression$form__GT_expr.invokeStatic(expression.clj:59)
	at core2.expression$form__GT_expr.invoke(expression.clj:35)
	at core2.expression$eval14003$fn__14005$fn__14009.invoke(expression.clj:181)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.lang.PersistentList.reduce(PersistentList.java:141)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at core2.expression$eval14003$fn__14005.invoke(expression.clj:181)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.expression$form__GT_expr.invokeStatic(expression.clj:59)
	at core2.expression$form__GT_expr.invoke(expression.clj:35)
	at core2.expression$__GT_expression_projection_spec.invokeStatic(expression.clj:1504)
	at core2.expression$__GT_expression_projection_spec.invoke(expression.clj:1503)
	at core2.expression$__GT_expression_relation_selector.invokeStatic(expression.clj:1529)
	at core2.expression$__GT_expression_relation_selector.invoke(expression.clj:1528)
	at core2.operator.select$eval20837$fn__20840$fn__20843.invoke(select.clj:42)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:68)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.select$eval20837$fn__20840.invoke(select.clj:40)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.rename$eval20786$fn__20788.invoke(rename.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.group_by$eval19543$fn__19545.invoke(group_by.clj:639)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.project$eval19711$fn__19714.invoke(project.clj:96)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.project$eval19711$fn__19714.invoke(project.clj:96)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
```

```
INSERT INTO Prop_Owner (id, customer_number, property_number)
VALUES (1, 145, 7797);

INSERT INTO Prop_Owner (id, customer_number, property_number, application_time_start, application_time_end)
SELECT 1,
       145,
       7797, DATE '1998-01-03', tmp.app_start
FROM
  (SELECT MIN(Prop_Owner.system_time_start) AS app_start
      FROM Prop_Owner
             FOR ALL SYSTEM_TIME
    WHERE Prop_Owner.id = 1) AS tmp;
```

```
[:insert
 {:table "prop_owner"}
 [:rename
  {x10 id,
   x11 customer_number,
   x12 property_number,
   x14 application_time_start,
   x15 application_time_end}
  [:project
   [x10 x11 x12 {x14 (cast-tstz x13)} {x15 (cast-tstz x8)}]
   [:project
    [{x10 1} {x11 145} {x12 7797} {x13 #time/date "1998-01-03"} x8]
    [:group-by
     [{x8 (min x1)}]
     [:rename
      {system_time_start x1,
       system_time_end x2,
       application_time_start x3,
       application_time_end x4,
       id x5,
       _table x6}
      [:select
       (and
        (<= tmp__93_application_time_start (current-timestamp))
        (> tmp__93_application_time_end (current-timestamp)))
       [:scan
        [{system_time_start (<= system_time_start core2/end-of-time)}
         system_time_end
         {application_time_start
          (<= application_time_start (current-timestamp))}
         {application_time_end
          (> application_time_end (current-timestamp))}
         {id (= id 1)}
         {_table (= _table "Prop_Owner")}]]]]]]]]]
```

**Comment by refset** [comment]
Confirmed as resolved by https://github.com/xtdb/core2/pull/434 - thanks again @mbutlerw :pray:
