### ISSUE TITLE
Error on `(halt)`

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2296]
```
dev> (halt)
12:19:55.821 [nREPL-session-97f7bee7-70a2-47b5-b1e0-fe4e68c7a0c8] INFO  core2.server - HTTP server stopped.
12:20:00.831 [nREPL-session-97f7bee7-70a2-47b5-b1e0-fe4e68c7a0c8] WARN  core2.pgwire - Could not drain connections in time, force closing
12:20:00.842 [nREPL-session-97f7bee7-70a2-47b5-b1e0-fe4e68c7a0c8] INFO  core2.pgwire - PGWire server stopped
12:20:00.887 [nREPL-session-97f7bee7-70a2-47b5-b1e0-fe4e68c7a0c8] WARN  core2.util - could not close
clojure.lang.ExceptionInfo: Error on key :core2.indexer/indexer when running system
	at juxt.clojars_mirrors.integrant.core$run_exception.invokeStatic(core.cljc:242)
	at juxt.clojars_mirrors.integrant.core$run_exception.invoke(core.cljc:241)
	at juxt.clojars_mirrors.integrant.core$try_run_action.invokeStatic(core.cljc:256)
	at juxt.clojars_mirrors.integrant.core$try_run_action.invoke(core.cljc:252)
	at juxt.clojars_mirrors.integrant.core$run_loop.invokeStatic(core.cljc:262)
	at juxt.clojars_mirrors.integrant.core$run_loop.invoke(core.cljc:258)
	at juxt.clojars_mirrors.integrant.core$reverse_run_BANG_.invokeStatic(core.cljc:282)
	at juxt.clojars_mirrors.integrant.core$reverse_run_BANG_.invoke(core.cljc:276)
	at juxt.clojars_mirrors.integrant.core$halt_BANG_.invokeStatic(core.cljc:449)
	at juxt.clojars_mirrors.integrant.core$halt_BANG_.invoke(core.cljc:443)
	at juxt.clojars_mirrors.integrant.core$halt_BANG_.invokeStatic(core.cljc:446)
	at juxt.clojars_mirrors.integrant.core$halt_BANG_.invoke(core.cljc:443)
	at core2.local_node$start_node$fn__25471.invoke(local_node.clj:228)
	at core2.local_node.Node.close(local_node.clj:184)
	at core2.util$try_close.invokeStatic(util.clj:274)
	at core2.util$try_close.invoke(util.clj:271)
	at dev$eval29692$fn__29693.invoke(dev.clj:46)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at integrant.core$try_run_action.invokeStatic(core.cljc:244)
	at integrant.core$try_run_action.invoke(core.cljc:242)
	at integrant.core$run_loop.invokeStatic(core.cljc:252)
	at integrant.core$run_loop.invoke(core.cljc:248)
	at integrant.core$reverse_run_BANG_.invokeStatic(core.cljc:272)
	at integrant.core$reverse_run_BANG_.invoke(core.cljc:266)
	at integrant.core$halt_BANG_.invokeStatic(core.cljc:439)
	at integrant.core$halt_BANG_.invoke(core.cljc:433)
	at integrant.core$halt_BANG_.invokeStatic(core.cljc:436)
	at integrant.core$halt_BANG_.invoke(core.cljc:433)
	at integrant.repl$halt_system.invokeStatic(repl.clj:20)
	at integrant.repl$halt_system.invoke(repl.clj:19)
	at integrant.repl$halt.invokeStatic(repl.clj:69)
	at integrant.repl$halt.invoke(repl.clj:68)
	at dev$eval38310.invokeStatic(NO_SOURCE_FILE:60)
	at dev$eval38310.invoke(NO_SOURCE_FILE:60)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7149)
	at clojure.core$eval.invokeStatic(core.clj:3215)
	at clojure.core$eval.invoke(core.clj:3211)
	at nrepl.middleware.interruptible_eval$evaluate$fn__2986$fn__2987.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at nrepl.middleware.interruptible_eval$evaluate$fn__2986.invoke(interruptible_eval.clj:87)
	at clojure.main$repl$read_eval_print__9206$fn__9209.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9206.invoke(main.clj:437)
	at clojure.main$repl$fn__9215.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__3019$fn__3023.invoke(interruptible_eval.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__3089$fn__3093.invoke(session.clj:218)
	at nrepl.middleware.session$session_exec$main_loop__3089.invoke(session.clj:217)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: No matching field found: clear for class core2.vector.writer$$reify__11835
	at clojure.lang.Reflector.getInstanceField(Reflector.java:397)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:440)
	at core2.indexer$$reify__24219.clear(indexer.clj:292)
	at core2.indexer.Indexer.closeCols(indexer.clj:774)
	at core2.indexer.Indexer.close(indexer.clj:799)
	at core2.indexer$eval24626$fn__24627.invoke(indexer.clj:831)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at juxt.clojars_mirrors.integrant.core$try_run_action.invokeStatic(core.cljc:254)
	... 57 common frames omitted
``

**Comment by refset** [comment]
Ah, I think this is simply due to me failing to run `clojure -X:deps prep :force true` after pulling the latest changes.
