### ISSUE TITLE
Ingestion stopped and node unresponsive due to fixed-sized-list error

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2333]
Any query (not just inserts) I run returns `ERROR:  unexpected server error during query execution` alongside:
```
11:12:38.727 [pgwire-connection--pool-3-thread-13] DEBUG core2.pgwire - Error during query open-sql-async
java.util.concurrent.CompletionException: clojure.lang.ExceptionInfo: Ingestion stopped: fixed-size-list vector already exists {}
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at core2.util$then_apply.invokeStatic(util.clj:266)
	at core2.util$then_apply.invoke(util.clj:263)
	at core2.ingester$eval19762$fn$reify__19771.snapshot(ingester.clj:94)
	at core2.node.Node$fn__20036.invoke(node.clj:129)
	at core2.util$$reify__4426.apply(util.clj:256)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at core2.util$then_compose.invokeStatic(util.clj:271)
	at core2.util$then_compose.invoke(util.clj:268)
	at core2.node.Node.snapshot_async(node.clj:128)
	at core2.node.Node._open_sql_async(node.clj:106)
	at core2.api$open_sql_async.invokeStatic(api.clj:80)
	at core2.api$open_sql_async.invoke(api.clj:79)
	at core2.pgwire$cmd_exec_query$fn__20948.invoke(pgwire.clj:1494)
	at core2.pgwire$cmd_exec_query.invokeStatic(pgwire.clj:1493)
	at core2.pgwire$cmd_exec_query.invoke(pgwire.clj:1474)
	at core2.pgwire$cmd_exec_stmt.invokeStatic(pgwire.clj:1632)
	at core2.pgwire$cmd_exec_stmt.invoke(pgwire.clj:1609)
	at core2.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1678)
	at core2.pgwire$cmd_simple_query.invoke(pgwire.clj:1673)
	at core2.pgwire$conn_loop.invokeStatic(pgwire.clj:1841)
	at core2.pgwire$conn_loop.invoke(pgwire.clj:1762)
	at core2.pgwire$connect$fn__21098.invoke(pgwire.clj:1906)
	at core2.pgwire$connect.invokeStatic(pgwire.clj:1904)
	at core2.pgwire$connect.invoke(pgwire.clj:1858)
	at core2.pgwire$accept_loop$fn__21113$fn__21114$fn__21115.invoke(pgwire.clj:1977)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: clojure.lang.ExceptionInfo: Ingestion stopped: fixed-size-list vector already exists
	at core2.await$__GT_ingester_ex.invokeStatic(await.clj:17)
	at core2.await$__GT_ingester_ex.invoke(await.clj:16)
	at core2.await$await_tx_async$fn__8005.invoke(await.clj:30)
	at core2.await$await_tx_async.invokeStatic(await.clj:25)
	at core2.await$await_tx_async.invoke(await.clj:21)
	at core2.ingester$eval19762$fn$reify__19771.snapshot(ingester.clj:89)
	... 29 common frames omitted
Caused by: java.lang.IllegalStateException: fixed-size-list vector already exists
	at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:458)
	at org.apache.arrow.vector.complex.DenseUnionVector.addVector(DenseUnionVector.java:1064)
	at core2.vector.writer.DuvWriter$reify__6148.apply(writer.clj:190)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at core2.vector.writer.DuvWriter.writerForType(writer.clj:172)
	at core2.vector.writer$vec__GT_duv_copier.invokeStatic(writer.clj:104)
	at core2.vector.writer$vec__GT_duv_copier.invoke(writer.clj:101)
	at core2.vector.writer.DuvWriter.rowCopier(writer.clj:156)
	at core2.vector.indirect.DirectVector.rowCopier(indirect.clj:157)
	at core2.indexer$doc_row_copier.invokeStatic(indexer.clj:430)
	at core2.indexer$doc_row_copier.invoke(indexer.clj:426)
	at core2.indexer$$reify__19455$iter__19457__19461$fn__19462$fn__19463.invoke(indexer.clj:559)
	at core2.indexer$$reify__19455$iter__19457__19461$fn__19462.invoke(indexer.clj:557)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.PersistentVector.create(PersistentVector.java:73)
	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
	at clojure.core$vec.invokeStatic(core.clj:379)
	at clojure.core$vec.invoke(core.clj:369)
	at core2.indexer$$reify__19455.indexOp(indexer.clj:555)
	at core2.indexer$$reify__19551$index_op__19552$fn$reify__19558.accept(indexer.clj:698)
	at core2.operator.rename.RenameCursor$reify__14263.accept(rename.clj:41)
	at core2.operator.table.TableCursor$fn__14570.invoke(table.clj:33)
	at core2.operator.table.TableCursor.tryAdvance(table.clj:31)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator$wrap_cursor$reify__14896.tryAdvance(operator.clj:45)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at core2.indexer$$reify__19551$index_op__19552$fn__19557.invoke(indexer.clj:695)
	at core2.indexer$$reify__19551$index_op__19552.invoke(indexer.clj:692)
	at core2.indexer$$reify__19551.indexOp(indexer.clj:701)
	at core2.indexer.Indexer$fn__19596.invoke(indexer.clj:775)
	at core2.indexer.Indexer.indexTx(indexer.clj:769)
	at core2.ingester$eval19762$fn$reify__19766.acceptRecord(ingester.clj:75)
	at core2.log$tx_handler$fn__19695.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.log.NotifyingSubscriberHandler$fn__19728.invoke(log.clj:87)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 common frames omitted
```

I was in the process of experimenting with arrays when this happened, e.g.
Everything was okay when I tried:
```
jdt=> SELECT * FROM a AS x (id, arr);
  id  |      arr       
------+----------------
 1234 | "sdf"
 1234 | "{\"a\":2}"
 1234 | "{\"a\":2}"
 1234 | ["as","ldld"]
 1234 | "ARRAY [1, 3]"
(5 rows)
```
...and then broke around the time I ran:
 `INSERT INTO a (id, name, foo, arr, cols) VALUES (1234, 4579999, 'asdf', [9,0], 'id name foo arr')`

After restarting everything, things seems okay so far. I'm not going to attempt to find a repro right now.

**Comment by refset** [comment]
Repro:

`INSERT INTO a (id, arr) VALUES (1234, [9,0]);` (works)
...then...
`INSERT INTO a (id, arr) VALUES (1234, [9,0,1]);` (dies)
`INSERT INTO a (id, arr) VALUES (1234, [9,[]]);` (was wondering if it was purely an item count thing, but this also dies)

```
11:31:14.724 [core2-tx-subscription-pool-1-thread-1] ERROR core2.util - Uncaught exception:
java.lang.IllegalStateException: fixed-size-list vector already exists
	at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:458)
	at org.apache.arrow.vector.complex.DenseUnionVector.addVector(DenseUnionVector.java:1064)
	at core2.vector.writer.DuvWriter$reify__6148.apply(writer.clj:190)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at core2.vector.writer.DuvWriter.writerForType(writer.clj:172)
	at core2.vector.writer$vec__GT_duv_copier.invokeStatic(writer.clj:104)
	at core2.vector.writer$vec__GT_duv_copier.invoke(writer.clj:101)
	at core2.vector.writer.DuvWriter.rowCopier(writer.clj:156)
	at core2.vector.indirect.DirectVector.rowCopier(indirect.clj:157)
	at core2.indexer$doc_row_copier.invokeStatic(indexer.clj:430)
	at core2.indexer$doc_row_copier.invoke(indexer.clj:426)
	at core2.indexer$$reify__19455$iter__19457__19461$fn__19462$fn__19463.invoke(indexer.clj:559)
	at core2.indexer$$reify__19455$iter__19457__19461$fn__19462.invoke(indexer.clj:557)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.PersistentVector.create(PersistentVector.java:73)
	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
	at clojure.core$vec.invokeStatic(core.clj:379)
	at clojure.core$vec.invoke(core.clj:369)
	at core2.indexer$$reify__19455.indexOp(indexer.clj:555)
	at core2.indexer$$reify__19551$index_op__19552$fn$reify__19558.accept(indexer.clj:698)
	at core2.operator.rename.RenameCursor$reify__14263.accept(rename.clj:41)
	at core2.operator.table.TableCursor$fn__14570.invoke(table.clj:33)
	at core2.operator.table.TableCursor.tryAdvance(table.clj:31)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator$wrap_cursor$reify__14896.tryAdvance(operator.clj:45)
:332)	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java
	at core2.indexer$$reify__19551$index_op__19552$fn__19557.invoke(indexer.clj:695)
	at core2.indexer$$reify__19551$index_op__19552.invoke(indexer.clj:692)
	at core2.indexer$$reify__19551.indexOp(indexer.clj:701)
	at core2.indexer.Indexer$fn__19596.invoke(indexer.clj:775)
	at core2.indexer.Indexer.indexTx(indexer.clj:769)
	at core2.ingester$eval19762$fn$reify__19766.acceptRecord(ingester.clj:75)
	at core2.log$tx_handler$fn__19695.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.log.NotifyingSubscriberHandler$fn__19728.invoke(log.clj:87)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
11:31:14.724 [pgwire-connection--pool-3-thread-1] DEBUG core2.pgwire - Error on await-tx
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: Ingestion stopped: fixed-size-list vector already exists {}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at clojure.core$deref_future.invokeStatic(core.clj:2317)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at core2.pgwire$submit_tx$fn__20918.invoke(pgwire.clj:1419)
	at core2.pgwire$submit_tx.invokeStatic(pgwire.clj:1419)
	at core2.pgwire$submit_tx.invoke(pgwire.clj:1406)
	at core2.pgwire$cmd_exec_dml.invokeStatic(pgwire.clj:1460)
	at core2.pgwire$cmd_exec_dml.invoke(pgwire.clj:1443)
	at core2.pgwire$cmd_exec_stmt.invokeStatic(pgwire.clj:1633)
	at core2.pgwire$cmd_exec_stmt.invoke(pgwire.clj:1609)
	at core2.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1678)
e$cmd_simple_query.invoke(pgwire.clj:1673)
	at core2.pgwire$conn_loop.invokeStatic(pgwire.clj:1841)
	at core2.pgwire$conn_loop.invoke(pgwire.clj:1762)
	at core2.pgwire$connect$fn__21098.invoke(pgwire.clj:1906)
	at core2.pgwire$connect.invokeStatic(pgwire.clj:1904)
	at core2.pgwire$connect.invoke(pgwire.clj:1858)
	at core2.pgwire$accept_loop$fn__21113$fn__21114$fn__21115.invoke(pgwire.clj:1977)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: clojure.lang.ExceptionInfo: Ingestion stopped: fixed-size-list vector already exists
	at core2.await$__GT_ingester_ex.invokeStatic(await.clj:17)
	at core2.await$__GT_ingester_ex.invoke(await.clj:16)
	at core2.await$notify_ex.invokeStatic(await.clj:58)
	at core2.await$notify_ex.invoke(await.clj:54)
	at core2.ingester$eval19762$fn$reify__19766.acceptRecord(ingester.clj:80)
	at core2.log$tx_handler$fn__19695.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.log.NotifyingSubscriberHandler$fn__19728.invoke(log.clj:87)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 common frames omitted
Caused by: java.lang.IllegalStateException: fixed-size-list vector already exists
	at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:458)
java:1064) org.apache.arrow.vector.complex.DenseUnionVector.addVector(DenseUnionVector.
	at core2.vector.writer.DuvWriter$reify__6148.apply(writer.clj:190)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at core2.vector.writer.DuvWriter.writerForType(writer.clj:172)
	at core2.vector.writer$vec__GT_duv_copier.invokeStatic(writer.clj:104)
	at core2.vector.writer$vec__GT_duv_copier.invoke(writer.clj:101)
	at core2.vector.writer.DuvWriter.rowCopier(writer.clj:156)
	at core2.vector.indirect.DirectVector.rowCopier(indirect.clj:157)
	at core2.indexer$doc_row_copier.invokeStatic(indexer.clj:430)
	at core2.indexer$doc_row_copier.invoke(indexer.clj:426)
	at core2.indexer$$reify__19455$iter__19457__19461$fn__19462$fn__19463.invoke(indexer.clj:559)
	at core2.indexer$$reify__19455$iter__19457__19461$fn__19462.invoke(indexer.clj:557)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.PersistentVector.create(PersistentVector.java:73)
	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
	at clojure.core$vec.invokeStatic(core.clj:379)
	at clojure.core$vec.invoke(core.clj:369)
	at core2.indexer$$reify__19455.indexOp(indexer.clj:555)
	at core2.indexer$$reify__19551$index_op__19552$fn$reify__19558.accept(indexer.clj:698)
	at core2.operator.rename.RenameCursor$reify__14263.accept(rename.clj:41)
	at core2.operator.table.TableCursor$fn__14570.invoke(table.clj:33)
	at core2.operator.table.TableCursor.tryAdvance(table.clj:31)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator$wrap_cursor$reify__14896.tryAdvance(operator.clj:45)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at core2.indexer$$reify__19551$index_op__19552$fn__19557.invoke(indexer.clj:695)
	at core2.indexer$$reify__19551$index_op__19552.invoke(indexer.clj:692)
	at core2.indexer$$reify__19551.indexOp(indexer.clj:701)
	at core2.indexer.Indexer$fn__19596.invoke(indexer.clj:775)
er.clj:769)core2.indexer.Indexer.indexTx(index
	at core2.ingester$eval19762$fn$reify__19766.acceptRecord(ingester.clj:75)
	... 10 common frames omitted
```

**Comment by jarohen** [comment]
@refset: think this is xtdb/xtdb#2286?

**Comment by refset** [comment]
Yep that looks the same :ok_hand:
