### ISSUE TITLE
Implement codegen-mono-call [:= :struct :struct]

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2335]
Currently, when attempting to filter records using top-level objects:

```
jdt=> INSERT into x (id, obj) VALUES (1234, {'a':123});
INSERT 0 0
jdt=> SELECT x.id FROM x WHERE x.id = 1234;
  id  
------
 1234
(1 row)

jdt=> SELECT x.id FROM x WHERE x.obj = {'a':123};
ERROR:  unexpected server error during query execution
```

```
22:56:06.344 [pgwire-connection--pool-31-thread-13] DEBUG core2.pgwire - Error during query open-sql-async
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: No method in multimethod 'codegen-mono-call' for dispatch value: [:= :struct :struct]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at core2.util$then_apply.invokeStatic(util.clj:266)
	at core2.util$then_apply.invoke(util.clj:263)
	at core2.node.Node._open_sql_async(node.clj:113)
	at core2.api$open_sql_async.invokeStatic(api.clj:80)
	at core2.api$open_sql_async.invoke(api.clj:79)
	at core2.pgwire$cmd_exec_query$fn__20948.invoke(pgwire.clj:1494)
	at core2.pgwire$cmd_exec_query.invokeStatic(pgwire.clj:1493)
	at core2.pgwire$cmd_exec_query.invoke(pgwire.clj:1474)
	at core2.pgwire$cmd_exec_stmt.invokeStatic(pgwire.clj:1632)
	at core2.pgwire$cmd_exec_stmt.invoke(pgwire.clj:1609)
	at core2.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1678)
	at core2.pgwire$cmd_simple_query.invoke(pgwire.clj:1673)
	at core2.pgwire$conn_loop.invokeStatic(pgwire.clj:1841)
	at core2.pgwire$conn_loop.invoke(pgwire.clj:1762)
	at core2.pgwire$connect$fn__21098.invoke(pgwire.clj:1906)
	at core2.pgwire$connect.invokeStatic(pgwire.clj:1904)
	at core2.pgwire$connect.invoke(pgwire.clj:1858)
	at core2.pgwire$accept_loop$fn__21113$fn__21114$fn__21115.invoke(pgwire.clj:1977)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'codegen-mono-call' for dispatch value: [:= :struct :struct]
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at core2.expression$eval6779$fn__6781$iter__6811__6815$fn__6816.invoke(expression.clj:501)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$into.invokeStatic(core.clj:6958)
	at clojure.core$into.invoke(core.clj:6950)
	at core2.expression$eval6779$fn__6781.invoke(expression.clj:504)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at core2.expression$eval6893$fn__6895.invoke(expression.clj:586)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.expression$eval6893$fn__6895$iter__6897__6901$fn__6902$fn__6903.invoke(expression.clj:585)
	at core2.expression$eval6893$fn__6895$iter__6897__6901$fn__6902.invoke(expression.clj:584)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.expression$eval6779$fn__6781.invoke(expression.clj:490)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at core2.expression$eval6893$fn__6895.invoke(expression.clj:586)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.expression$fn__7874.invokeStatic(expression.clj:1421)
	at core2.expression$fn__7874.invoke(expression.clj:1418)
	at core2.util$lru_memoize$fn__4535.invoke(util.clj:607)
	at core2.expression$wrap_zone_id_cache_buster$fn__7870.invoke(expression.clj:1411)
	at core2.expression$emit_prim_expr.invokeStatic(expression.clj:1469)
	at core2.expression$emit_prim_expr.invoke(expression.clj:1449)
	at core2.expression$eval7959$fn__7962.invoke(expression.clj:1510)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at core2.expression$__GT_expression_projection_spec.invokeStatic(expression.clj:1524)
	at core2.expression$__GT_expression_projection_spec.invoke(expression.clj:1519)
	at core2.expression$__GT_expression_relation_selector.invokeStatic(expression.clj:1545)
	at core2.expression$__GT_expression_relation_selector.invoke(expression.clj:1544)
	at core2.operator.scan$eval13710$fn__13713$iter__13745__13749$fn__13750.invoke(scan.clj:302)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$into.invokeStatic(core.clj:6958)
	at clojure.core$into.invoke(core.clj:6950)
	at core2.operator.scan$eval13710$fn__13713.invoke(scan.clj:303)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.rename$eval14276$fn__14278.invoke(rename.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.project$eval13234$fn__13237.invoke(project.clj:96)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.logical_plan$unary_expr.invokeStatic(logical_plan.clj:67)
	at core2.logical_plan$unary_expr.invoke(logical_plan.clj:66)
	at core2.operator.rename$eval14276$fn__14278.invoke(rename.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.operator$prepare_ra$reify$reify__14903.apply(operator.clj:81)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at core2.operator$prepare_ra$reify__14900.bind(operator.clj:74)
	at core2.node.Node$fn__20033.invoke(node.clj:115)
	at core2.util$$reify__4426.apply(util.clj:256)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	... 26 common frames omitted
```

**Comment by jarohen** [comment]
@refset: think this is xtdb/xtdb#2289?

**Comment by refset** [comment]
Yep, this one is a dupe. Thanks (and sorry for the noise!)
