### ISSUE TITLE
Timestamp print-dup EE error when using Core2 as a library

### ISSUE THREAD

**Issue by refset** [xtdb/crux#2337]
Everything works fine using Core2 via Docker, but when I use Core2 as an in-process library this error is seen: `Can't embed object in code, maybe print-dup not defined: 9999-12-31T23:59:59.999999Z`

```
jdt=> INSERT INTO posts (id, user_id, text)
                             VALUES (1234, 5678, 'Hello World!');
INSERT 0 0
jdt=> SELECT posts.id FROM posts;
  id  
------
 1234
(1 row)

jdt=> ERASE FROM posts WHERE posts.id=1234;
ERASE 0
jdt=> SELECT posts.id FROM posts;
ERROR:  unexpected server error during query execution
```

```13:52:16.847 [pgwire-connection--pool-11-thread-1] DEBUG core2.pgwire - Error during query open-sql-async
java.util.concurrent.CompletionException: clojure.lang.ExceptionInfo: Ingestion stopped: Syntax error compiling fn* at (0:0). {}
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at core2.util$then_apply.invokeStatic(util.clj:266)
	at core2.util$then_apply.invoke(util.clj:263)
	at core2.ingester$eval19762$fn$reify__19771.snapshot(ingester.clj:94)
	at core2.node.Node$fn__20036.invoke(node.clj:129)
	at core2.util$$reify__4426.apply(util.clj:256)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at core2.util$then_compose.invokeStatic(util.clj:271)
	at core2.util$then_compose.invoke(util.clj:268)
	at core2.node.Node.snapshot_async(node.clj:128)
	at core2.node.Node._open_sql_async(node.clj:106)
	at core2.api$open_sql_async.invokeStatic(api.clj:80)
	at core2.api$open_sql_async.invoke(api.clj:79)
	at core2.pgwire$cmd_exec_query$fn__20948.invoke(pgwire.clj:1494)
	at core2.pgwire$cmd_exec_query.invokeStatic(pgwire.clj:1493)
	at core2.pgwire$cmd_exec_query.invoke(pgwire.clj:1474)
	at core2.pgwire$cmd_exec_stmt.invokeStatic(pgwire.clj:1632)
	at core2.pgwire$cmd_exec_stmt.invoke(pgwire.clj:1609)
	at core2.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1678)
	at core2.pgwire$cmd_simple_query.invoke(pgwire.clj:1673)
	at core2.pgwire$conn_loop.invokeStatic(pgwire.clj:1841)
	at core2.pgwire$conn_loop.invoke(pgwire.clj:1762)
	at core2.pgwire$connect$fn__21098.invoke(pgwire.clj:1906)
	at core2.pgwire$connect.invokeStatic(pgwire.clj:1904)
	at core2.pgwire$connect.invoke(pgwire.clj:1858)
	at core2.pgwire$accept_loop$fn__21113$fn__21114$fn__21115.invoke(pgwire.clj:1977)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: clojure.lang.ExceptionInfo: Ingestion stopped: Syntax error compiling fn* at (0:0).
	at core2.await$__GT_ingester_ex.invokeStatic(await.clj:17)
	at core2.await$__GT_ingester_ex.invoke(await.clj:16)
	at core2.await$await_tx_async$fn__8005.invoke(await.clj:30)
	at core2.await$await_tx_async.invokeStatic(await.clj:25)
	at core2.await$await_tx_async.invoke(await.clj:21)
	at core2.ingester$eval19762$fn$reify__19771.snapshot(ingester.clj:89)
	... 29 common frames omitted
Caused by: clojure.lang.Compiler$CompilerException: Syntax error compiling fn* at (0:0).
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7132)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5479)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4041)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.eval(Compiler.java:7191)
	at clojure.lang.Compiler.eval(Compiler.java:7149)
	at clojure.core$eval.invokeStatic(core.clj:3215)
	at clojure.core$eval.invoke(core.clj:3211)
	at core2.expression$fn__7874$fn__7877.invoke(expression.clj:1426)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at core2.expression$emit_prim_expr$fn__7922.invoke(expression.clj:1495)
	at core2.expression$$reify__7971.project(expression.clj:1542)
	at core2.expression$$reify__7977.select(expression.clj:1548)
	at core2.operator.scan$apply_temporal_preds$fn__13615.invoke(scan.clj:151)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.operator.scan$apply_temporal_preds.invokeStatic(scan.clj:149)
	at core2.operator.scan$apply_temporal_preds.invoke(scan.clj:144)
	at core2.operator.scan.ScanCursor$next_block__13645$fn__13646.invoke(scan.clj:202)
	at core2.operator.scan.ScanCursor$next_block__13645.invoke(scan.clj:201)
	at core2.operator.scan.ScanCursor$live_chunk__13659.invoke(scan.clj:226)
	at core2.operator.scan.ScanCursor.tryAdvance(scan.clj:257)
	at core2.coalesce.CoalescingCursor.tryAdvance(coalesce.clj:24)
	at core2.util$and_also_close$reify__4514.tryAdvance(util.clj:533)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator.project.ProjectCursor.tryAdvance(project.clj:72)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator$wrap_cursor$reify__14896.tryAdvance(operator.clj:45)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at core2.indexer$$reify__19551$index_op__19552$fn__19557.invoke(indexer.clj:695)
	at core2.indexer$$reify__19551$index_op__19552.invoke(indexer.clj:692)
	at core2.indexer$$reify__19551.indexOp(indexer.clj:701)
	at core2.indexer.Indexer$fn__19596.invoke(indexer.clj:775)
	at core2.indexer.Indexer.indexTx(indexer.clj:769)
	at core2.ingester$eval19762$fn$reify__19766.acceptRecord(ingester.clj:75)
	at core2.log$tx_handler$fn__19695.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.log.NotifyingSubscriberHandler$fn__19728.invoke(log.clj:87)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 common frames omitted
Caused by: java.lang.RuntimeException: Can't embed object in code, maybe print-dup not defined: 9999-12-31T23:59:59.999999Z
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$ObjExpr.emitValue(Compiler.java:4905)
	at clojure.lang.Compiler$ObjExpr.emitConstants(Compiler.java:4946)
	at clojure.lang.Compiler$ObjExpr.compile(Compiler.java:4624)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4118)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	... 58 common frames omitted
```

**Comment by refset** [comment]
As per the repro in xtdb/xtdb#2338 - this can be trivially triggered without any interesting DML:
```
  (core2.api/submit-tx my-node
                       [[:sql
                         "INSERT INTO foo (id) VALUES (1)"]])

  (core2.api/sql-query my-node
                       "SELECT foo.id FROM foo FOR ALL SYSTEM_TIME"
                       {})
```

**Comment by refset** [comment]
@mbutlerw suggested doing this may fix it https://github.com/xtdb/core2/blob/3d6d6e43594437e05e8a969cc4a28046752f3002/dev/user.clj#L31 - ultimately Core2 should probably do this on the users' behalf though if library usage is at all important.

**Comment by mbutlerw** [comment]
Take this will a small grain of salt as printouts from pgwire queries seemed out of sync. That being said, this ERASE query creates this plan.

```
ERASE FROM posts WHERE posts.id=1234
```

```
[:rename
 {x2 _iid,
  x3 _row-id,
  x4 application_time_start,
  x5 application_time_end,
  x6 system_time_start,
  x7 system_time_end}
 [:project
  [x2 x3 x4 x5 x6 x7]
  [:rename
   {id x1,
    _iid x2,
    _row-id x3,
    application_time_start x4,
    application_time_end x5,
    system_time_start x6,
    system_time_end x7}
   [:scan
    posts
    [{id (= id 1234)}
     _iid
     _row-id
     application_time_start
     application_time_end
     system_time_start
     {system_time_end (<= system_time_end core2/end-of-time)}]]]]]
```

The code generated for the system_time_end pred looks like below and contains `#time/instant "9999-12-31T23:59:59.999999Z"` which would require the reader implementations from time-literals to parse.

```
(clojure.core/fn
 [rel15135 params15136 out-vec16503]
 (clojure.core/let
  [system_time_end
   (.monoReader (.vectorForName rel15135 "system_time_end"))
   lit42176
   (core2.util/instant->micros
    #time/instant "9999-12-31T23:59:59.999999Z")
   out-writer-sym16504
   (core2.vector/->mono-writer out-vec16503)
   row-count__16555__auto__
   (.rowCount rel15135)]
  (clojure.core/dotimes
   [idx15134 row-count__16555__auto__]
   (.writeBoolean
    out-writer-sym16504
    (clojure.core/not
     (clojure.core/pos?
      (java.lang.Math/subtractExact
       (.readLong system_time_end idx15134)
       lit42176)))))))
```
