### ISSUE TITLE
IOOBE in `row-id-aligned-blocks`

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2373]
As mentioned by @jarohen the IOOBE in `row-id-aligned-blocks` might trigger a Memory Leak.
See https://github.com/xtdb/core2/blob/2197ac8b648e67b3c05c444be99f356d47d15b06/core/src/core2/indexer.clj#L925
Relevant Stacktrace
```
java.lang.IndexOutOfBoundsException: index: 0, length: 1 (expected: range(0, 0))
	at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:319)
	at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:306)
	at org.apache.arrow.memory.ArrowBuf.getByte(ArrowBuf.java:508)
	at org.apache.arrow.vector.BaseFixedWidthVector.isSet(BaseFixedWidthVector.java:800)
	at org.apache.arrow.vector.BigIntVector.get(BigIntVector.java:111)
	at core2.blocks$row_id_aligned_blocks$count_seq__16662$fn__16663.invoke(blocks.clj:47)
	at core2.blocks$row_id_aligned_blocks$count_seq__16662.invokePrim(blocks.clj:44)
	at core2.blocks$row_id_aligned_blocks$count_seq__16662.invoke(blocks.clj)
	at core2.blocks$row_id_aligned_blocks.invokeStatic(blocks.clj:54)
	at core2.blocks$row_id_aligned_blocks.invokePrim(blocks.clj)
	at core2.watermark.Watermark$iter__21978__21982$fn__21983$fn__21984$fn__21985.invoke(watermark.clj:58)
	at clojure.core$keep$fn__8645$fn__8646.invoke(core.clj:7393)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core$into.invokeStatic(core.clj:6962)
	at clojure.core$into.invoke(core.clj:6950)
	at core2.watermark.Watermark$iter__21978__21982$fn__21983$fn__21984.invoke(watermark.clj:55)
	at core2.watermark.Watermark$iter__21978__21982$fn__21983.invoke(watermark.clj:53)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.lang.SeqIterator.hasNext(SeqIterator.java:38)
	at core2.operator.scan.ScanCursor$live_chunk__22265.invoke(scan.clj:228)
	at core2.operator.scan.ScanCursor.tryAdvance(scan.clj:262)
	at core2.coalesce.CoalescingCursor.tryAdvance(coalesce.clj:24)
	at core2.util$and_also_close$reify__2515.tryAdvance(util.clj:533)
	at core2.operator$wrap_cursor$reify__23571.tryAdvance(operator.clj:58)
	at core2.indexer$find_fn.invokeStatic(indexer.clj:556)
	at core2.indexer$find_fn.invoke(indexer.clj:542)
	at core2.indexer$$reify__33038.indexOp(indexer.clj:624)
	at core2.indexer.Indexer$index_tx_ops__33189.invoke(indexer.clj:922)
	at core2.indexer.Indexer$fn__33206.invoke(indexer.clj:929)
	at core2.indexer.Indexer.indexTx(indexer.clj:928)
	at core2.ingester$eval33275$fn$reify__33279.acceptRecord(ingester.clj:75)
	at core2.log$tx_handler$fn__27816.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at core2.log$handle_polling_subscription$fn__27822.invoke(log.clj:48)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jarohen** [comment]
re-open if we see it again
