### ISSUE TITLE
Unhandled ClosedByInterruptException

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2415]
Getting the following when running `api-test/test-basic-sql-dml` on master. Doesn't seem to happen on CI.
```clj
17:00:50.281 [xtdb-tx-subscription-pool-1-thread-6] ERROR xtdb.util - Uncaught exception:
java.nio.channels.ClosedByInterruptException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:390)
	at org.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:60)
	at org.apache.arrow.vector.ipc.message.MessageSerializer.readMessage(MessageSerializer.java:683)
	at org.apache.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:57)
	at org.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:145)
	at xtdb.indexer$$reify__36304$index_op__36305.invoke(indexer.clj:445)
	at xtdb.indexer$$reify__36304.indexOp(indexer.clj:461)
	at xtdb.indexer.Indexer$index_tx_ops__36328.invoke(indexer.clj:523)
	at xtdb.indexer.Indexer$fn__36345.invoke(indexer.clj:534)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:533)
	at xtdb.ingester$eval36402$fn$reify__36406.acceptRecord(ingester.clj:67)
	at xtdb.log$tx_handler$fn__35918.invoke(log.clj:34)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8246.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8246.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8194$G__8189__8207.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6895)
	at clojure.core$reduce.invoke(core.clj:6877)
	at xtdb.log.NotifyingSubscriberHandler$fn__35951.invoke(log.clj:87)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by FiV0** [comment]
This actually seems to make the node hang.
