### ISSUE TITLE
Correctly deal with `ClosedChannelException` in `xtdb.log`

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2518]
Currently a `ClosedChannelException` potentially results in an infinite loop in `xtdb.log` when trying to read records around here
https://github.com/xtdb/xtdb/blob/2.x/core/src/main/clojure/xtdb/log.clj#L51
```
java.nio.channels.ClosedChannelException: null
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:159)
	at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:356)
	at xtdb.log.local_directory_log.LocalDirectoryLog.readRecords(local_directory_log.clj:36)
	at xtdb.log$handle_polling_subscription$fn__92954$fn__92957.invoke(log.clj:52)
	at xtdb.log$handle_polling_subscription$fn__92954.invoke(log.clj:51)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by FiV0** [comment]
Closed in #2519
