### ISSUE TITLE
Checkpoint restore hang using AWS S3 CRT client with multiple nodes

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2567]
(thanks @avocade for your help in isolating this one!)

```clojure
{:xtdb/index-store {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store,
                               :db-dir "..."
                               :sync? true 
                               :checkpointer {:xtdb/module xtdb.checkpoint/->checkpointer,
                                              :store {:xtdb/module xtdb.s3.checkpoint-transfer-manager/->cp-store,
                                                      :configurator app.system.xtdb/->crt-configurator,
                                                      :bucket "...",
                                                      :prefix "..."},
                                              :approx-frequency "PT1H"}}}
 :xtdb.lucene/lucene-store {...}}
```

Behaviour observed:

* First node starts up fine, either with an existing index store, a fresh index store with checkpoints to restore, or a fresh index store with no checkpoints (i.e. playing the full log)
* Subsequent nodes hang trying to restore the checkpoint, as if it's waiting on a lock or something:
  ```
  "main" #1 prio=5 os_prio=0 cpu=11995.41ms elapsed=359.84s tid=0x0000ffffa80258a0 nid=0xa waiting on condition  [0x0000ffffaceb3000]
     java.lang.Thread.State: WAITING (parking)
      at jdk.internal.misc.Unsafe.park(java.base@17.0.5/Native Method)
      - parking to wait for  <0x00000007fd121070> (a java.util.concurrent.CompletableFuture$Signaller)
      ...
      at java.util.concurrent.CompletableFuture.join(java.base@17.0.5/CompletableFuture.java:2117)
      at xtdb.s3.checkpoint_transfer_manager.CheckpointStore$fn__55234.invoke(checkpoint_transfer_manager.clj:70)
      at xtdb.s3.checkpoint_transfer_manager.CheckpointStore.download_checkpoint(checkpoint_transfer_manager.clj:52)
      at xtdb.checkpoint.ScheduledCheckpointer.try_restore(checkpoint.clj:74)
      at xtdb.rocksdb$__GT_kv_store.invokeStatic(rocksdb.clj:307)
      at xtdb.rocksdb$__GT_kv_store.invoke(rocksdb.clj:270)
      ...
      at xtdb.system$start_system.invokeStatic(system.clj:203)
      at xtdb.system$start_system.invoke(system.clj:197)
      at xtdb.api$start_node.invokeStatic(api.clj:306)
      at xtdb.api$start_node.invoke(api.clj:282)
   ```

System in question is running on k8s, with two XT nodes on two separate k8s nodes (i.e. no shared filesystems etc)

**Comment by jarohen** [comment]
I've temporarily (ea0f676b) reduced the recommendation in our docs - once this is resolved, we can go back to recommending the newer module :slightly_smiling_face:
