### ISSUE TITLE
Including `finish-chunk` in `test-aligns-temporal-columns-correctly-363` breaks the test

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2641]
Stacktrace

```
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at xtdb.indexer.live_index.LiveIndex.liveTable(live_index.clj:216)
	at xtdb.indexer.live_index.LiveIndex$reify$reify__19055.apply(live_index.clj:228)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at xtdb.indexer.live_index.LiveIndex$reify__19054.liveTable(live_index.clj:225)
	at xtdb.indexer$__GT_put_indexer$fn__23590.invoke(indexer.clj:81)
	at clojure.core$mapv$fn__8551.invoke(core.clj:6988)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8246.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8246.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8194$G__8189__8207.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6895)
	at clojure.core$mapv.invokeStatic(core.clj:6979)
	at clojure.core$mapv.invoke(core.clj:6979)
	at xtdb.indexer$__GT_put_indexer.invokeStatic(indexer.clj:75)
	at xtdb.indexer$__GT_put_indexer.invoke(indexer.clj:67)
	at xtdb.indexer.Indexer$fn__23720$index_tx_ops__23723$fn__23724.invoke(indexer.clj:496)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at xtdb.indexer.Indexer$fn__23720$index_tx_ops__23723.invoke(indexer.clj:504)
	at xtdb.indexer.Indexer$fn__23720$fn__23740.invoke(indexer.clj:514)
	at xtdb.indexer.Indexer$fn__23720.invoke(indexer.clj:513)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:479)
```

My suspicion here is that, at least in test, the `tables` HashMap has the potential to be concurrently modified.

In the running system finish chunk and tx-op processing happens within the same loop. In test, we call finish chunk and rely on await-tx to avoid concurrent modification, which should and on the most part does work, but I could imagine it failing.

Speculation here as I was unable to repro, one to watch I think.

**Comment by FiV0** [comment]
This seems to have been fixed at some point during the temporal index change.

**Comment by FiV0** [comment]
Reopening with https://github.com/xtdb/xtdb/actions/runs/5865839531/job/15903517259.

**Comment by mbutlerw** [comment]
Perhaps related to test-metadata-filtering-for-time-data-607 failing, considering this the card for them both for now.

**Comment by mbutlerw** [comment]
After Closer inspection I don't believe these failures are related.
