### ISSUE TITLE
CI timeouts

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#2692]
_finally_ got a hang locally 😅 

```
"Test worker" #1 prio=5 os_prio=0 cpu=33075.31ms elapsed=479.82s tid=0x00007fee7c0201d0 nid=0x2527 waiting on condition  [0x00007fee837fb000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.8.1/Native Method)
        - parking to wait for  <0x000000071047e108> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.8.1/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.8.1/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.8.1/ForkJoinPool.java:3465)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.8.1/ForkJoinPool.java:3436)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.8.1/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.get(java.base@17.0.8.1/CompletableFuture.java:2072)
        at clojure.core$deref_future.invokeStatic(core.clj:2317)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at xtdb.test_util$then_await_tx.invokeStatic(test_util.clj:107)
        at xtdb.test_util$then_await_tx.invoke(test_util.clj:107)
        at xtdb.test_util$then_await_tx.invokeStatic(test_util.clj:109)
        at xtdb.test_util$then_await_tx.invoke(test_util.clj:107)
        at xtdb.test_util$query_ra.invokeStatic(test_util.clj:207)
        at xtdb.test_util$query_ra.invoke(test_util.clj:201)
        at xtdb.as_of_test$fn__45962$fn__45963.invoke(as_of_test.clj:87)
        at xtdb.as_of_test$fn__45962.invokeStatic(as_of_test.clj:86)
        at xtdb.as_of_test$fn__45962.invoke(as_of_test.clj:61)
        at dev.clojurephant.jovial.engine.clojure_test$eval886$fn__889.invoke(clojure_test.clj:34)
  ...
```

**Comment by jarohen** [comment]
_finally_ got a hang locally, looks like something in as-of-test
