### ISSUE TITLE
`invalid Arrow IPC file format` when evaluating tx-fn

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2813]
When running Auctionmark with tx-fns
```clj
11:23:12.668 [xtdb-tx-subscription-pool-3-thread-23] WARN  xtdb.indexer - unhandled error evaluating tx fn
xtdb.IllegalArgumentException: invalid Arrow IPC file format
	at xtdb.error$illegal_arg.invokeStatic(error.clj:13)
	at xtdb.error$illegal_arg.invoke(error.clj:4)
	at xtdb.error$illegal_arg.invokeStatic(error.clj:8)
	at xtdb.error$illegal_arg.invoke(error.clj:4)
	at xtdb.util$validate_arrow_magic.invokeStatic(util.clj:444)
	at xtdb.util$validate_arrow_magic.invoke(util.clj:437)
	at xtdb.util$read_arrow_footer.invokeStatic(util.clj:448)
	at xtdb.util$read_arrow_footer.invoke(util.clj:447)
	at xtdb.util$read_arrow_buf.invokeStatic(util.clj:558)
	at xtdb.util$read_arrow_buf.invoke(util.clj:557)
	at xtdb.trie$open_meta_file.invokeStatic(trie.clj:301)
	at xtdb.trie$open_meta_file.invoke(trie.clj:299)
	at xtdb.operator.scan$eval50223$fn$reify__50228$fn__50330$fn__50337$fn__50338$fn__50339.invoke(scan.clj:488)
	at clojure.core$mapv$fn__8551.invoke(core.clj:6988)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:345)
	at clojure.core$reduce.invokeStatic(core.clj:6894)
	at clojure.core$mapv.invokeStatic(core.clj:6979)
	at clojure.core$mapv.invoke(core.clj:6979)
	at xtdb.operator.scan$eval50223$fn$reify__50228$fn__50330$fn__50337$fn__50338.invoke(scan.clj:487)
	at xtdb.operator.scan$eval50223$fn$reify__50228$fn__50330$fn__50337.invoke(scan.clj:486)
	at xtdb.operator.scan$eval50223$fn$reify__50228$fn__50330.invoke(scan.clj:485)
	at xtdb.logical_plan$unary_expr$fn__40681.invoke(logical_plan.clj:120)
	at xtdb.logical_plan$unary_expr$fn__40681.invoke(logical_plan.clj:120)
	at xtdb.logical_plan$unary_expr$fn__40681.invoke(logical_plan.clj:120)
	at xtdb.logical_plan$unary_expr$fn__40681.invoke(logical_plan.clj:120)
	at xtdb.operator$prepare_ra$reify$reify__51625.openCursor(operator.clj:140)
	at xtdb.datalog$open_datalog_query.invokeStatic(datalog.clj:1237)
	at xtdb.datalog$open_datalog_query.invoke(datalog.clj:1204)
	at xtdb.indexer$tx_fn_q$tx_fn_q_STAR___100165.invoke(indexer.clj:200)
	at xtdb.indexer$tx_fn_q$tx_fn_q_STAR___100165.invoke(indexer.clj:194)
	at sci.impl.analyzer$return_call$reify__31012.eval(analyzer.cljc:1396)
	at sci.impl.analyzer$return_call$reify__31012.eval(analyzer.cljc:1396)
	at sci.impl.analyzer$analyze_let_STAR_$reify__30685.eval(analyzer.cljc:679)
	at sci.impl.analyzer$analyze_let_STAR_$reify__30685.eval(analyzer.cljc:689)
	at sci.impl.analyzer$analyze_let_STAR_$reify__30685.eval(analyzer.cljc:689)
	at sci.impl.analyzer$analyze_let_STAR_$reify__30685.eval(analyzer.cljc:689)
	at sci.impl.fns$fun$arity_1__29870.invoke(fns.cljc:105)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at xtdb.indexer$$reify__116573$fn__116574$fn__116575.invoke(NO_SOURCE_FILE:245)
	at xtdb.indexer$$reify__116573$fn__116574.invoke(NO_SOURCE_FILE:243)
	at xtdb.indexer$$reify__116573.indexOp(NO_SOURCE_FILE:242)
	at xtdb.indexer.Indexer$fn__100257$index_tx_ops__100260.invoke(indexer.clj:509)
	at xtdb.indexer.Indexer$fn__100257$fn__100277.invoke(indexer.clj:516)
	at xtdb.indexer.Indexer$fn__100257.invoke(indexer.clj:515)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:481)
	at xtdb.log.watcher$watch_log_BANG_$reify__100963.acceptRecord(watcher.clj:55)
	at xtdb.log$tx_handler$fn__54529.invoke(log.clj:35)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8246.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8246.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8194$G__8189__8207.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6895)
	at clojure.core$reduce.invoke(core.clj:6877)
	at xtdb.log$handle_polling_subscription$fn__54535.invoke(log.clj:49)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by FiV0** [comment]
Seems to have been fixed with da4d8ad4
