### ISSUE TITLE
Negative ref counts for ArrowBufs

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#2819]
I am still getting negative ref counts when running Auctionmark. Quite reliably after an initial loading phase. This hints at some double closing somewhere:
```
11:38:17.277 [core2-benchmark-pool-3-thread-2] ERROR xtdb.bench2.auctionmark - Error while executing xtdb.bench2.auctionmark$index_item_status_groups@65b4319b
java.lang.IllegalStateException: Ref count should be >= 1 for accessing the ArrowBuf
        at org.apache.arrow.memory.ArrowBuf.ensureAccessible(ArrowBuf.java:126)
        at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:312)
        at org.apache.arrow.memory.ArrowBuf.checkBytes(ArrowBuf.java:117)
        at org.apache.arrow.memory.util.ByteFunctionHelpers.equal(ByteFunctionHelpers.java:50)
        at org.apache.arrow.memory.util.ArrowBufPointer.equals(ArrowBufPointer.java:145)
        at clojure.lang.Util.equiv(Util.java:33)
        at xtdb.operator.scan$pick_leaf_row_BANG_.invokeStatic(scan.clj:182)
        at xtdb.operator.scan$pick_leaf_row_BANG_.invoke(scan.clj:177)
        at xtdb.operator.scan.TrieCursor$fn__19473.invoke(scan.clj:289)
        at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:272)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:84)
        at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:84)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:84)
        at xtdb.operator$wrap_cursor$reify__20694.tryAdvance(operator.clj:72)
        at xtdb.operator.CursorResultSet.hasNext(operator.clj:196)
        at clojure.lang.RT$4.invoke(RT.java:522)
        at clojure.lang.LazySeq.sval(LazySeq.java:44)
        at clojure.lang.LazySeq.seq(LazySeq.java:53)
        at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:61)
        at clojure.lang.ChunkedCons.next(ChunkedCons.java:45)
        at clojure.lang.PersistentVector.create(PersistentVector.java:81)
        at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
        at clojure.core$vec.invokeStatic(core.clj:379)
        at clojure.core$vec.invoke(core.clj:369)
        at xtdb.api$q_AMPERSAND_$reify__287.apply(api.clj:79)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at xtdb.api$q_AMPERSAND_.invokeStatic(api.clj:75)
        at xtdb.api$q_AMPERSAND_.invoke(api.clj:14)
        at xtdb.api$q.invokeStatic(api.clj:135)
        at xtdb.api$q.invoke(api.clj:82)
        at xtdb.bench2.auctionmark$q_now.invokeStatic(auctionmark.clj:14)
        at xtdb.bench2.auctionmark$q_now.invoke(auctionmark.clj:13)
        at xtdb.bench2.auctionmark$item_status_groups.invokeStatic(auctionmark.clj:334)
        at xtdb.bench2.auctionmark$item_status_groups.invoke(auctionmark.clj:333)
        at xtdb.bench2.auctionmark$index_item_status_groups.invokeStatic(auctionmark.clj:374)
        at xtdb.bench2.auctionmark$index_item_status_groups.invoke(auctionmark.clj:370)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at xtdb.bench2.auctionmark$wrap_in_catch$fn__26902.doInvoke(auctionmark.clj:572)
        at clojure.lang.RestFn.invoke(RestFn.java:411)
        at xtdb.bench2.measurement$wrap_transaction$instrumented_transaction__26590$fn__26591.invoke(measurement.clj:118)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:147)
        at xtdb.bench2.measurement$wrap_transaction$instrumented_transaction__26590.invoke(measurement.clj:118)
        at xtdb.bench2$compile_benchmark$compile_task__26349$run_freq_job__26374.invoke(bench2.clj:231)
        at xtdb.bench2$compile_benchmark$compile_task__26349$start_thread__26390$fn__26391.invoke(bench2.clj:204)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by FiV0** [comment]
Can't reproduce this anymore. I suspect it got somehow resolved by switching to the buffer pool only implementation.
