### ISSUE TITLE
Ingester exception on processing transaction function update halts ingestion on Kafka document store

### ISSUE THREAD

**Issue by jfhamlin** [xtdb/crux#2912]
This is the first update to any transaction function in this (development) XT deployment. No new nodes make it past this point. Kafka is being used for both TX and doc store.

```
10:45:21.299 [xtdb-tx-processor-1] ERROR xtdb.tx - Ingester error occurred
java.lang.ClassCastException: class clojure.lang.PersistentVector cannot be cast to class java.util.Map$Entry (clojure.lang.PersistentVector is in unnamed module of loader 'app'; java.util.Map$Entry is in module java.base of loader 'bootstrap')
at clojure.core$val.invokeStatic(core.clj:1576)
at 02:45 (UTC-8:00)	at clojure.core$val.invoke(core.clj:1576)
at 02:45 (UTC-8:00)	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
at 02:45 (UTC-8:00)	at clojure.core$filter$fn__5911.invoke(core.clj:2825)
at 02:45 (UTC-8:00)	at clojure.lang.LazySeq.sval(LazySeq.java:42)
at 02:45 (UTC-8:00)	at clojure.lang.LazySeq.seq(LazySeq.java:51)
at 02:45 (UTC-8:00)	at clojure.lang.RT.seq(RT.java:535)
at 02:45 (UTC-8:00)	at clojure.core$seq__5419.invokeStatic(core.clj:139)
at 02:45 (UTC-8:00)	at clojure.core$seq__5419.invoke(core.clj:139)
at 02:45 (UTC-8:00)	at xtdb.kafka.KafkaDocumentStore.submit_docs(kafka.clj:281)
at 02:45 (UTC-8:00)	at xtdb.fork.ForkedDocumentStore.abort_doc_store_tx(fork.clj:162)
at 02:45 (UTC-8:00)	at xtdb.tx.InFlightTx.abort(tx.clj:401)
at 02:45 (UTC-8:00)	at xtdb.tx$__GT_tx_ingester$fn__11440$txs_index_fn__11446.invoke(tx.clj:673)
at 02:45 (UTC-8:00)	at clojure.lang.AFn.applyToHelper(AFn.java:154)
at 02:45 (UTC-8:00)	at clojure.lang.AFn.applyTo(AFn.java:144)
at 02:45 (UTC-8:00)	at clojure.core$apply.invokeStatic(core.clj:667)
at 02:45 (UTC-8:00)	at clojure.core$apply.invoke(core.clj:662)
at 02:45 (UTC-8:00)	at xtdb.tx$__GT_tx_ingester$apply_if_not_done__11430.invoke(tx.clj:614)
at 02:45 (UTC-8:00)	at xtdb.tx$__GT_tx_ingester$fn__11440$submit_job_BANG___11441$fn__11442.invoke(tx.clj:649)
at 02:45 (UTC-8:00)	at clojure.lang.AFn.call(AFn.java:18)
at 02:45 (UTC-8:00)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at 02:45 (UTC-8:00)	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at 02:45 (UTC-8:00)	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at 02:45 (UTC-8:00)	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by refset** [comment]
Thanks for the report @jfhamlin - can you share an example of the transaction function(s) and the transaction being submitted to help repro? (feel free to DM / email jdt@juxt.pro)

**Comment by jfhamlin** [comment]
👍 provided in DM

**Comment by refset** [comment]
After some investigation it looks like a regression was introduced here: https://github.com/xtdb/xtdb/commit/e262c1c7e5bfb178fcdc6cbcb316f2fb934b08bd#diff-5ebf0beaabf11c6994497ae4d365957ac4379ddabdd06f6c22a7e2076f57d67eR158-R162

The Kafka module (and other document store implementations) assume that submit-docs takes a seq of MapEntries, so passing a seq of vectors is problematic. cc @wotbrew 

We'll get this fixed and released soon @jfhamlin - thanks for bringing it to our attention.

**Comment by jfhamlin** [comment]
If it's helpful, I suspect that I'm seeing this specifically when a transaction is aborted because a `:xtdb.api/match` op is failing in a transaction that also includes a transaction function. I can't say this with complete certainty because my iteration rate on the repro is quite low, but that appears to be the trigger.
