### ISSUE TITLE
No method in multimethod 'type->metadata-writer' for dispatch value: :set

### ISSUE THREAD

**Issue by onetom** [xtdb/crux#3067]
I've started following along with the https://github.com/xtdb/sakila-playground examples in https://www.youtube.com/watch?v=xB-hIpQxweI&t=29s .
Then I've left my REPL running for a few days and why I got back I've seen this error dumped into my CIDER REPL twice:

```
17:27:36 | INFO  xtdb.stagnant-log-flusher | last chunk tx-id null, flushing any pending writes
17:27:36 | ERROR xtdb.util | Uncaught exception:
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :set
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at clojure.core$deref_future.invokeStatic(core.clj:2317)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at xtdb.indexer.live_index.LiveIndex.finishChunk(live_index.clj:307)
	at xtdb.indexer.Indexer.finish_chunk_BANG_(indexer.clj:716)
	at xtdb.indexer.Indexer.forceFlush(indexer.clj:667)
	at xtdb.log.watcher$watch_log_BANG_$reify__25891.acceptRecord(watcher.clj:61)
	at xtdb.log$tx_handler$fn__23546.invoke(log.clj:35)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log.NotifyingSubscriberHandler$fn__23579.invoke(log.clj:91)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :set
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at xtdb.metadata$__GT_page_meta_wtr$__GT_nested_meta_writer$reify__15277.apply(metadata.clj:239)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at xtdb.metadata$__GT_page_meta_wtr$__GT_nested_meta_writer__15275.invoke(metadata.clj:235)
	at xtdb.metadata$__GT_page_meta_wtr$write_col_meta_BANG___15281$fn__15282.invoke(metadata.clj:246)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at xtdb.metadata$__GT_page_meta_wtr$write_col_meta_BANG___15281.invoke(metadata.clj:245)
	at xtdb.metadata$$reify__15293.writeMetadata(metadata.clj:272)
	at xtdb.trie$open_trie_writer$reify__15398.writeLeaf(trie.clj:124)
	at xtdb.trie$write_live_trie_node$write_node_BANG___15416.invoke(trie.clj:190)
	at xtdb.trie$write_live_trie_node.invokeStatic(trie.clj:192)
	at xtdb.trie$write_live_trie_node.invoke(trie.clj:169)
	at xtdb.trie$write_live_trie_BANG_$fn__15437.invoke(trie.clj:203)
	at xtdb.trie$write_live_trie_BANG_.invokeStatic(trie.clj:197)
	at xtdb.trie$write_live_trie_BANG_.invoke(trie.clj:194)
	at xtdb.indexer.live_index.LiveTable$fn__15634.invoke(live_index.clj:183)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
17:27:45 | INFO  xtdb.stagnant-log-flusher | last chunk tx-id null, flushing any pending writes
17:27:45 | ERROR xtdb.util | Uncaught exception:
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :set
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at clojure.core$deref_future.invokeStatic(core.clj:2317)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at xtdb.indexer.live_index.LiveIndex.finishChunk(live_index.clj:307)
	at xtdb.indexer.Indexer.finish_chunk_BANG_(indexer.clj:716)
	at xtdb.indexer.Indexer.forceFlush(indexer.clj:667)
	at xtdb.log.watcher$watch_log_BANG_$reify__25891.acceptRecord(watcher.clj:61)
	at xtdb.log$tx_handler$fn__23546.invoke(log.clj:35)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log.NotifyingSubscriberHandler$fn__23579.invoke(log.clj:91)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :set
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at xtdb.metadata$__GT_page_meta_wtr$__GT_nested_meta_writer$reify__15277.apply(metadata.clj:239)
<the rest of the stack trace is the same as the previous exception>
```

**Comment by jarohen** [comment]
Cheers @onetom - this should be a quick one to get fixed 🙏

**Comment by jarohen** [comment]
Hey @onetom - we'll get a snapshot out with this fix shortly :slightly_smiling_face:
