### ISSUE TITLE
String in temporal expression causes runtime CCE

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3095]
EDIT: minimal repro `SELECT DATE '2000-01-01' < '2010-01-01'`

```sql
SELECT r.xt$id FROM rental r WHERE r.xt$valid_from <= ?
```
Given `"asdf"` as the parameter:

```
java.lang.ClassCastException: class java.nio.DirectByteBuffer cannot be cast to class java.lang.Number (java.nio.DirectByteBuffer and java.lang.Number are in module java.base of loader 'bootstrap')
	at clojure.lang.Util.compare(Util.java:152)
	at clojure.core$eval41591$fn__41592.invoke(NO_SOURCE_FILE:0)
	at xtdb.expression$$reify__16862.project(expression.clj:1533)
	at xtdb.expression$$reify__16871.select(expression.clj:1541)
	at xtdb.operator.scan.TrieCursor$fn__20642$fn__20657.invoke(scan.clj:269)
	at xtdb.operator.scan.TrieCursor$fn__20642.invoke(scan.clj:265)
	at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:228)
	at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:112)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at xtdb.operator.join$build_phase.invokeStatic(join.clj:166)
	at xtdb.operator.join$build_phase.invoke(join.clj:165)
	at xtdb.operator.join.JoinCursor.tryAdvance(join.clj:333)
	at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:112)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at xtdb.operator.group_by.GroupByCursor$fn__21684.invoke(group_by.clj:584)
	at xtdb.operator.group_by.GroupByCursor.tryAdvance(group_by.clj:583)
	at xtdb.operator.set.DistinctCursor.tryAdvance(set.clj:176)
	at xtdb.operator.order_by.OrderByCursor.tryAdvance(order_by.clj:249)
	at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at xtdb.query$wrap_cursor$reify__28685.tryAdvance(query.clj:68)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at xtdb.api$q_AMPERSAND_$reify__4359.apply(api.clj:106)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
	at xtdb.api$q_AMPERSAND_.invokeStatic(api.clj:102)
	at xtdb.api$q_AMPERSAND_.invoke(api.clj:50)
	at xtdb.api$q.invokeStatic(api.clj:157)
	at xtdb.api$q.invoke(api.clj:109)
```

**Comment by refset** [comment]
Possibly a different card (but similar class of error):
```sql
SELECT film.replacement_cost, SUM(film.rental_rate) from film GROUP BY film.replacement_cost HAVING film.replacement_cost > 'y'
```
```
1. Unhandled java.lang.ClassCastException
   class java.nio.HeapByteBuffer cannot be cast to class java.lang.Number
   (java.nio.HeapByteBuffer and java.lang.Number are in module java.base of
   loader 'bootstrap')

                 Util.java:  152  clojure.lang.Util/compare
                      REPL:  112  xtdb.demo.jdt-resources/eval39719/fn
            expression.clj: 1533  xtdb.expression//reify
            expression.clj: 1541  xtdb.expression//reify
                  scan.clj:  269  xtdb.operator.scan.TrieCursor/fn/fn
                  scan.clj:  265  xtdb.operator.scan.TrieCursor/fn
                  scan.clj:  228  xtdb.operator.scan.TrieCursor/tryAdvance
                rename.clj:   31  xtdb.operator.rename.RenameCursor/tryAdvance
          Spliterator.java:  332  java.util.Spliterator/forEachRemaining
              group_by.clj:  584  xtdb.operator.group-by.GroupByCursor/fn
              group_by.clj:  583  xtdb.operator.group-by.GroupByCursor/tryAdvance
                rename.clj:   31  xtdb.operator.rename.RenameCursor/tryAdvance
                 query.clj:   68  xtdb.query/wrap-cursor/reify
          Spliterator.java:  332  java.util.Spliterator/forEachRemaining
     AbstractPipeline.java:  509  java.util.stream.AbstractPipeline/copyInto
     AbstractPipeline.java:  499  java.util.stream.AbstractPipeline/wrapAndCopyInto
     AbstractPipeline.java:  575  java.util.stream.AbstractPipeline/evaluate
     AbstractPipeline.java:  260  java.util.stream.AbstractPipeline/evaluateToArrayNode
    ReferencePipeline.java:  616  java.util.stream.ReferencePipeline/toArray
    ReferencePipeline.java:  622  java.util.stream.ReferencePipeline/toArray
    ReferencePipeline.java:  627  java.util.stream.ReferencePipeline/toList
                   api.clj:  106  xtdb.api/q&/reify
    CompletableFuture.java:  684  java.util.concurrent.CompletableFuture/uniApplyNow
    CompletableFuture.java:  662  java.util.concurrent.CompletableFuture/uniApplyStage
    CompletableFuture.java: 2200  java.util.concurrent.CompletableFuture/thenApply
                   api.clj:  102  xtdb.api/q&
                   api.clj:   50  xtdb.api/q&
                   api.clj:   94  xtdb.api/q&
                   api.clj:   50  xtdb.api/q&
                   api.clj:  153  xtdb.api/q
                   api.clj:  109  xtdb.api/q
```
