### ISSUE TITLE
50% request timeout rate through NodeJS

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3143]
* setup as per #3142 
* about 50% of requests time out, only error I get on the Docker console:
  ```
  WARN  o.e.j.util.thread.QueuedThreadPool | Job failed
  java.lang.IllegalStateException: COMPLETED
  	at org.eclipse.jetty.server.HttpChannelState.sendError(HttpChannelState.java:911)
  	at org.eclipse.jetty.server.HttpChannelState.nextAction(HttpChannelState.java:493)
  	at org.eclipse.jetty.server.HttpChannelState.unhandle(HttpChannelState.java:418)
  	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:650)
  	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:461)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  ```
* can't repro through cURL (`curl http://localhost:3000/query -XPOST -d '{"query": {"from": "visits"}, "queryOpts": {}}' -i -H 'content-type: application/json'`)

**Comment by FiV0** [comment]
Can't repro anymore. I suspect because of similar reasons to #3142. Ofcourse haven't tried with docker as we need to push a new image for that.
