### ISSUE TITLE
Clarify Java/Kotlin Driver SQL parameter handling

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3162]
Currently, supplying positional args to a SQL query in Java requires passing an args map using numbers as strings with a `_` prefix:

```java
xtdb.openQuery(sql, new QueryOptions(Collections.singletonMap("_0", 1),
                                     null,
                                     null,
                                     null,
                                     null,
                                     false,
                                     false,
                                     null))
```

For reference, this is what the error message looks if you don't supply the correct args key (over HTTP):
```
java.lang.RuntimeException: IllegalArgumentException(key=:xtdb.expression/unknown-symbol, message=Unknown symbol: '?_0', data={:symbol ?_0}, cause=null)
	at xtdb.api.IXtdbKt.await(IXtdb.kt:17)
	at xtdb.api.IXtdbKt.access$await(IXtdb.kt:1)
	at xtdb.api.IXtdb.openQuery(IXtdb.kt:81)
	at xtdb.api.IXtdb.openQuery$default(IXtdb.kt:81)
	at xtdb.api.IXtdb.openQuery(IXtdb.kt)
	at MySample.main(MySample.java:15)
	at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0(ExecJavaMojo.java:283)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: IllegalArgumentException(key=:xtdb.expression/unknown-symbol, message=Unknown symbol: '?_0', data={:symbol ?_0}, cause=null)
	at xtdb.serde$iae_reader.invokeStatic(serde.clj:205)
	at xtdb.serde$iae_reader.invoke(serde.clj:205)
	at cognitect.transit$read_handler$reify__231.fromRep(transit.clj:181)
	at com.cognitect.transit.impl.JsonParser.parseArray(JsonParser.java:143)
	at com.cognitect.transit.impl.JsonParser.parseVal(JsonParser.java:56)
	at com.cognitect.transit.impl.JsonParser.parse(JsonParser.java:46)
	at com.cognitect.transit.impl.ReaderFactory$ReaderImpl.read(ReaderFactory.java:112)
	at cognitect.transit$read.invokeStatic(transit.clj:323)
	at cognitect.transit$read.invoke(transit.clj:319)
	at xtdb.client.impl$eval3553$fn__3555.invoke(impl.clj:74)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at juxt.clojars_mirrors.hato.v0v8v2.hato.middleware$output_coercion_response.invokeStatic(middleware.clj:260)
	at juxt.clojars_mirrors.hato.v0v8v2.hato.middleware$output_coercion_response.invoke(middleware.clj:257)
	at juxt.clojars_mirrors.hato.v0v8v2.hato.middleware$wrap_output_coercion$fn__595$fn__596.invoke(middleware.clj:274)
	at juxt.clojars_mirrors.hato.v0v8v2.hato.middleware$wrap_decompression$fn__759$fn__760.invoke(middleware.clj:641)
	at juxt.clojars_mirrors.hato.v0v8v2.hato.middleware$wrap_request_timing$fn__725$fn__726.invoke(middleware.clj:571)
	at juxt.clojars_mirrors.hato.v0v8v2.hato.client$request_STAR_$reify__868.apply(client.clj:308)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

This is not currently clear from reading the kdocs alone.

Note that the JSON API also currently requires a map for SQL args, so this may be at least partially blocked until that is resolved (unless we keep transit around for longer).

**Comment by jarohen** [comment]
@refset: this is what the query options builder is for:

```java
var argsList = List.of("hello", "world");

try (var res = xtdb.openQuery(
       "SELECT * FROM foo ...", 
       queryOpts().args(argsList).build())) {
    System.out.println(res.toList());
}

// equivalent to

var argsMap = Map.of("_0", "hello", "_1", "world");
try (var res = xtdb.openQuery(
       "SELECT * FROM foo ...", 
       queryOpts().args(argsMap).build())) {

    System.out.println(res.toList());
}

```

**Comment by refset** [comment]
Ahh that works perfectly, thank you :pray:
