### ISSUE TITLE
Handling query parameters via JSON

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3167]
Parameters are not currently handled correctly via JSON (definitely for SQL, probably for XTQL also).

The cause is roughly: clojure.spec and the core fns expecting persistent data structures but the serde returns basic Java data structures.

Additionally, the JSON is also expecting an indexed map currently which doesn't correspond well with SQL positional parameters - similar to the description in https://github.com/xtdb/xtdb/issues/3162 (about the Java/Kotlin driver requiring a map with keys like "_0" and "_1")

In principle something like this should work okay:
```
curl -X POST localhost:3000/query \
     -H "Content-Type: application/json" \
     -H "Accept: application/jsonl" \
     -d '{"query":{"sql":"SELECT LEAST(?,2), LEAST(3,4) FROM (VALUES (1)) x"}, "queryOpts":{"args":[{"@type":"integer","@value":1}]}}}' \
| jet --from json --to edn --pretty
```

But it produces opaque errors like:

```
{"@type" "xt:error",
 "@value" {"xtdb.error/message" "Malformed \"application/json\" request.",
           "xtdb.error/class" "xtdb.IllegalArgumentException",
           "xtdb.error/error-key" "malformed-request",
           "xtdb.error/data" {}}}
...

clojure.lang.ExceptionInfo: Malformed application/json request.
	at muuntaja.core$fail_on_request_decode_exception.invokeStatic(core.clj:132)
    ...
Caused by: clojure.lang.ExceptionInfo: Malformed application/json in :muuntaja/decode
	at muuntaja.core$on_exception.invokeStatic(core.clj:284)
	at muuntaja.core$on_exception.invoke(core.clj:267)
	at clojure.core$partial$fn__5908.invoke(core.clj:2643)
	at muuntaja.core$create_coder$decode__3324.invoke(core.clj:322)
	at muuntaja.core$create$_decode_request_body__3374.invoke(core.clj:422)
	... 44 common frames omitted
Caused by: java.io.IOException: mark/reset not supported
	at java.base/java.io.InputStream.reset(InputStream.java:733)
	at xtdb.JsonSerde.decode(JsonSerde.kt:240)
	at xtdb.server$json_query_decoder$reify__10351.decode(server.clj:218)
	at muuntaja.core$create_coder$decode__3324.invoke(core.clj:320)
	... 45 common frames omitted

...

{"@type" "xt:error",
 "@value" {"xtdb.error/message" "Malformed request: Request coercion failed: #reitit.coercion.CoercionError{:spec #Spec{:form (clojure.spec.alpha/keys :req-un [:xtdb.server/query] :opt-un [:xtdb.server/after-tx :xtdb.server/basis :xtdb.server/tx-timeout :xtdb.server/args :xtdb.server/default-all-valid-time? :xtdb.server/default-tz :xtdb.server/key-fn :xtdb.server/explain?]), :type :map, :leaf? false}, :problems {:clojure.spec.alpha/problems ({:path [:args :clojure.spec.alpha/pred], :pred clojure.core/coll?, :val {\"_0\" 1}, :via [:xtdb.server/query-body :xtdb.server/args], :in [:args]} {:path [:args :clojure.spec.alpha/nil], :pred nil?, :val {\"_0\" 1}, :via [:xtdb.server/query-body :xtdb.server/args], :in [:args]}), :clojure.spec.alpha/spec #Spec{:form (clojure.spec.alpha/keys :req-un [:xtdb.server/query] :opt-un [:xtdb.server/after-tx :xtdb.server/basis :xtdb.server/tx-timeout :xtdb.server/args :xtdb.server/default-all-valid-time? :xtdb.server/default-tz :xtdb.server/key-fn :xtdb.server/explain?]), :type :map, :leaf? false}, :clojure.spec.alpha/value {:args {\"_0\" 1}, :explain? false, :query \"SELECT LEAST(1,2), LEAST(3,4) FROM (VALUES (1)) x\", :default-all-valid-time? false}}}",
           "xtdb.error/class" "xtdb.IllegalArgumentException",
           "xtdb.error/error-key" "malformed-request",
           "xtdb.error/data" {"spec" "(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:xtdb.server/query] :opt-un [:xtdb.server/after-tx :xtdb.server/basis :xtdb.server/tx-timeout :xtdb.server/args :xtdb.server/default-all-valid-time? :xtdb.server/default-tz :xtdb.server/key-fn :xtdb.server/explain?]), :type :map, :leaf? false})",
                              "problems" [{"path" [{"@type" "xt:keyword",
                                                    "@value" "args"}
                                                   {"@type" "xt:keyword",
                                                    "@value" "clojure.spec.alpha/pred"}],
                                           "pred" "clojure.core/coll?",
                                           "val" {"_0" 1},
                                           "via" [{"@type" "xt:keyword",
                                                   "@value" "xtdb.server/query-body"}
                                                  {"@type" "xt:keyword",
                                                   "@value" "xtdb.server/args"}],
                                           "in" [{"@type" "xt:keyword",
                                                  "@value" "args"}]}
                                          {"path" [{"@type" "xt:keyword",
                                                    "@value" "args"}
                                                   {"@type" "xt:keyword",
                                                    "@value" "clojure.spec.alpha/nil"}],
                                           "pred" "nil?",
                                           "val" {"_0" 1},
                                           "via" [{"@type" "xt:keyword",
                                                   "@value" "xtdb.server/query-body"}
                                                  {"@type" "xt:keyword",
                                                   "@value" "xtdb.server/args"}],
                                           "in" [{"@type" "xt:keyword",
                                                  "@value" "args"}]}],
                              "type" {"@type" "xt:keyword",
                                      "@value" "reitit.coercion/request-coercion"},
                              "coercion" {"@type" "xt:keyword",
                                          "@value" "spec"},
                              "value" {"args" {"_0" 1},
                                       "default-all-valid-time?" false,
                                       "explain?" false,
                                       "query" "SELECT LEAST(1,2), LEAST(3,4) FROM (VALUES (1)) x"},
                              "in" [{"@type" "xt:keyword",
                                     "@value" "request"}
                                    {"@type" "xt:keyword",
                                     "@value" "body-params"}]}}}
```

**Comment by FiV0** [comment]
Fixed in https://github.com/xtdb/xtdb/commit/a6bf8c5153f43226c7fc946864744f8c55038b29 and https://github.com/xtdb/xtdb/commit/244cc7c4c5951f2168c3eabd0f2fa216998cebc8
