### ISSUE TITLE
Intermittent failure in compactor

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3240]
We sometimes seem to be reading a empty trie when compacting. This could be because the vectors have not been properly loaded or because we have closed things too early.
```
Caused by: java.lang.IndexOutOfBoundsException: index: -4, length: 4 (expected: range(0, 0))
	at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:319)
	at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:306)
	at org.apache.arrow.memory.ArrowBuf.getInt(ArrowBuf.java:425)
	at org.apache.arrow.vector.complex.DenseUnionVector.getOffset(DenseUnionVector.java:902)
	at xtdb.trie.ArrowHashTrie.forIndex(ArrowHashTrie.kt:75)
	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:86)
	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:13)
	at xtdb.trie.HashTrieKt.toMergePlan(HashTrie.kt:88)
	at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:59)
	at xtdb.compactor$merge_segments_into.invoke(compactor.clj:53)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__28982$fn__28983$fn__28992$fn__28993.invoke(compactor.clj:128)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__28982$fn__28983$fn__28992.invoke(compactor.clj:126)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__28982$fn__28983.invoke(compactor.clj:126)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__28982.invoke(compactor.clj:115)
	at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:115)
	at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:110)
	at xtdb.compactor$fn$reify__29098.compactAll(compactor.clj:250)
	at xtdb.compactor$compact_all_BANG_.invokeStatic(compactor.clj:264)
	at xtdb.compactor$compact_all_BANG_.invoke(compactor.clj:262)
	at xtdb.compactor_test$fn__29415$fn__29416.invoke(compactor_test.clj:318)
	at xtdb.compactor_test$fn__29415.invokeStatic(compactor_test.clj:291)
	at xtdb.compactor_test$fn__29415.invoke(compactor_test.clj:285)
	at dev.clojurephant.jovial.engine.clojure_test$eval886$fn__889.invoke(clojure_test.clj:34)
	... 65 more
	Suppressed: clojure.lang.ExceptionInfo: Error on key :xtdb/buffer-pool when running system {:reason :juxt.clojars-mirrors.integrant.core/run-threw-exception, :system {:xtdb/default-tz #time/zone "Z", :xtdb/log #object[xtdb.log.local_directory_log.LocalDirectoryLog 0x245f8895 ...}
		at app//juxt.clojars_mirrors.integrant.core$run_exception.invokeStatic(core.cljc:242)
		at app//juxt.clojars_mirrors.integrant.core$run_exception.invoke(core.cljc:241)
		at app//juxt.clojars_mirrors.integrant.core$try_run_action.invokeStatic(core.cljc:256)
		at app//juxt.clojars_mirrors.integrant.core$try_run_action.invoke(core.cljc:252)
		at app//juxt.clojars_mirrors.integrant.core$run_loop.invokeStatic(core.cljc:262)
		at app//juxt.clojars_mirrors.integrant.core$run_loop.invoke(core.cljc:258)
		at app//juxt.clojars_mirrors.integrant.core$reverse_run_BANG_.invokeStatic(core.cljc:282)
		at app//juxt.clojars_mirrors.integrant.core$reverse_run_BANG_.invoke(core.cljc:276)
		at app//juxt.clojars_mirrors.integrant.core$halt_BANG_.invokeStatic(core.cljc:449)
		at app//juxt.clojars_mirrors.integrant.core$halt_BANG_.invoke(core.cljc:443)
		at app//juxt.clojars_mirrors.integrant.core$halt_BANG_.invokeStatic(core.cljc:446)
		at app//juxt.clojars_mirrors.integrant.core$halt_BANG_.invoke(core.cljc:443)
		at app//xtdb.node.impl$open_node$fn__26243.invoke(impl.clj:191)
		at app//xtdb.node.impl.Node.close(impl.clj:108)
		at app//xtdb.util$close.invokeStatic(util.clj:43)
		at app//xtdb.util$close.invoke(util.clj:40)
		at app//xtdb.compactor_test$fn__29415$fn__29416$fn__29467.invoke(compactor_test.clj:291)
		at app//xtdb.compactor_test$fn__29415$fn__29416.invoke(compactor_test.clj:291)
		... 68 more
	Caused by: java.lang.IllegalStateException: RefCnt has gone negative
		at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:458)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:130)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
		at org.apache.arrow.memory.ArrowBuf.close(ArrowBuf.java:1044)
		at xtdb.util$close.invokeStatic(util.clj:43)
		at xtdb.util$close.invoke(util.clj:40)
		at clojure.core$run_BANG_$fn__8908.invoke(core.clj:7836)
		at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
		at clojure.core.protocols$fn__8246.invokeStatic(protocols.clj:75)
		at clojure.core.protocols$fn__8246.invoke(protocols.clj:75)
		at clojure.core.protocols$fn__8194$G__8189__8207.invoke(protocols.clj:13)
		at clojure.core$reduce.invokeStatic(core.clj:6895)
		at clojure.core$run_BANG_.invokeStatic(core.clj:7831)
		at clojure.core$run_BANG_.invoke(core.clj:7831)
		at xtdb.buffer_pool$free_memory.invokeStatic(buffer_pool.clj:41)
		at xtdb.buffer_pool$free_memory.invoke(buffer_pool.clj:39)
		at xtdb.buffer_pool.LocalBufferPool.close(buffer_pool.clj:235)
		at xtdb.util$close.invokeStatic(util.clj:43)
		at xtdb.util$close.invoke(util.clj:40)
		at xtdb.buffer_pool$fn__9584.invokeStatic(buffer_pool.clj:480)
		at xtdb.buffer_pool$fn__9584.invoke(buffer_pool.clj:479)
		at clojure.lang.MultiFn.invoke(MultiFn.java:234)
		at juxt.clojars_mirrors.integrant.core$try_run_action.invokeStatic(core.cljc:254)
		... 83 more
```

**Comment by FiV0** [comment]
I suspect something similar to https://github.com/xtdb/xtdb/issues/3298 is happening in the compactor
```
10:36:45.194 [xtdb.compactor-7] ERROR xtdb.compactor - Error running compaction job.
java.lang.NullPointerException: Cannot invoke "org.apache.arrow.memory.ArrowBuf.getByte(long)" because the return value of "org.apache.arrow.memory.util.ArrowBufPointer.getBuf()" is null
	at xtdb.trie.HashTrie$Companion.bucketFor(HashTrie.kt:59)
	at xtdb.trie.HashTrie$Companion.compareToPath(HashTrie.kt:66)
	at xtdb.trie.EventRowPointer.<init>(EventRowPointer.kt:24)
	at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:83)
	at xtdb.compactor$merge_segments_into.invoke(compactor.clj:56)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__41151$fn__41152$fn__41161$fn__41162.invoke(compactor.clj:134)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__41151$fn__41152$fn__41161.invoke(compactor.clj:132)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__41151$fn__41152.invoke(compactor.clj:132)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__41151.invoke(compactor.clj:121)
	at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:121)
	at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:116)
	at xtdb.compactor$eval41266$fn__41268$compactor_loop__41302.invoke(compactor.clj:280)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

**Comment by FiV0** [comment]
Should be fixed in https://github.com/xtdb/xtdb/commit/c189f9bd0219147cd310cfbf666195ce2794e28a. Not test written.
