### ISSUE TITLE
Invalid txOps should not halt ingestion

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3246]
e.g. `select * from wait_this_isnt_a_tx_op`

```bash
➜  xtdb ✗ sql="\                                  
INSERT INTO people (xt\$id, name, info) \
VALUES (6, 'fred', {'height': DATE '2000-01-01', \
                    'age': 29, \
                    'likes': ['apples']})"; \
curl --json "{\"txOps\": [{\"sql\": \"${sql}\"}]}" localhost:3000/tx
{"txId":0,"systemTime":"2024-03-15T18:21:39.824547Z"}%                                                           

➜  xtdb ✗ sql="SELECT people.xt\$id, people.name FROM people"; \
curl --json "{\"query\": {\"sql\": \"${sql}\"},\
              \"queryOpts\": {}}" localhost:3000/query
[{"name":"fred","xt/id":6}]%                                                             

➜  xtdb ✗ sql="\                                                
select * from wait_this_isnt_a_tx_op"; \       
curl --json "{\"txOps\": [{\"sql\": \"${sql}\"}]}" localhost:3000/tx
{"txId":1413,"systemTime":"2024-03-15T18:22:28.931564Z"}%                                

➜  xtdb ✗ sql="SELECT people.xt\$id, people.name FROM people"; \
curl --json "{\"query\": {\"sql\": \"${sql}\"},\
              \"queryOpts\": {}}" localhost:3000/query
{"@type":"xt:error","@value":{"xtdb.error/message":"Ingestion stopped: sql query","xtdb.error/class":"clojure.lang.ExceptionInfo","xtdb.error/data":{"xtdb.error/error-type":{"@type":"xt:keyword","@value":"unknown-runtime-error"},"class":"clojure.lang.ExceptionInfo","stringified":"clojure.lang.ExceptionInfo: Ingestion stopped: sql query {}"}}}%
```

Log:
```
Starting XTDB 2.x (pre-alpha) @ "dev-SNAPSHOT" @ 482a652 ...
18:21:10 | DEBUG xtdb.metrics | Metrics server started on port:  8080
18:21:10 | INFO  xtdb.server | HTTP server started on port:  3000
18:21:10 | INFO  xtdb.pgwire | PGWire server started on port: 5432
18:21:10 | INFO  xtdb.pgwire | PGWire server listening on 5432
18:21:10 | INFO  xtdb.cli | Node started
18:22:29 | ERROR xtdb.indexer | error in indexer
java.lang.UnsupportedOperationException: sql query
	at xtdb.indexer$$reify__35027.indexOp(indexer.clj:399)
	at xtdb.indexer.Indexer$fn__35090$index_tx_ops__35093$fn__35106.invoke(indexer.clj:631)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.indexer.Indexer$fn__35090$index_tx_ops__35093.invoke(indexer.clj:628)
	at xtdb.indexer.Indexer$fn__35090$fn__35114.invoke(indexer.clj:642)
	at xtdb.indexer.Indexer$fn__35090.invoke(indexer.clj:641)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:603)
	at xtdb.log.watcher$watch_log_BANG_$reify__35327.acceptRecord(watcher.clj:53)
	at xtdb.log$tx_handler$fn__16495.invoke(log.clj:38)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log$handle_polling_subscription$fn__16501.invoke(log.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:840)
18:22:29 | ERROR xtdb.util | Uncaught exception:
java.lang.UnsupportedOperationException: sql query
	at xtdb.indexer$$reify__35027.indexOp(indexer.clj:399)
	at xtdb.indexer.Indexer$fn__35090$index_tx_ops__35093$fn__35106.invoke(indexer.clj:631)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.indexer.Indexer$fn__35090$index_tx_ops__35093.invoke(indexer.clj:628)
	at xtdb.indexer.Indexer$fn__35090$fn__35114.invoke(indexer.clj:642)
	at xtdb.indexer.Indexer$fn__35090.invoke(indexer.clj:641)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:603)
	at xtdb.log.watcher$watch_log_BANG_$reify__35327.acceptRecord(watcher.clj:53)
	at xtdb.log$tx_handler$fn__16495.invoke(log.clj:38)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log$handle_polling_subscription$fn__16501.invoke(log.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:840)
18:22:33 | DEBUG xtdb.server | response error (class clojure.lang.ExceptionInfo): 'Ingestion stopped: sql query'
clojure.lang.ExceptionInfo: Ingestion stopped: sql query
	at xtdb.await$__GT_ingester_ex.invokeStatic(await.clj:17)
	at xtdb.await$__GT_ingester_ex.invoke(await.clj:16)
	at xtdb.await$await_tx_async$fn__30360.invoke(await.clj:30)
	at xtdb.await$await_tx_async.invokeStatic(await.clj:25)
	at xtdb.await$await_tx_async.invoke(await.clj:21)
	at xtdb.indexer.Indexer.awaitTxAsync(indexer.clj:687)
	at xtdb.node.impl.Node.openQueryAsync(impl.clj:66)
	at xtdb.api$eval3423$fn__3425.invoke(api.clj:182)
	at xtdb.protocols$eval865$fn__866$G__856__875.invoke(protocols.clj:4)
	at xtdb.server$eval23403$fn__23404$fn__23406.invoke(server.clj:266)
	at sieppari.interceptor$eval22911$fn__22912$fn__22913.invoke(interceptor.cljc:33)
	at sieppari.core$_try.invokeStatic(core.cljc:20)
	at sieppari.core$_try.invoke(core.cljc:17)
	at sieppari.core$enter.invokeStatic(core.cljc:62)
	at sieppari.core$enter.invoke(core.cljc:49)
	at sieppari.core$execute$fn__23117.invoke(core.cljc:125)
	at sieppari.core$execute.invokeStatic(core.cljc:123)
	at sieppari.core$execute.invoke(core.cljc:117)
	at reitit.interceptor.sieppari$reify__23126.execute(sieppari.clj:18)
	at reitit.http$ring_handler$fn__22184.invoke(http.cljc:165)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at ring.adapter.jetty9.handlers.async$_doHandle.invokeStatic(async.clj:34)
	at ring.adapter.jetty9.handlers.async$_doHandle.invoke(async.clj:22)
	at ring.adapter.jetty9.handlers.AsyncProxyHandler.doHandle(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at ring.adapter.jetty9.handlers.AsyncProxyHandler.doScope(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException: sql query
	at xtdb.indexer$$reify__35027.indexOp(indexer.clj:399)
	at xtdb.indexer.Indexer$fn__35090$index_tx_ops__35093$fn__35106.invoke(indexer.clj:631)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.indexer.Indexer$fn__35090$index_tx_ops__35093.invoke(indexer.clj:628)
	at xtdb.indexer.Indexer$fn__35090$fn__35114.invoke(indexer.clj:642)
	at xtdb.indexer.Indexer$fn__35090.invoke(indexer.clj:641)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:603)
	at xtdb.log.watcher$watch_log_BANG_$reify__35327.acceptRecord(watcher.clj:53)
	at xtdb.log$tx_handler$fn__16495.invoke(log.clj:38)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log$handle_polling_subscription$fn__16501.invoke(log.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 common frames omitted
```

**Comment by jarohen** [comment]
see #3265
