### ISSUE TITLE
Columns names should conform to a regex of `[A-Za-z0-9_$]`, and otherwise throw

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3273]
e.g. currently, semi-colons in top-level column names work okay:
```
xtdb-> insert into foo (xt$id, "fo; o") values (1, {'foo':4});

| systemTime                     | txId  |
|--------------------------------|-------|
| '2024-04-02T15:42:35.031074Z'  | 5236  |

xtdb-> select * from foo;

| xt$id | fo; o       |
|-------|-------------|
| 1     | {'foo': 4}  |
```

...but anything nested causes stopped ingestion:
```
insert into foo (xt$id, foo) values (1, {'fo;o':2});
```
...
```
clojure.lang.Compiler$CompilerException: Syntax error compiling fn* at (0:0).
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7132)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5479)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4041)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.eval(Compiler.java:7191)
	at clojure.lang.Compiler.eval(Compiler.java:7149)
	at clojure.core$eval.invokeStatic(core.clj:3215)
	at clojure.core$eval.invoke(core.clj:3211)
	at xtdb.expression$fn__7800$fn__7803.invoke(expression.clj:1515)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at xtdb.expression$$reify__7816.project(expression.clj:1572)
	at xtdb.operator.table$emit_rows_table$fn__34536.invoke(table.clj:107)
	at xtdb.operator.table$emit_rows_table$fn__34601$fn__34602.invoke(table.clj:118)
	at xtdb.operator.table$__GT_out_rel$fn__34471.invoke(table.clj:58)
	at xtdb.operator.table$__GT_out_rel.invokeStatic(table.clj:54)
	at xtdb.operator.table$__GT_out_rel.invoke(table.clj:47)
	at xtdb.operator.table$emit_rows_table$fn__34601.invoke(table.clj:116)
	at xtdb.operator.table$eval34679$fn__34681$fn__34689.invoke(table.clj:163)
	at xtdb.logical_plan$unary_expr$fn__14288.invoke(logical_plan.clj:120)
	at xtdb.query$prepare_ra$reify$reify__35816.openCursor(query.clj:138)
	at xtdb.indexer$query_indexer$eval_query__35994.invoke(indexer.clj:369)
	at xtdb.indexer$wrap_sql_args$fn__36001.invoke(indexer.clj:392)
	at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:378)
	at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
	at xtdb.indexer$$reify__36006.indexOp(indexer.clj:376)
	at xtdb.indexer.Indexer$fn__36069$index_tx_ops__36072$fn__36085.invoke(indexer.clj:608)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.indexer.Indexer$fn__36069$index_tx_ops__36072.invoke(indexer.clj:605)
	at xtdb.indexer.Indexer$fn__36069$fn__36093.invoke(indexer.clj:619)
	at xtdb.indexer.Indexer$fn__36069.invoke(indexer.clj:618)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:580)
	at xtdb.log.watcher$watch_log_BANG_$reify__36306.acceptRecord(watcher.clj:53)
	at xtdb.log$tx_handler$fn__17425.invoke(log.clj:38)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log$handle_polling_subscription$fn__17431.invoke(log.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassFormatError: Illegal field name "fo;o_box36630" in class clojure/core$eval36632$fn__36633
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:879)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.lang.Compiler$ObjExpr.getCompiledClass(Compiler.java:4998)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4128)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	... 48 common frames omitted
15:39:56 | ERROR xtdb.util | Uncaught exception:
clojure.lang.Compiler$CompilerException: Syntax error compiling fn* at (0:0).
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7132)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5479)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4041)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.eval(Compiler.java:7191)
	at clojure.lang.Compiler.eval(Compiler.java:7149)
	at clojure.core$eval.invokeStatic(core.clj:3215)
	at clojure.core$eval.invoke(core.clj:3211)
	at xtdb.expression$fn__7800$fn__7803.invoke(expression.clj:1515)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at xtdb.expression$$reify__7816.project(expression.clj:1572)
	at xtdb.operator.table$emit_rows_table$fn__34536.invoke(table.clj:107)
	at xtdb.operator.table$emit_rows_table$fn__34601$fn__34602.invoke(table.clj:118)
	at xtdb.operator.table$__GT_out_rel$fn__34471.invoke(table.clj:58)
	at xtdb.operator.table$__GT_out_rel.invokeStatic(table.clj:54)
	at xtdb.operator.table$__GT_out_rel.invoke(table.clj:47)
	at xtdb.operator.table$emit_rows_table$fn__34601.invoke(table.clj:116)
	at xtdb.operator.table$eval34679$fn__34681$fn__34689.invoke(table.clj:163)
	at xtdb.logical_plan$unary_expr$fn__14288.invoke(logical_plan.clj:120)
	at xtdb.query$prepare_ra$reify$reify__35816.openCursor(query.clj:138)
	at xtdb.indexer$query_indexer$eval_query__35994.invoke(indexer.clj:369)
	at xtdb.indexer$wrap_sql_args$fn__36001.invoke(indexer.clj:392)
	at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:378)
	at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
	at xtdb.indexer$$reify__36006.indexOp(indexer.clj:376)
	at xtdb.indexer.Indexer$fn__36069$index_tx_ops__36072$fn__36085.invoke(indexer.clj:608)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.indexer.Indexer$fn__36069$index_tx_ops__36072.invoke(indexer.clj:605)
	at xtdb.indexer.Indexer$fn__36069$fn__36093.invoke(indexer.clj:619)
	at xtdb.indexer.Indexer$fn__36069.invoke(indexer.clj:618)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:580)
	at xtdb.log.watcher$watch_log_BANG_$reify__36306.acceptRecord(watcher.clj:53)
	at xtdb.log$tx_handler$fn__17425.invoke(log.clj:38)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log$handle_polling_subscription$fn__17431.invoke(log.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassFormatError: Illegal field name "fo;o_box36630" in class clojure/core$eval36632$fn__36633
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:879)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.lang.Compiler$ObjExpr.getCompiledClass(Compiler.java:4998)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4128)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	... 48 common frames omitted
15:39:58 | DEBUG xtdb.server | response error (class clojure.lang.ExceptionInfo): 'Ingestion stopped: Syntax error compiling fn* at (0:0).'
clojure.lang.ExceptionInfo: Ingestion stopped: Syntax error compiling fn* at (0:0).
	at xtdb.await$__GT_ingester_ex.invokeStatic(await.clj:17)
	at xtdb.await$__GT_ingester_ex.invoke(await.clj:16)
	at xtdb.await$await_tx_async$fn__31280.invoke(await.clj:30)
	at xtdb.await$await_tx_async.invokeStatic(await.clj:25)
	at xtdb.await$await_tx_async.invoke(await.clj:21)
	at xtdb.indexer.Indexer.awaitTxAsync(indexer.clj:664)
	at xtdb.node.impl.Node.openQueryAsync(impl.clj:66)
	at xtdb.api$eval3440$fn__3442.invoke(api.clj:182)
	at xtdb.protocols$eval865$fn__866$G__856__875.invoke(protocols.clj:4)
	at xtdb.server$eval24333$fn__24334$fn__24336.invoke(server.clj:270)
	at sieppari.interceptor$eval23841$fn__23842$fn__23843.invoke(interceptor.cljc:33)
	at sieppari.core$_try.invokeStatic(core.cljc:20)
	at sieppari.core$_try.invoke(core.cljc:17)
	at sieppari.core$enter.invokeStatic(core.cljc:62)
	at sieppari.core$enter.invoke(core.cljc:49)
	at sieppari.core$execute$fn__24047.invoke(core.cljc:125)
	at sieppari.core$execute.invokeStatic(core.cljc:123)
	at sieppari.core$execute.invoke(core.cljc:117)
	at reitit.interceptor.sieppari$reify__24056.execute(sieppari.clj:18)
	at reitit.http$ring_handler$fn__23114.invoke(http.cljc:165)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at ring.adapter.jetty9.handlers.async$_doHandle.invokeStatic(async.clj:34)
	at ring.adapter.jetty9.handlers.async$_doHandle.invoke(async.clj:22)
	at ring.adapter.jetty9.handlers.AsyncProxyHandler.doHandle(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at ring.adapter.jetty9.handlers.AsyncProxyHandler.doScope(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: clojure.lang.Compiler$CompilerException: Syntax error compiling fn* at (0:0).
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7132)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5479)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4041)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.eval(Compiler.java:7191)
	at clojure.lang.Compiler.eval(Compiler.java:7149)
	at clojure.core$eval.invokeStatic(core.clj:3215)
	at clojure.core$eval.invoke(core.clj:3211)
	at xtdb.expression$fn__7800$fn__7803.invoke(expression.clj:1515)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at xtdb.expression$$reify__7816.project(expression.clj:1572)
	at xtdb.operator.table$emit_rows_table$fn__34536.invoke(table.clj:107)
	at xtdb.operator.table$emit_rows_table$fn__34601$fn__34602.invoke(table.clj:118)
	at xtdb.operator.table$__GT_out_rel$fn__34471.invoke(table.clj:58)
	at xtdb.operator.table$__GT_out_rel.invokeStatic(table.clj:54)
	at xtdb.operator.table$__GT_out_rel.invoke(table.clj:47)
	at xtdb.operator.table$emit_rows_table$fn__34601.invoke(table.clj:116)
	at xtdb.operator.table$eval34679$fn__34681$fn__34689.invoke(table.clj:163)
	at xtdb.logical_plan$unary_expr$fn__14288.invoke(logical_plan.clj:120)
	at xtdb.query$prepare_ra$reify$reify__35816.openCursor(query.clj:138)
	at xtdb.indexer$query_indexer$eval_query__35994.invoke(indexer.clj:369)
	at xtdb.indexer$wrap_sql_args$fn__36001.invoke(indexer.clj:392)
	at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:378)
	at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
	at xtdb.indexer$$reify__36006.indexOp(indexer.clj:376)
	at xtdb.indexer.Indexer$fn__36069$index_tx_ops__36072$fn__36085.invoke(indexer.clj:608)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.indexer.Indexer$fn__36069$index_tx_ops__36072.invoke(indexer.clj:605)
	at xtdb.indexer.Indexer$fn__36069$fn__36093.invoke(indexer.clj:619)
	at xtdb.indexer.Indexer$fn__36069.invoke(indexer.clj:618)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:580)
	at xtdb.log.watcher$watch_log_BANG_$reify__36306.acceptRecord(watcher.clj:53)
	at xtdb.log$tx_handler$fn__17425.invoke(log.clj:38)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log$handle_polling_subscription$fn__17431.invoke(log.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 common frames omitted
Caused by: java.lang.ClassFormatError: Illegal field name "fo;o_box36630" in class clojure/core$eval36632$fn__36633
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:879)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.lang.Compiler$ObjExpr.getCompiledClass(Compiler.java:4998)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4128)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	... 48 common frames omitted
```

This may not be limited to `;`, other characters / escaping considerations should probably be validated also.

**Comment by refset** [comment]
Update: no longer stopping ingestion, but there's a silent failure when submitting to psql (_txs shows committed)

```
jdt=> insert into foo (xt$id, foo) values (1, {"fo;o":2});
INSERT 0 0
jdt=> select * from foo;
 _id |    bar    
-----+-----------
   1 | {"foo":4}
(1 row)

jdt=> select * from _txs;
 _id  | committed | error |            tx_time            
------+-----------+-------+-------------------------------
 5618 | t         |       | "2024-07-19T10:22:23.033885Z"
 2722 | t         |       | "2024-07-18T21:13:55.853920Z"
 4285 | t         |       | "2024-07-19T10:22:04.520113Z"
    0 | t         |       | "2024-07-18T21:13:39.735165Z"
 1341 | t         |       | "2024-07-18T21:13:49.959299Z"
(5 rows)


```
