### ISSUE TITLE
IAE in Auctionmark with `arrowUnsafeMemoryAccess`

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3280]
Not sure if the is related to my MultiVectorReader changes, but it's happening in the live-index. Also resulting in memory leaks.
```
java.lang.IllegalArgumentException: Invalid parameters startIndex: 0, length: 18194 for valueCount: 0
	at org.apache.arrow.util.Preconditions.checkArgument(Preconditions.java:413)
	at org.apache.arrow.vector.BaseVariableWidthVector.splitAndTransferTo(BaseVariableWidthVector.java:773)
	at org.apache.arrow.vector.VarCharVector$TransferImpl.splitAndTransfer(VarCharVector.java:353)
	at org.apache.arrow.vector.complex.NonNullableStructVector$StructTransferPair.splitAndTransfer(NonNullableStructVector.java:338)
	at org.apache.arrow.vector.complex.StructVector$NullableStructTransferPair.splitAndTransfer(StructVector.java:293)
	at org.apache.arrow.vector.complex.DenseUnionVector$TransferImpl.splitAndTransfer(DenseUnionVector.java:1192)
	at xtdb.util$slice_vec.invokeStatic(util.clj:353)
	at xtdb.util$slice_vec.invokePrim(util.clj)
	at xtdb.util$slice_vec.invokeStatic(util.clj:333)
	at xtdb.util$slice_vec.invokePrim(util.clj)
	at xtdb.util$slice_vec.invokeStatic(util.clj:332)
	at xtdb.util$slice_vec.invoke(util.clj:331)
	at xtdb.indexer.live_index$open_wm_live_rel.invokeStatic(live_index.clj:87)
	at xtdb.indexer.live_index$open_wm_live_rel.invoke(live_index.clj:81)
	at xtdb.indexer.live_index.LiveTable.openWatermark(live_index.clj:195)
	at xtdb.indexer.live_index.LiveIndex$open_live_idx_wm__29174.invoke(live_index.clj:329)
	at xtdb.indexer.live_index.LiveIndex.openWatermark(live_index.clj:355)
	at xtdb.indexer.Indexer.openWatermark(indexer.clj:657)
	at xtdb.operator.scan$tables_with_cols.invokeStatic(scan.clj:119)
	at xtdb.operator.scan$tables_with_cols.invoke(scan.clj:116)
	at xtdb.node.impl.Node$fn__42476.invoke(impl.clj:92)
	at xtdb.util$$reify__4265.apply(util.clj:291)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
	at xtdb.util$then_apply.invokeStatic(util.clj:296)
	at xtdb.util$then_apply.invoke(util.clj:293)
	at xtdb.node.impl.Node.openQueryAsync(impl.clj:90)
	at xtdb.api$eval13497$fn__13499.invoke(api.clj:188)
	at xtdb.protocols$eval1948$fn__1949$G__1939__1958.invoke(protocols.clj:4)
	at xtdb.api$q_AMPERSAND_.invokeStatic(api.clj:106)
	at xtdb.api$q_AMPERSAND_.invoke(api.clj:55)
	at xtdb.api$q.invokeStatic(api.clj:162)
	at xtdb.api$q.invoke(api.clj:114)
	at xtdb.bench.auctionmark$query_now.invokeStatic(auctionmark.clj:15)
	at xtdb.bench.auctionmark$query_now.invoke(auctionmark.clj:13)
	at xtdb.bench.auctionmark$proc_get_item.invokeStatic(auctionmark.clj:339)
	at xtdb.bench.auctionmark$proc_get_item.invoke(auctionmark.clj:330)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at xtdb.bench$wrap_in_catch$fn__41088.doInvoke(bench.clj:19)
	at clojure.lang.RestFn.invoke(RestFn.java:411)
	at xtdb.bench.measurement$wrap_transaction$instrumented_transaction__41291$fn__41292.invoke(measurement.clj:32)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.bench.measurement$wrap_transaction$instrumented_transaction__41291.invoke(measurement.clj:32)
	at xtdb.bench$compile_benchmark$compile_task__41200$run_pick_weighted__41210.invoke(bench.clj:264)
	at xtdb.bench$compile_benchmark$compile_task__41200$run_pool_thread_loop__41230.invoke(bench.clj:218)
	at xtdb.bench$compile_benchmark$compile_task__41200$start_thread__41232$fn__41233.invoke(bench.clj:227)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by FiV0** [comment]
I think another instance of https://github.com/apache/arrow/issues/30866 or some variation thereof.
