### ISSUE TITLE
`splitAndTransfer` (aka opening a watermark) while a buffer is being reallocated causes an error

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3315]
It seems to happen that opening a Watermark in on the live index throws, as the underlying vectors get either closed or realloacted.
```
14:16:27.517 [core2-benchmark-pool-16-thread-4] ERROR xtdb.bench - Error while executing xtdb.bench.auctionmark$proc_get_item@4daa4792
java.lang.IllegalArgumentException: Invalid parameters startIndex: 0, length: 17991 for valueCount: 0
	at org.apache.arrow.util.Preconditions.checkArgument(Preconditions.java:413)
	at org.apache.arrow.vector.BaseFixedWidthVector.splitAndTransferTo(BaseFixedWidthVector.java:635)
	at org.apache.arrow.vector.BigIntVector$TransferImpl.splitAndTransfer(BigIntVector.java:360)
	at org.apache.arrow.vector.complex.NonNullableStructVector$StructTransferPair.splitAndTransfer(NonNullableStructVector.java:338)
	at org.apache.arrow.vector.complex.StructVector$NullableStructTransferPair.splitAndTransfer(StructVector.java:293)
	at org.apache.arrow.vector.complex.DenseUnionVector$TransferImpl.splitAndTransfer(DenseUnionVector.java:1192)
	at xtdb.util$slice_vec.invokeStatic(util.clj:353)
	at xtdb.util$slice_vec.invokePrim(util.clj)
	at xtdb.util$slice_vec.invokeStatic(util.clj:333)
	at xtdb.util$slice_vec.invokePrim(util.clj)
	at xtdb.util$slice_vec.invokeStatic(util.clj:332)
	at xtdb.util$slice_vec.invoke(util.clj:331)
	at xtdb.indexer.live_index$open_wm_live_rel.invokeStatic(live_index.clj:87)
	at xtdb.indexer.live_index$open_wm_live_rel.invoke(live_index.clj:81)
	at xtdb.indexer.live_index.LiveTable.openWatermark(live_index.clj:195)
	at xtdb.indexer.live_index.LiveIndex$open_live_idx_wm__76777.invoke(live_index.clj:329)
	at xtdb.indexer.live_index.LiveIndex.openWatermark(live_index.clj:355)
	at xtdb.indexer.Indexer.openWatermark(indexer.clj:657)
	at xtdb.operator.scan$tables_with_cols.invokeStatic(scan.clj:119)
	at xtdb.operator.scan$tables_with_cols.invoke(scan.clj:116)
	at xtdb.node.impl.Node$fn__100267.invoke(impl.clj:92)
	at xtdb.util$$reify__62690.apply(util.clj:291)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by FiV0** [comment]
Different but probably related error:
```
16:26:29.628 [core2-benchmark-pool-24-thread-1] ERROR xtdb.bench - Error while executing xtdb.bench.auctionmark$proc_get_item@4daa4792
java.lang.IllegalStateException: watermark closed
	at xtdb.watermark.Watermark.retain(IWatermark.kt:28)
	at xtdb.indexer.live_index.LiveIndex$maybe_existing_wm__76771.invoke(live_index.clj:322)
	at xtdb.indexer.live_index.LiveIndex$fn__76797.invoke(live_index.clj:346)
	at xtdb.indexer.live_index.LiveIndex.openWatermark(live_index.clj:345)
	at xtdb.indexer.Indexer.openWatermark(indexer.clj:657)
	at xtdb.query$prepare_ra$reify__81681.bind(query.clj:114)
	at xtdb.query$open_query.invokeStatic(query.clj:216)
	at xtdb.query$open_query.invoke(query.clj:211)
	at xtdb.node.impl.Node$fn__100267.invoke(impl.clj:96)
	at xtdb.util$$reify__62690.apply(util.clj:291)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by FiV0** [comment]
Tried to reproduce this with only reading and writing, but no luck so far:
```clj
(ns arrow-read-write
  (:require [xtdb.vector.writer :as vw]
            [xtdb.util :as util])
  (:import (org.apache.arrow.memory RootAllocator)
           (org.apache.arrow.vector.types.pojo Field FieldType)))

(dotimes [i 10]
  (with-open [allocator (RootAllocator.)
              rel-wtr1 (vw/->rel-writer allocator)]

    (let [col-wtr1 (.colWriter rel-wtr1 "my-column" (FieldType/notNullable #xt.arrow/type :i64))
          write-t (doto (Thread.
                         (fn []
                           (dotimes [i 10000000]
                             (when (zero? (mod i 10000))
                               (prn i))
                             (.writeLong col-wtr1 i))))
                    (.start))
          vec (.getVector col-wtr1)

          read-ts (doall (for [t-id (range 20)]
                           (doto (Thread.
                                  (fn []
                                    (dotimes [i 10]
                                      (Thread/sleep (long (rand-int 50)))
                                      (with-open [_v (util/slice-vec vec)]
                                        (prn "thread" t-id "slice" i)))))
                             (.start))))]

      (.join write-t)
      (run! #(.join %) read-ts))))
```

**Comment by FiV0** [comment]
Replacing the `writeLong` call with `(writeObject col-write "some longish string")` already surfaces some issues.

**Comment by FiV0** [comment]
Another error surfaced by the above program. It would be good to understand the cause of that as well
```
11:54:05.920 [Thread-14813] ERROR xtdb.util - Uncaught exception:
java.lang.IllegalStateException: The final removal of reference manager should be connected to owning reference manager
	at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:458)
	at org.apache.arrow.memory.AllocationManager.release(AllocationManager.java:170)
	at org.apache.arrow.memory.BufferLedger.decrement(BufferLedger.java:157)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:124)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
	at org.apache.arrow.vector.BaseValueVector.releaseBuffer(BaseValueVector.java:117)
	at org.apache.arrow.vector.BaseVariableWidthVector.clear(BaseVariableWidthVector.java:270)
	at org.apache.arrow.vector.BaseVariableWidthVector.close(BaseVariableWidthVector.java:261)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:438)
	at arrow_read_write$eval44062$fn__44063$iter__44068__44072$fn__44073$fn__44074$fn__44076$fn__44077.invoke(NO_SOURCE_FILE:26)
	at arrow_read_write$eval44062$fn__44063$iter__44068__44072$fn__44073$fn__44074$fn__44076.invoke(NO_SOURCE_FILE:26)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
