### ISSUE TITLE
List concatenation

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3326]
Currently there is no way to concat lists or a list and an element in the EE. 
Postgres allows the following three (although on arrays in their case):
```sql
SELECT [1, 2, 3] || [4, 5]
SELECT [1, 2, 3] || 4
SELECT 1 || [2, 3, 4]
```

**Comment by refset** [comment]
Noting that a user on Discord recently reported trying to do this in an UPDATE and found that it causes an ingestion-stopped error:
```
INSERT INTO testing RECORDS {_id: 6, list: [1,2,3]};
=> 
INSERT 0 0

SELECT * FROM testing WHERE _id = 6;
=>
 _id |  list   
-----+---------
   6 | {1,2,3}

UPDATE testing SET list = list || [4] where _id = 6;
=> 
UPDATE 0
ERROR:  unexpected error on tx submit (report as a bug)

[...]

18:37:37 | ERROR xtdb.indexer.LogProcessor | Ingestion stopped: error processing log record at id 2241.
java.lang.IllegalArgumentException: No matching clause: [:list :i64]
    at xtdb.expression$codegen_concat.invokeStatic(expression.clj:1329)
    at xtdb.expression$codegen_concat.invoke(expression.clj:1317)
    at xtdb.expression$eval13990$fn__13992.invoke(expression.clj:700)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        ...

18:37:37 | ERROR xtdb.indexer.LogProcessor | XTDB transaction processing has encountered an unrecoverable error and has been stopped to prevent corruption of your data.
```

**Comment by jarohen** [comment]
@refset haven't impl'd the functionality yet, but have fixed the ingestion stopped
