### ISSUE TITLE
Issues with python tests

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3333]
Running `./gradlew :lang:test-harness:test`
currently gives me
```
Caused by: java.io.IOException: Cannot run program "poetry" (in directory "/lang/python"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at java.base/java.lang.Runtime.exec(Runtime.java:681)
	at clojure.java.shell$sh.invokeStatic(shell.clj:113)
	at clojure.java.shell$sh.doInvoke(shell.clj:79)
	at clojure.lang.RestFn.invoke(RestFn.java:460)
	at drivers.python_test$poetry_install.invokeStatic(python_test.clj:11)
	at drivers.python_test$poetry_install.invoke(python_test.clj:9)
	at clojure.test$compose_fixtures$fn__9878$fn__9879.invoke(test.clj:694)
	at clojure.test$default_fixture.invokeStatic(test.clj:687)
	at clojure.test$default_fixture.invoke(test.clj:683)
	at clojure.test$compose_fixtures$fn__9878.invoke(test.clj:694)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__1737.invoke(clojure_test.clj:51)
```

**Comment by Akeboshiwind** [comment]
Ah, this'll be because you don't have poetry installed locally 🤔 
I expect this will be a problem with all the language drivers.

Is this blocking you from running `./gradlew test`?
If so we should probably run language driver tests under a separate test command like the integration tests

**Comment by FiV0** [comment]
I have peotry installed
```
[fin@fin-ms7b79 xtdb2]$ poetry --version
Poetry (version 1.8.2)
```

**Comment by FiV0** [comment]
Fixed in the above.
