### ISSUE TITLE
compact-all intermittently hanging

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3375]

**Comment by jarohen** [comment]
fwiw atm I think this one is only a bug in compact-all rather than the compactor itself - there's relatively little in the compactor itself that could cause this kind of race condition.

(compact-all is used in tests as a means of saying "compact as much as you can" so that they can test the output of compaction - it's not used in production code)

**Comment by jarohen** [comment]
getting an intermittent error in the compactor, might be the cause:

```
15:22:19.211 [xtdb.compactor-280] ERROR xtdb.compactor - Error running compaction job.
java.lang.IndexOutOfBoundsException: index: -4, length: 4 (expected: range(0, 0))
	at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:320)
	at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:307)
	at org.apache.arrow.memory.ArrowBuf.getInt(ArrowBuf.java:426)
	at org.apache.arrow.vector.complex.DenseUnionVector.getOffset(DenseUnionVector.java:915)
	at xtdb.trie.ArrowHashTrie.forIndex(ArrowHashTrie.kt:75)
	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:86)
	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:13)
	at xtdb.trie.HashTrieKt.toMergePlan(HashTrie.kt:88)
	at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:63)
	at xtdb.compactor$merge_segments_into.invoke(compactor.clj:57)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__20444$fn__20445$fn__20454$fn__20455.invoke(compactor.clj:135)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__20444$fn__20445$fn__20454.invoke(compactor.clj:133)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__20444$fn__20445.invoke(compactor.clj:133)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__20444.invoke(compactor.clj:122)
	at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:122)
	at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:117)
	at xtdb.compactor$eval20559$fn__20561$compactor_task__20590$fn__20592.invoke(compactor.clj:275)
	at xtdb.compactor$eval20559$fn__20561$compactor_task__20590.invoke(compactor.clj:267)
	at xtdb.compactor$eval20559$fn__20561$fn__20597$fn__20598$fn__20599$fn__20605.invoke(compactor.clj:310)
	at clojure.lang.AFn.run(AFn.java:22)
```
