### ISSUE TITLE
Generative test failure in `row-copiers` 

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3391]
Test run: https://github.com/xtdb/xtdb/actions/runs/9367393238/job/25787291194

Stacktrace:
```
org.opentest4j.AssertionFailedError: FAIL in  (row-copiers) (arrow_generative_test.clj:188)
expected:  {:result true}
  actual:  {:shrunk {:total-nodes-visited 70819, :depth 358, :pass? false, :result false, :result-data nil, :time-shrinking-ms 117222, :smallest [#object[xtdb.vector.IndirectMultiVectorReader 0x764f0161 "(IndirectMultiVectorReader [(ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]})])"]]}, :failed-after-ms 1316, :num-tests 32, :seed 1717505628996, :fail [#object[xtdb.vector.IndirectMultiVectorReader 0x14c49bcd "(IndirectMultiVectorReader [(ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]}), (ValueVectorReader {vector=[]})])"]], :result false, :result-data nil, :failing-size 31, :pass? false, :test-var "row-copiers"}

	at dev.clojurephant.jovial.engine.clojure_test$eval914$fn__915.invoke(clojure_test.clj:75)
	at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at app//clojure.test$do_report.invokeStatic(test.clj:357)
	at app//clojure.test$do_report.invoke(test.clj:351)
	at app//clojure.test.check.clojure_test.assertions$check_results.invokeStatic(assertions.cljc:37)
	at app//clojure.test.check.clojure_test.assertions$check_results.invoke(assertions.cljc:32)
	at app//clojure.test.check.clojure_test$assert_check.invokeStatic(clojure_test.cljc:22)
	at app//clojure.test.check.clojure_test$assert_check.invoke(clojure_test.cljc:18)
	at app//xtdb.vector.arrow_generative_test$fn__29032.invokeStatic(arrow_generative_test.clj:188)
	at app//xtdb.vector.arrow_generative_test$fn__29032.invoke(arrow_generative_test.clj:188)
	at dev.clojurephant.jovial.engine.clojure_test$eval886$fn__889.invoke(clojure_test.clj:34)
	at dev.clojurephant.jovial.engine.clojure_test$eval844$fn__856$G__835__861.invoke(clojure_test.clj:16)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:53)
	at app//xtdb.test_util$with_allocator$fn__23959.invoke(test_util.clj:51)
	at app//xtdb.test_util$with_allocator.invokeStatic(test_util.clj:49)
	at app//xtdb.test_util$with_allocator.invoke(test_util.clj:48)
	at app//clojure.test$compose_fixtures$fn__9878$fn__9879.invoke(test.clj:694)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at app//clojure.test$compose_fixtures$fn__9878.invoke(test.clj:694)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:55)
	at app//clojure.test$default_fixture.invokeStatic(test.clj:687)
	at app//clojure.test$default_fixture.invoke(test.clj:683)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899$fn__900.invoke(clojure_test.clj:55)
	at dev.clojurephant.jovial.engine.clojure_test$eval872$fn__873$fn__874.invoke(clojure_test.clj:22)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invokeStatic(clojure_test.clj:50)
	at dev.clojurephant.jovial.engine.clojure_test$execute_node.invoke(clojure_test.clj:46)
	at dev.clojurephant.jovial.engine.clojure_test.Engine.execute(clojure_test.clj:113)
	at dev.clojurephant.jovial.engine$eval661$fn__688$G__653__691.invoke(engine.clj:23)
	at dev.clojurephant.jovial.engine$eval661$fn__688$G__652__695.invoke(engine.clj:23)
	at app//clojure.lang.AFn.applyToHelper(AFn.java:156)
	at app//clojure.lang.AFn.applyTo(AFn.java:144)
	at app//clojure.lang.Var.applyTo(Var.java:707)
	at app//clojure.core$apply.invokeStatic(core.clj:667)
	at app//clojure.core$apply.invoke(core.clj:662)
	at app//clojure.lang.Var.invoke(Var.java:390)
	at app//dev.clojurephant.jovial.util.SimpleClojure.invoke(SimpleClojure.java:21)
	at app//dev.clojurephant.jovial.BaseClojureEngine.execute(BaseClojureEngine.java:32)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@21.0.3/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base@21.0.3/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
	Suppressed: org.opentest4j.AssertionFailedError: ERROR in  () (BaseAllocator.java:491)
Uncaught exception, in fixtures.
expected:  nil

		at dev.clojurephant.jovial.engine.clojure_test$eval922$fn__923.invoke(clojure_test.clj:86)
		at app//clojure.lang.MultiFn.invoke(MultiFn.java:229)
		at app//clojure.test$do_report.invokeStatic(test.clj:357)
		at app//clojure.test$do_report.invoke(test.clj:351)
		at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:57)
		... 52 more
	Caused by: java.lang.IllegalStateException: Memory was leaked by query. Memory leaked: (18345430)
Allocator(ROOT) 0/18345430/25481250/9223372036854775807 (res/actual/peak/limit)

		at org.apache.arrow.memory.BaseAllocator.close(BaseAllocator.java:491)
		at org.apache.arrow.memory.RootAllocator.close(RootAllocator.java:29)
		at xtdb.util$close.invokeStatic(util.clj:57)
		at xtdb.util$close.invoke(util.clj:40)
		at xtdb.test_util$with_allocator.invokeStatic(test_util.clj:49)
		at xtdb.test_util$with_allocator.invoke(test_util.clj:48)
		at clojure.test$compose_fixtures$fn__9878$fn__9879.invoke(test.clj:694)
		at clojure.test$default_fixture.invokeStatic(test.clj:687)
		at clojure.test$default_fixture.invoke(test.clj:683)
		at clojure.test$compose_fixtures$fn__9878.invoke(test.clj:694)
		at dev.clojurephant.jovial.engine.clojure_test$execute_node$fn__899.invoke(clojure_test.clj:51)
		... 52 more
```

**Comment by jarohen** [comment]
let's try migrate this test to XT Arrow (if it isn't covered already)

**Comment by FiV0** [comment]
Should be covered by `full-vector-copy-preserves-data`.
