### ISSUE TITLE
StackOverflow in compactor on Auctionmark run

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3402]
Stacktrace of some likely infinite recursion 
```
12:58:02.542 [xtdb.compactor-0] ERROR xtdb.compactor - Error running compaction job.
java.lang.StackOverflowError: null
	at kotlin.ranges.IntProgression.<init>(Progressions.kt:97)
	at kotlin.ranges.IntRange.<init>(PrimitiveRanges.kt:52)
	at kotlin.ranges.RangesKt___RangesKt.until(_Ranges.kt:1095)
	at xtdb.Compactor.partitionSlices(Compactor.kt:26)
	at xtdb.Compactor.iidPartitions(Compactor.kt:49)
	at xtdb.Compactor.writeRelation$writeSubtree(Compactor.kt:132)
	at xtdb.Compactor.writeRelation$writeSubtree(Compactor.kt:134)
	at xtdb.Compactor.writeRelation$writeSubtree(Compactor.kt:134)
	at xtdb.Compactor.writeRelation$writeSubtree(Compactor.kt:134)
	at xtdb.Compactor.writeRelation$writeSubtree(Compactor.kt:134)
	at xtdb.Compactor.writeRelation$writeSubtree(Compactor.kt:134)
	...
```

**Comment by FiV0** [comment]
Trying to bump the SF from 0.1 to 0.2 and seeing if that already raises the issue could be an option.
