### ISSUE TITLE
Compactor error with polymorphic data

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3405]
```
18:03:43.917 [xtdb.compactor-1] ERROR xtdb.compactor - Error running compaction job.

java.lang.IllegalArgumentException: Could not load buffers for field foo: Union(Dense, [0, 1, 2, 3])<f64: FloatingPoint(DOUBLE) not null, utf8: Utf8 not null, i32: Int(32, true) not null, null: Null> not null. error message: index: 3, length: 1 (expected: range(0, 3))
                at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:122)
                at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:133)
                at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:133)
                at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:84)
                at xtdb.trie.ArrowDataRel$fn__61081.invoke(trie.clj:373)
                at xtdb.trie.ArrowDataRel.loadPage(trie.clj:372)
                at xtdb.trie$load_data_page.invokeStatic(trie.clj:410)
                at xtdb.trie$load_data_page.invoke(trie.clj:407)
                at clojure.core$mapv$fn__8551.invoke(core.clj:6988)
                at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
                at clojure.core.protocols$fn__8246.invokeStatic(protocols.clj:75)
                at clojure.core.protocols$fn__8246.invoke(protocols.clj:75)
                at clojure.core.protocols$fn__8194$G__8189__8207.invoke(protocols.clj:13)
                at clojure.core$reduce.invokeStatic(core.clj:6895)
                at clojure.core$mapv.invokeStatic(core.clj:6979)
                at clojure.core$mapv.invoke(core.clj:6979)
                at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:76)
                at xtdb.compactor$merge_segments_into.invoke(compactor.clj:56)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174$fn__68175$fn__68184$fn__68185.invoke(compactor.clj:134)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174$fn__68175$fn__68184.invoke(compactor.clj:132)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174$fn__68175.invoke(compactor.clj:132)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174.invoke(compactor.clj:121)
                at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:121)
                at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:116)
                at xtdb.compactor$eval68289$fn__68291$compactor_loop__68325.invoke(compactor.clj:280)
                at clojure.lang.AFn.run(AFn.java:22)
                at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
                at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)

Caused by: java.lang.IndexOutOfBoundsException: index: 3, length: 1 (expected: range(0, 3))
                at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:320)
                at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:307)
                at org.apache.arrow.memory.ArrowBuf.getByte(ArrowBuf.java:509)
                at org.apache.arrow.vector.complex.DenseUnionVector.getTypeId(DenseUnionVector.java:856)
                at org.apache.arrow.vector.complex.DenseUnionVector.loadFieldBuffers(DenseUnionVector.java:208)
                at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:114)
                ... 27 common frames omitted
```

`frequencies` of the input data:
```clojure
{java.lang.String 99078,
 java.lang.Integer 102333,
 java.lang.Double 113015,
 java.lang.Long 7,
 nil 1}
```

**Comment by jarohen** [comment]
I've unfortunately not managed to repro this one yet with various orders of the input data (I don't have access to the original data).

In a random order, these insert and compact fine - one theory is that it could be caused by two chunks both having a union type. I've also tried inserting all of one type first, then all of another.

Will go back to the original reporter and go into more detail.

**Comment by refset** [comment]
Since the changes to use XT Arrow in #3596 the user now reports that _ingestion_ completes successfully and they are able to run queries :tada: 

Unfortunately though it is not clear that compaction actually succeeds fully / at all - I have opened a new issue with that stack trace https://github.com/xtdb/xtdb/issues/3673
