### ISSUE TITLE
Compactor error storing >2^31 bytes in a single vector

### ISSUE THREAD

**Issue by jarohen** [xtdb/crux#3406]
```
15:54:14.919 [xtdb.compactor-5] ERROR xtdb.compactor - Error running compaction job.

org.apache.arrow.vector.util.OversizedAllocationException: Memory required for vector is (2147483648), which is overflow or more than max allowed (2147483647). You could consider using LargeVarCharVector/LargeVarBinaryVector for large strings/large bytes types
                at org.apache.arrow.vector.BaseVariableWidthVector.checkDataBufferSize(BaseVariableWidthVector.java:465)
                at org.apache.arrow.vector.BaseVariableWidthVector.reallocDataBuffer(BaseVariableWidthVector.java:574)
                at org.apache.arrow.vector.BaseVariableWidthVector.handleSafe(BaseVariableWidthVector.java:1344)
                at org.apache.arrow.vector.BaseVariableWidthVector.copyFromSafe(BaseVariableWidthVector.java:1446)
                at xtdb.vector.ScalarVectorWriter.rowCopier$lambda$1(FieldVectorWriters.kt:62)
                at xtdb.vector.StructVectorWriter.rowCopier$lambda$14(StructVectorWriter.kt:179)
                at xtdb.vector.DenseUnionVectorWriter$ChildWriter.rowCopier$lambda$0(DenseUnionVectorWriter.kt:108)
                at xtdb.vector.DenseUnionVectorWriter.duvRowCopier$lambda$6(DenseUnionVectorWriter.kt:209)
                at xtdb.compactor$__GT_reader__GT_copier$reader__GT_copier$reify__68123.copyRow(compactor.clj:51)
                at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:92)
                at xtdb.compactor$merge_segments_into.invoke(compactor.clj:56)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174$fn__68175$fn__68184$fn__68185.invoke(compactor.clj:134)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174$fn__68175$fn__68184.invoke(compactor.clj:132)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174$fn__68175.invoke(compactor.clj:132)
                at xtdb.compactor$exec_compaction_job_BANG_$fn__68174.invoke(compactor.clj:121)
                at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:121)
                at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:116)
                at xtdb.compactor$eval68289$fn__68291$compactor_loop__68325.invoke(compactor.clj:280)
                at clojure.lang.AFn.run(AFn.java:22)
                at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
                at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```

Distribution: ~3.3M entries, 12 rows >1MB, 300 >100kB, ~13k > 50kB, ~93k > 10kB, 3.2M <= 10kB

Looks like a by-product of bringing the whole chunk into one vector in the compactor to paginate it - maybe, now that we have multi-vec readers we can do this pagination just on the iid/recency cols initially and use this as an indirection for the individual pages?

**Comment by FiV0** [comment]
@jarohen Why the move to `OSS/Support issues`? You want to fix this Arrow side?

**Comment by refset** [comment]
@jarohen is this still relevant given the move to XT Arrow?

**Comment by jarohen** [comment]
@refset: yep - we'll need to promote to the 'large' Arrow equivalents here
