### ISSUE TITLE
Java Heap Space OoM when running Auctionmark for an Hour

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#3421]
When running Auctionmark on AWS for a 1hour run, at a point about 30 minutes in we receive a `java.lang.OutOfMemoryError: Java heap space` error.

## Stack Trace

The following is a stack trace from our AWS container's logs:

```
EVENTS	1718638034616	15:27:13.243 [core2-benchmark-pool-9-thread-2] ERROR xtdb.bench - Error while executing xtdb.bench.auctionmark$index_item_status_groups@166befb2	1718638033244
EVENTS	1718638034616	java.lang.OutOfMemoryError: Java heap space	1718638033244
EVENTS	1718638034616		at java.base/java.util.LinkedHashMap.sequencedValues(LinkedHashMap.java:792)	1718638033244
EVENTS	1718638034616		at java.base/java.util.LinkedHashMap.values(LinkedHashMap.java:777)	1718638033244
EVENTS	1718638034616		at xtdb.vector.RelationWriter.close(RelationWriter.kt:39)	1718638033244
EVENTS	1718638034616		at xtdb.operator.scan.TrieCursor$fn__22871.invoke(scan.clj:251)	1718638033244
EVENTS	1718638034616		at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:251)	1718638033244
EVENTS	1718638034616		at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)	1718638033244
EVENTS	1718638034616		at xtdb.query$wrap_cursor$reify__28984.tryAdvance(query.clj:75)	1718638033244
EVENTS	1718638034616		at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)	1718638033244
EVENTS	1718638034616		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)	1718638033244
EVENTS	1718638034616		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)	1718638033244
EVENTS	1718638034616		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)	1718638033244
EVENTS	1718638034616		at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)	1718638033244
EVENTS	1718638034616		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)	1718638033244
EVENTS	1718638034616		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)	1718638033244
EVENTS	1718638034616		at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)	1718638033244
EVENTS	1718638034616		at xtdb.api$q.invokeStatic(api.clj:113)	1718638033244
EVENTS	1718638034616		at xtdb.api$q.invoke(api.clj:61)	1718638033244
EVENTS	1718638034616		at xtdb.bench.auctionmark$item_status_groups.invokeStatic(auctionmark.clj:399)	1718638033244
EVENTS	1718638034616		at xtdb.bench.auctionmark$item_status_groups.invoke(auctionmark.clj:398)	1718638033244
EVENTS	1718638034616		at xtdb.bench.auctionmark$index_item_status_groups.invokeStatic(auctionmark.clj:436)	1718638033244
EVENTS	1718638034616		at xtdb.bench.auctionmark$index_item_status_groups.invoke(auctionmark.clj:433)	1718638033244
EVENTS	1718638034616		at clojure.lang.AFn.applyToHelper(AFn.java:154)	1718638033244
EVENTS	1718638034616		at clojure.lang.AFn.applyTo(AFn.java:144)	1718638033244
EVENTS	1718638034616		at clojure.core$apply.invokeStatic(core.clj:667)	1718638033244
EVENTS	1718638034616		at clojure.core$apply.invoke(core.clj:662)	1718638033244
EVENTS	1718638034616		at xtdb.bench$wrap_in_catch$fn__5960.doInvoke(bench.clj:19)	1718638033244
EVENTS	1718638034616		at clojure.lang.RestFn.invoke(RestFn.java:408)	1718638033244
EVENTS	1718638034616		at xtdb.bench.measurement$wrap_transaction$instrumented_transaction__8132.invoke(measurement.clj:33)	1718638033244
EVENTS	1718638034616		at xtdb.bench$compile_benchmark$compile_task__6073$run_freq_job__6098.invoke(bench.clj:280)	1718638033244
EVENTS	1718638034616		at xtdb.bench$compile_benchmark$compile_task__6073$start_thread__6114$fn__6115.invoke(bench.clj:253)	1718638033244
EVENTS	1718638034616		at clojure.lang.AFn.run(AFn.java:22)	1718638033244
EVENTS	1718638034616		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)	1718638033244
```

## Todo:

- [x] Attempt to get a Repro locally by lowering the amount of Heap space (also trying to replicate without AWS in the mix)
- [x] See if we can find where memory is growing/where when running Auctionmark that causes it to OoM

**Comment by danmason** [comment]
Replicated this locally fairly quickly by lowering HeapSize down to 1000MB.

While there is some heavy usage of `custom-state` within auctionmark, from profiling we can see where a large majority of the memory is being used. A grand majority of the memory usage that I saw from a node that returned an OoM was the `plan-cache` within `query-source`:
- Retained size makes up the majority of used memory.
- Continues to grow - no limit to the amount of items within it (and from what I can tell, no mechanism to do so? Stored within a `ConcurrentHashMap`)
- Since each auctionmark query has some random elements within it (ie, which item a comment might belong to, etc), we're generating a LOT of slightly different queries
