### ISSUE TITLE
"Unable to execute HTTP request" from SQS when running Auctionmark

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#3422]
On our long running Auctionmark benchmarks on AWS, we saw a few errors being thrown from SQS regarding failed/timing out connections. Want to investigate this, see if it causes many problems in the file watcher, and see if we can edit the file watching loop to better handle this (either through investigating SQS/socket config or writing in some backoff logic).

## Example Stacktrace

Seen from one of our 1hour runs on AWS:
```
EVENTS	1718638034616	Exception in thread "Thread-0" software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Connection reset	1718638033336
EVENTS	1718638034616		at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)	1718638033348
EVENTS	1718638034616		at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)	1718638033348
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:223)	1718638033348
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:83)	1718638033349
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)	1718638033349
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)	1718638033349
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)	1718638033349
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)	1718638033349
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)	1718638033349
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)	1718638033350
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)	1718638033350
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)	1718638033350
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)	1718638033350
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)	1718638033350
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)	1718638033351
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)	1718638033351
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)	1718638033351
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:224)	1718638033351
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)	1718638033351
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)	1718638033351
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)	1718638033352
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)	1718638033352
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)	1718638033352
EVENTS	1718638034616		at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)	1718638033352
EVENTS	1718638034616		at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)	1718638033352
EVENTS	1718638034616		at software.amazon.awssdk.services.sqs.DefaultSqsClient.receiveMessage(DefaultSqsClient.java:1949)	1718638033352
EVENTS	1718638034616		at xtdb.s3.file_list$open_file_list_watcher$fn__30118.invoke(file_list.clj:110)	1718638033353
EVENTS	1718638034616		at clojure.lang.AFn.run(AFn.java:22)	1718638033353
EVENTS	1718638034616		at java.base/java.lang.Thread.run(Thread.java:1583)	1718638033353
EVENTS	1718638034616		Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 1 failure: Unable to execute HTTP request: The target server failed to respond	1718638033353
EVENTS	1718638034616		Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 2 failure: Unable to execute HTTP request: Connection reset	1718638033354
EVENTS	1718638034616		Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 3 failure: Unable to execute HTTP request: Connection reset	1718638033354
EVENTS	1718638034616	Caused by: java.net.SocketException: Connection reset	1718638033354
EVENTS	1718638034616		at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)	1718638033355
EVENTS	1718638034616		at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)	1718638033355
EVENTS	1718638034616		at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)	1718638033361
EVENTS	1718638034616		at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)	1718638033362
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)	1718638033362
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)	1718638033362
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)	1718638033362
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)	1718638033362
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)	1718638033362
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)	1718638033363
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)	1718638033382
EVENTS	1718638034616		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)	1718638033383
EVENTS	1718638034616		at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)	1718638033383
EVENTS	1718638034616		at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)	1718638033383
EVENTS	1718638034616		at software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory.connectSocket(SdkTlsSocketFactory.java:65)	1718638033383
EVENTS	1718638034616		at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)	1718638033383
EVENTS	1718638034616		at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)	1718638033384
EVENTS	1718638034616		at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$DelegatingHttpClientConnectionManager.connect(ClientConnectionManagerFactory.java:86)	1718638033384
EVENTS	1718638034616		at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)	1718638033384
EVENTS	1718638034616		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)	1718638033384
EVENTS	1718638034616		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)	1718638033384
EVENTS	1718638034616		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)	1718638033384
EVENTS	1718638034616		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)	1718638033385
EVENTS	1718638034616		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)	1718638033385
EVENTS	1718638034616		at software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)	1718638033385
EVENTS	1718638034616		at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:254)	1718638033386
EVENTS	1718638034616		at software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:104)	1718638033386
EVENTS	1718638034616		at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:231)	1718638033386
EVENTS	1718638034616		at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:228)	1718638033386
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:99)	1718638033386
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:79)	1718638033387
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:57)	1718638033387
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:40)	1718638033387
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)	1718638033387
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)	1718638033388
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)	1718638033388
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)	1718638033388
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)	1718638033388
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)	1718638033388
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)	1718638033389
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)	1718638033389
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)	1718638033389
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)	1718638033391
EVENTS	1718638034616		at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)	1718638033391
EVENTS	1718638034616		... 25 more	1718638033391
```

One thing to note is that we _did_ see this error thrown at the same time in the logs as our OoM, #3421, though it seems like it was likely thrown at a point earlier looking at the stacktrace above, in particular:

```
EVENTS	1718638034616		Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 1 failure: Unable to execute HTTP request: The target server failed to respond	1718638033353
EVENTS	1718638034616		Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 2 failure: Unable to execute HTTP request: Connection reset	1718638033354
EVENTS	1718638034616		Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 3 failure: Unable to execute HTTP request: Connection reset	1718638033354
```

**Comment by jarohen** [comment]
see #3631
