### ISSUE TITLE
http-server: Getting a `Error decoding JSON` on /query

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3444]
Setup:
1. `docker run --pull=always -tip 6543:3000 ghcr.io/xtdb/xtdb-standalone-ea`
2. `curl http://localhost:6543/status` (works fine)
3. `curl -v --header "Content-Type: application/json" --data '{"query": {"sql": "SELECT * FROM docs"}}' -XPOST http://localhost:6543/query` returns an error
4. `curl -s https://docs.xtdb.com/xtsql.py -O && python xtsql.py --url=http://localhost:6543`
5. `SELECT * FROM docs;` returns an error

**Comment by Akeboshiwind** [comment]
Log from docker container:
```
latest: Pulling from xtdb/xtdb-standalone-ea
Digest: sha256:735f69a0a361e1e1e0ac2c1c43b76f5301ddd41808022e0bbfbcdc1b0cd4d7d2
Status: Image is up to date for ghcr.io/xtdb/xtdb-standalone-ea:latest
Starting XTDB 2.x (pre-alpha) @ "dev-SNAPSHOT" @ bab740f ...
13:48:35 | DEBUG xtdb.metrics | Metrics server started on port:  8080
13:48:35 | INFO  xtdb.server | HTTP server started on port:  3000
13:48:35 | INFO  xtdb.pgwire | PGWire server started on port: 5432
13:48:35 | INFO  xtdb.cli | Node started
13:48:46 | DEBUG xtdb.server | response error (class clojure.lang.ExceptionInfo): 'Malformed application/json request.'
clojure.lang.ExceptionInfo: Malformed application/json request.
        at muuntaja.core$fail_on_request_decode_exception.invokeStatic(core.clj:132)
        at muuntaja.core$fail_on_request_decode_exception.invoke(core.clj:126)
        at muuntaja.core$create$_decode_request_body__12381.invoke(core.clj:424)
        at muuntaja.core$create$reify__12403.format_request(core.clj:476)
        at muuntaja.interceptor$format_request_interceptor$fn__17091.invoke(interceptor.clj:96)
        at sieppari.core$_try.invokeStatic(core.cljc:20)
        at sieppari.core$_try.invoke(core.cljc:17)
        at sieppari.core$enter.invokeStatic(core.cljc:62)
        at sieppari.core$enter.invoke(core.cljc:49)
        at sieppari.core$execute$fn__17765.invoke(core.cljc:125)
        at sieppari.core$execute.invokeStatic(core.cljc:123)
        at sieppari.core$execute.invoke(core.cljc:117)
        at reitit.interceptor.sieppari$reify__17774.execute(sieppari.clj:18)
        at reitit.http$ring_handler$fn__16832.invoke(http.cljc:165)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at ring.adapter.jetty9.handlers.async$_doHandle.invokeStatic(async.clj:34)
        at ring.adapter.jetty9.handlers.async$_doHandle.invoke(async.clj:22)
        at ring.adapter.jetty9.handlers.AsyncProxyHandler.doHandle(Unknown Source)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at ring.adapter.jetty9.handlers.AsyncProxyHandler.doScope(Unknown Source)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: clojure.lang.ExceptionInfo: Malformed application/json in :muuntaja/decode
        at muuntaja.core$on_exception.invokeStatic(core.clj:284)
        at muuntaja.core$on_exception.invoke(core.clj:267)
        at clojure.core$partial$fn__5908.invoke(core.clj:2643)
        at muuntaja.core$create_coder$decode__12331.invoke(core.clj:322)
        at muuntaja.core$create$_decode_request_body__12381.invoke(core.clj:422)
        ... 39 common frames omitted
Caused by: xtdb.IllegalArgumentException: Error decoding JSON!
        at xtdb.JsonSerde.decode(JsonSerde.kt:248)
        at xtdb.server$json_query_decoder$reify__18046.decode(server.clj:242)
        at muuntaja.core$create_coder$decode__12331.invoke(core.clj:320)
        ... 40 common frames omitted
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'query' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {"query": {"sql": "SELECT * FROM docs"}}
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:593)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:257)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:243)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:178)
        at xtdb.api.query.QueryRequest$$serializer.deserialize(QueryRequest.kt:8)
        at xtdb.api.query.QueryRequest$$serializer.deserialize(QueryRequest.kt:8)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
        at kotlinx.serialization.json.internal.JsonStreamsKt.decodeByReader(JsonStreams.kt:43)
        at kotlinx.serialization.json.JvmStreamsKt.decodeFromStream(JvmStreams.kt:61)
        at xtdb.JsonSerde.decode(JsonSerde.kt:240)
        ... 42 common frames omitted
        Suppressed: java.io.IOException: mark/reset not supported
                at java.base/java.io.InputStream.reset(InputStream.java:741)
                at xtdb.JsonSerde.decode(JsonSerde.kt:243)
                ... 42 common frames omitted
```

**Comment by jarohen** [comment]
(discussed on Slack) - issue was that `sql` is now at the top-level after #3403
