### ISSUE TITLE
Arrow OutOfMemoryException in Local Auctionmark

### ISSUE THREAD

**Issue by danmason** [xtdb/crux#3457]
Similar to our other Heap Space OOM (#3451), witnessed a `org.apache.arrow.memory.OutOfMemoryException: Failure allocating buffer.` error thrown while running auctionmark locally (with `cloud-benchmark:local`). This was actually caused by a lack of Direct Memory available, rather than Heap Memory.

## Details

Thrown running auctionmark locally on docker - within a volume attached.

Memory settings on Java task:
```
   - `"-Xmx1500m", "-Xms1500m", \
    "-XX:MaxDirectMemorySize=2000m", \
    "-XX:MaxMetaspaceSize=500m", \`
```

Node config:
```yaml
txLog: !Local
  path: /var/lib/xtdb/local-log

storage: !Local
  path: /var/lib/xtdb/local-buffers

metrics:
```

## Stack Trace

```
10:32:03.039 [xtdb.compactor-94] ERROR xtdb.compactor - Error running compaction job.
org.apache.arrow.memory.OutOfMemoryException: Failure allocating buffer.
	at io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:66)
	at org.apache.arrow.memory.netty.NettyAllocationManager.<init>(NettyAllocationManager.java:82)
	at org.apache.arrow.memory.netty.NettyAllocationManager.<init>(NettyAllocationManager.java:89)
	at org.apache.arrow.memory.netty.NettyAllocationManager$1.create(NettyAllocationManager.java:39)
	at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:367)
	at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:362)
	at org.apache.arrow.memory.BaseAllocator.bufferWithoutReservation(BaseAllocator.java:350)
	at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:328)
	at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:291)
	at org.apache.arrow.vector.BaseVariableWidthVector.reallocDataBuffer(BaseVariableWidthVector.java:576)
	at org.apache.arrow.vector.BaseVariableWidthVector.handleSafe(BaseVariableWidthVector.java:1344)
	at org.apache.arrow.vector.BaseVariableWidthVector.copyFromSafe(BaseVariableWidthVector.java:1446)
	at xtdb.vector.ScalarVectorWriter.rowCopier$lambda$1(FieldVectorWriters.kt:62)
	at xtdb.vector.StructVectorWriter.rowCopier$lambda$14(StructVectorWriter.kt:179)
	at xtdb.vector.DenseUnionVectorWriter$ChildWriter.rowCopier$lambda$0(DenseUnionVectorWriter.kt:108)
	at xtdb.vector.DenseUnionVectorWriter.duvRowCopier$lambda$6(DenseUnionVectorWriter.kt:209)
	at xtdb.compactor$__GT_reader__GT_copier$reader__GT_copier$reify__15783.copyRow(compactor.clj:54)
	at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:95)
	at xtdb.compactor$merge_segments_into.invoke(compactor.clj:59)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__15834$fn__15835$fn__15844$fn__15845.invoke(compactor.clj:137)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__15834$fn__15835$fn__15844.invoke(compactor.clj:135)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__15834$fn__15835.invoke(compactor.clj:135)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__15834.invoke(compactor.clj:124)
	at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:124)
	at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:119)
	at xtdb.compactor$eval15949$fn__15951$compactor_task__15980$fn__15982.invoke(compactor.clj:272)
	at xtdb.compactor$eval15949$fn__15951$compactor_task__15980.invoke(compactor.clj:270)
	at xtdb.compactor$eval15949$fn__15951$fn__15985$fn__15986$fn__15987$fn__15993.invoke(compactor.clj:307)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 268435456 byte(s) of direct memory (used: 1933574144, max: 2097152000)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:843)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:772)
	at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.allocateDirect(UnpooledUnsafeNoCleanerDirectByteBuf.java:30)
	at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf.allocateDirect(UnpooledByteBufAllocator.java:186)
	at io.netty.buffer.UnpooledDirectByteBuf.<init>(UnpooledDirectByteBuf.java:64)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:41)
	at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.<init>(UnpooledUnsafeNoCleanerDirectByteBuf.java:25)
	at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf.<init>(UnpooledByteBufAllocator.java:181)
	at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:91)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.newDirectBufferL(PooledByteBufAllocatorL.java:167)
	at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.directBuffer(PooledByteBufAllocatorL.java:210)
	at io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:57)
```

## TODO

- [ ] Investigate sources/places that we allocate direct memory.
- [ ] Run locally with a profiler and see behaviour.

**Comment by jarohen** [comment]
optimistically closing after #3471
