### ISSUE TITLE
IOB in 24H Auctionmark AWS run

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3488]
This is another one of these arrow empty vector issues, where certain operations throw on an empty vector.
```
java.lang.IndexOutOfBoundsException: index: -4, length: 4 (expected: range(0, 0))
	2024-07-09T19:56:47.830Z	at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:320)
	2024-07-09T19:56:47.830Z	at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:307)
	2024-07-09T19:56:47.830Z	at org.apache.arrow.memory.ArrowBuf.getInt(ArrowBuf.java:426)
	2024-07-09T19:56:47.830Z	at org.apache.arrow.vector.complex.DenseUnionVector.getOffset(DenseUnionVector.java:915)
	2024-07-09T19:56:47.830Z	at xtdb.trie.ArrowHashTrie.forIndex(ArrowHashTrie.kt:75)
	2024-07-09T19:56:47.830Z	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:86)
	2024-07-09T19:56:47.830Z	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:13)
	2024-07-09T19:56:47.830Z	at xtdb.trie.HashTrieKt.toMergePlan(HashTrie.kt:89)
	2024-07-09T19:56:47.830Z	at xtdb.operator.scan$__GT_merge_tasks.invokeStatic(scan.clj:361)
	2024-07-09T19:56:47.830Z	at xtdb.operator.scan$__GT_merge_tasks.invoke(scan.clj:353)
	2024-07-09T19:56:47.830Z	at xtdb.operator.scan$eval23035$fn$reify__23040$fn__23143$fn__23150$fn__23151.invoke(scan.clj:498)
	2024-07-09T19:56:47.830Z	at xtdb.operator.scan$eval23035$fn$reify__23040$fn__23143$fn__23150.invoke(scan.clj:497)
	2024-07-09T19:56:47.830Z	at xtdb.operator.scan$eval23035$fn$reify__23040$fn__23143.invoke(scan.clj:496)
	2024-07-09T19:56:47.830Z	at xtdb.logical_plan$unary_expr$fn__21915.invoke(logical_plan.clj:119)
	2024-07-09T19:56:47.830Z	at xtdb.logical_plan$unary_expr$fn__21915.invoke(logical_plan.clj:119)
	2024-07-09T19:56:47.830Z	at xtdb.query$prepare_ra$reify$reify__29178.openCursor(query.clj:208)
	2024-07-09T19:56:47.830Z	at xtdb.query$open_cursor_as_stream.invokeStatic(query.clj:289)
	2024-07-09T19:56:47.830Z	at xtdb.query$open_cursor_as_stream.invoke(query.clj:287)
	2024-07-09T19:56:47.830Z	at xtdb.node.impl$then_execute_prepared_query.invokeStatic(impl.clj:56)
	2024-07-09T19:56:47.830Z	at xtdb.node.impl$then_execute_prepared_query.invoke(impl.clj:53)
	2024-07-09T19:56:47.830Z	at xtdb.node.impl.Node.open_sql_query(impl.clj:115)
```

**Comment by jarohen** [comment]
hmm, same stack trace as we saw in #3240 :thinking:
