### ISSUE TITLE
File AccessDeniedException in disk cache on Azure Auctionmark

### ISSUE THREAD

**Issue by tggreene** [xtdb/crux#3536]
We're seeing the following error after some time (~5 minutes) on a node responsible for the load phase:

```
2024-07-30T10:59:53.256205831Z java.util.concurrent.CompletionException: java.nio.file.AccessDeniedException: /var/lib/xtdb/disk-cache/cache-1/.tmp/upload2353722833684105263.arrow -> /var/lib/xtdb/disk-cache/cache-1/tables/item/meta/log-l00-fr4965d1-nr4af6f1-rs1900d.arrow
2024-07-30T10:59:53.256212723Z  at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
2024-07-30T10:59:53.256243651Z  at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
2024-07-30T10:59:53.256249321Z  at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
2024-07-30T10:59:53.256255092Z  at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
2024-07-30T10:59:53.256260572Z  at xtdb.util$then_apply.invokeStatic(util.clj:315)
2024-07-30T10:59:53.256266072Z  at xtdb.util$then_apply.invoke(util.clj:312)
2024-07-30T10:59:53.256271703Z  at xtdb.buffer_pool.RemoteBufferPool$reify__8520$fn__8521.invoke(buffer_pool.clj:420)
2024-07-30T10:59:53.256277384Z  at xtdb.buffer_pool$update_evictor_key$reify__8466.apply(buffer_pool.clj:335)
2024-07-30T10:59:53.256282473Z  at com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncAsMapView.lambda$compute$3(LocalAsyncCache.java:410)
2024-07-30T10:59:53.256287272Z  at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$remap$16(BoundedLocalCache.java:2891)
2024-07-30T10:59:53.256292461Z  at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940)
2024-07-30T10:59:53.256297370Z  at com.github.benmanes.caffeine.cache.BoundedLocalCache.remap(BoundedLocalCache.java:2853)
2024-07-30T10:59:53.256302580Z  at com.github.benmanes.caffeine.cache.BoundedLocalCache.compute(BoundedLocalCache.java:2803)
2024-07-30T10:59:53.256307950Z  at com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncAsMapView.compute(LocalAsyncCache.java:409)
2024-07-30T10:59:53.256313290Z  at com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncAsMapView.compute(LocalAsyncCache.java:295)
2024-07-30T10:59:53.256321706Z  at xtdb.buffer_pool$update_evictor_key.invokeStatic(buffer_pool.clj:334)
2024-07-30T10:59:53.256327306Z  at xtdb.buffer_pool$update_evictor_key.invoke(buffer_pool.clj:333)
2024-07-30T10:59:53.256332887Z  at xtdb.buffer_pool.RemoteBufferPool$reify__8520.end(buffer_pool.clj:416)
2024-07-30T10:59:53.256338327Z  at xtdb.trie$open_trie_writer$reify__15758$fn__15771.invoke(trie.clj:201)
2024-07-30T10:59:53.256345290Z  at xtdb.trie$open_trie_writer$reify__15758.end(trie.clj:199)
2024-07-30T10:59:53.256350860Z  at xtdb.trie$write_live_trie_BANG_$fn__15809.invoke(trie.clj:243)
2024-07-30T10:59:53.256355629Z  at xtdb.trie$write_live_trie_BANG_.invokeStatic(trie.clj:235)
2024-07-30T10:59:53.256360448Z  at xtdb.trie$write_live_trie_BANG_.invoke(trie.clj:232)
2024-07-30T10:59:53.256365167Z  at xtdb.indexer.live_index.LiveTable$fn__21122.invoke(live_index.clj:186)
2024-07-30T10:59:53.256370256Z  at clojure.lang.AFn.run(AFn.java:22)
2024-07-30T10:59:53.256375195Z  at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
2024-07-30T10:59:53.256380555Z  at java.base/java.lang.Thread.run(Thread.java:1583)
2024-07-30T10:59:53.256386416Z Caused by: java.nio.file.AccessDeniedException: /var/lib/xtdb/disk-cache/cache-1/.tmp/upload2353722833684105263.arrow -> /var/lib/xtdb/disk-cache/cache-1/tables/item/meta/log-l00-fr4965d1-nr4af6f1-rs1900d.arrow
2024-07-30T10:59:53.256391896Z  at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
2024-07-30T10:59:53.256397206Z  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
2024-07-30T10:59:53.256402105Z  at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:873)
2024-07-30T10:59:53.256407575Z  at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
2024-07-30T10:59:53.256412845Z  at java.base/java.nio.file.Files.move(Files.java:1430)
2024-07-30T10:59:53.256418235Z  at xtdb.util$atomic_move.invokeStatic(util.clj:295)
2024-07-30T10:59:53.256423044Z  at xtdb.util$atomic_move.invoke(util.clj:294)
2024-07-30T10:59:53.256439595Z  at xtdb.buffer_pool.RemoteBufferPool$reify__8520$fn__8521$fn__8523.invoke(buffer_pool.clj:425)
2024-07-30T10:59:53.256445115Z  at xtdb.util$$reify__5786.apply(util.clj:310)
2024-07-30T10:59:53.256449984Z  at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
2024-07-30T10:59:53.256454663Z  ... 25 more
```

**Comment by danmason** [comment]
A bit confusing to me given that each disk-cache should have their own directory in the multi-node run - worth just verifying that, but if it is the case seems like it could be some kind of timing/locking issue? (Ie, one thing has created the file/has a lock on it, one is trying to copy to its location)?

**Comment by danmason** [comment]
I suppose in the multi node run it COULD be something that looks like this:
- Another node writes the arrow file out to the object store (Ie, openArrowWriter invoked, file written to object store).
- The second node calls to `getObject` on the arrow file, which writes it into their disk cache.
- `openArrowWriter` is being invoked at around the same time (some kind of race condition), and attempts to move to a file at the wrong point causing the error.
  - Either that, or `atomic-move` throws an error if a file already exists.

**Comment by tggreene** [comment]
We worked around this by essentially not writing files that already exist in the buffer pool [here](https://github.com/tggreene/xtdb/commit/e01f58fc66eed4c3875a2a507c237199f16b341f), but haven't addressed the underlying issue

**Comment by refset** [comment]
This looks almost identical to https://github.com/xtdb/xtdb/issues/3566 except for the actual error thrown :thinking: (same stack trace around `uploadXXXX.arrow -> log-l00-XXXX.arrow` whilst doing `xtdb.trie$write_live_trie`)
