### ISSUE TITLE
Negative Ref Count in compactor

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3551]
```
java.lang.IllegalStateException: Ref count should be >= 1 for accessing the ArrowBuf
	at org.apache.arrow.memory.ArrowBuf.ensureAccessible(ArrowBuf.java:119)
	at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:291)
	at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:285)
	at org.apache.arrow.memory.ArrowBuf.getByte(ArrowBuf.java:487)
	at xtdb.arrow.ExtensibleBuffer.getByte(Buffers.kt:64)
	at xtdb.arrow.DenseUnionVector.getTypeId(DenseUnionVector.kt:93)
	at xtdb.arrow.DenseUnionVector.leg(DenseUnionVector.kt:101)
	at xtdb.arrow.DenseUnionVector.getLeg(DenseUnionVector.kt:116)
	at xtdb.trie.ArrowHashTrie.forIndex(ArrowHashTrie.kt:68)
	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:76)
	at xtdb.trie.ArrowHashTrie.getRootNode(ArrowHashTrie.kt:11)
	at xtdb.trie.HashTrieKt.toMergePlan(HashTrie.kt:93)
	at xtdb.compactor$merge_segments_into.invokeStatic(compactor.clj:66)
	at xtdb.compactor$merge_segments_into.invoke(compactor.clj:60)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__23846$fn__23847$fn__23856$fn__23857.invoke(compactor.clj:139)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__23846$fn__23847$fn__23856.invoke(compactor.clj:137)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__23846$fn__23847.invoke(compactor.clj:137)
	at xtdb.compactor$exec_compaction_job_BANG_$fn__23846.invoke(compactor.clj:126)
	at xtdb.compactor$exec_compaction_job_BANG_.invokeStatic(compactor.clj:126)
	at xtdb.compactor$exec_compaction_job_BANG_.invoke(compactor.clj:121)
	at xtdb.compactor$eval23962$fn__23964$compactor_task__23993$fn__23995.invoke(compactor.clj:275)
	at xtdb.compactor$eval23962$fn__23964$compactor_task__23993.invoke(compactor.clj:273)
	at xtdb.compactor$eval23962$fn__23964$fn__23998$fn__23999$fn__24000$fn__24006.invoke(compactor.clj:310)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
	Suppressed: java.lang.IllegalStateException: RefCnt has gone negative
		at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:422)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:128)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
		at org.apache.arrow.memory.ArrowBuf.close(ArrowBuf.java:1040)
		at xtdb.arrow.ExtensibleBuffer.close(Buffers.kt:141)
		at xtdb.arrow.DenseUnionVector.close(DenseUnionVector.kt:178)
		at xtdb.arrow.Relation.close(Relation.kt:168)
		at xtdb.util$close.invokeStatic(util.clj:58)
		at xtdb.util$close.invoke(util.clj:41)
		at xtdb.metadata.TableMetadata.close(metadata.clj:385)
		at xtdb.util$close.invokeStatic(util.clj:58)
		at xtdb.util$close.invoke(util.clj:41)
		at xtdb.util$close$close_all__4296$fn__4299.invoke(util.clj:46)
		at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
		at clojure.core.protocols$fn__8246.invokeStatic(protocols.clj:75)
		at clojure.core.protocols$fn__8246.invoke(protocols.clj:75)
		at clojure.core.protocols$fn__8194$G__8189__8207.invoke(protocols.clj:13)
		at clojure.core$reduce.invokeStatic(core.clj:6895)
		at clojure.core$reduce.invoke(core.clj:6877)
		at xtdb.util$close$close_all__4296.invoke(util.clj:44)
		at xtdb.util$close.invokeStatic(util.clj:60)
		at xtdb.util$close.invoke(util.clj:41)
		at xtdb.compactor$exec_compaction_job_BANG_$fn__23846$fn__23879.invoke(compactor.clj:126)
		... 10 common frames omitted
```

**Comment by danmason** [comment]
Encountered this recently on Azure benchmark - (notes [**here**](https://github.com/xtdb/xtdb/issues/3478#issuecomment-2348565271))

Saw the following two errors occur at around the same time (same error in different calls/places):
```
22:57:09.402 [core2-benchmark-pool-7-thread-7] ERROR xtdb.bench - Error while executing xtdb.bench.auctionmark$proc_new_bid@4df4499a
java.lang.IndexOutOfBoundsException: index: -1, length: 1 (expected: range(0, 21))
	at org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:299)
	at org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:285)
	...
	at xtdb.node.impl.Node.open_sql_query(impl.clj:117)
	at xtdb.api$plan_q$reify__7747.reduce(api.clj:81)
	...
	Suppressed: java.lang.IllegalStateException: RefCnt has gone negative
		at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:422)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:128)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
		at org.apache.arrow.memory.ArrowBuf.close(ArrowBuf.java:1040)
		...
		at xtdb.util$close.invokeStatic(util.clj:56)
		at xtdb.util$close.invoke(util.clj:37)
		at xtdb.operator.scan$eval26459$fn$reify__26464$fn__26567$fn__26574$fn__26575$fn__26602.invoke(scan.clj:454)
		at xtdb.operator.scan$eval26459$fn$reify__26464$fn__26567$fn__26574$fn__26575.invoke(scan.clj:454)
		... 37 common frames omitted
Sep 12, 2024 10:57:09 PM com.github.benmanes.caffeine.cache.BoundedLocalCache lambda$notifyRemoval$1
WARNING: Exception thrown by removal listener

java.lang.IllegalStateException: RefCnt has gone negative
	at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:422)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:128)
	at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:104)
	at org.apache.arrow.memory.ArrowBuf.close(ArrowBuf.java:1040)
	at xtdb.util$close.invokeStatic(util.clj:54)
	at xtdb.util$close.invoke(util.clj:37)
	at xtdb.buffer_pool$$reify__8477.onRemoval(buffer_pool.clj:214)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$notifyRemoval$1(BoundedLocalCache.java:422)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
```

Full error logs/stack traces [here](https://github.com/danmason/xtdb/blob/0cb77856396093b8273b5799a10a019d060f684e/cloud-benchmark/azure/azure-logs/12h/node-1#L820).

**Comment by jarohen** [comment]
optimistically closing this one after the referenced commit, feel free to re-open if we see it again

**Comment by egg-juxt** [comment]
I am still seeing these when the Compactor raises Arrow OOMs when it runs out of its allocator memory limit:

```
2026-02-17T10:11:14.001989985Z ERROR xtdb.compactor.Compactor 
error running compaction job: public/explanation_of_benefit/l04-rc-p233-b310ec, files in job: '["l03-rc-p23-b31043" "l03-rc-p23-b3106f" "l03-rc-p23-b3109d" "l03-rc-p23-b310ec"]'
org.apache.arrow.memory.OutOfMemoryException: Unable to allocate buffer of size 139808078 due to memory limit. Current allocation: 0
	at org.apache.arrow.memory.BaseAllocator.wrapForeignAllocation(BaseAllocator.java:268)
	at xtdb.arrow.ArrowUtil.openArrowBufView(ArrowUtil.kt:160)
	at xtdb.arrow.ArrowUtil.openArrowBufView$default(ArrowUtil.kt:136)
	at xtdb.storage.RemoteBufferPool.uploadArrowFile(RemoteBufferPool.kt:104)
	at xtdb.storage.RemoteBufferPool.access$uploadArrowFile(RemoteBufferPool.kt:36)
	at xtdb.storage.RemoteBufferPool$openArrowWriter$1$1$1.end(RemoteBufferPool.kt:177)
	at xtdb.trie.DataFileWriter.end(DataFileWriter.kt:27)
	at xtdb.trie.PageTrieWriter.writePageTree(PageTrieWriter.kt:130)
	at xtdb.compactor.Compactor$Driver$Companion$real$1$create$1.executeJob(Compactor.kt:115)
	at xtdb.compactor.Compactor$Driver$Companion$real$1$create$1$executeJob$1.invokeSuspend(Compactor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```

```
2026-02-17T10:11:22.771725952Z ERROR xtdb.pgwire
Uncaught exception processing message
xtdb.error.Fault: Unable to allocate buffer of size 20159480 due to memory limit. Current allocation: 224921608
	at xtdb.error$fault.invokeStatic(error.clj:70)
	at xtdb.error$fault.invoke(error.clj:62)
	at xtdb.error$eval1042$fn__1043.invoke(error.clj:173)
	at xtdb.error$eval961$fn__962$G__952__969.invoke(error.clj:14)
	at xtdb.pgwire$send_ex.invokeStatic(pgwire.clj:276)
	at xtdb.pgwire$send_ex.invoke(pgwire.clj:270)
	at xtdb.pgwire$eval28782$fn__28784$fn__28787.invoke(pgwire.clj:679)
	at xtdb.pgwire$eval28782$fn__28784.invoke(pgwire.clj:673)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1702)
	at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1696)
	at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1749)
	at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1720)
	at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1795)
	at xtdb.pgwire$connect.invoke(pgwire.clj:1753)
	at xtdb.pgwire$accept_loop$fn__29505$fn__29506$fn__29507.invoke(pgwire.clj:1842)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.arrow.memory.OutOfMemoryException: Unable to allocate buffer of size 20159480 due to memory limit. Current allocation: 224921608
	at org.apache.arrow.memory.BaseAllocator.wrapForeignAllocation(BaseAllocator.java:268)
	at xtdb.cache.MemoryCache$FetchDone.handle(MemoryCache.kt:154)
	at xtdb.cache.MemoryCache$1.invokeSuspend(MemoryCache.kt:203)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
	Suppressed: java.lang.IllegalStateException: RefCnt has gone negative
		at org.apache.arrow.util.Preconditions.checkState(Preconditions.java:419)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:129)
		at org.apache.arrow.memory.BufferLedger.release(BufferLedger.java:105)
		at org.apache.arrow.memory.ArrowBuf.close(ArrowBuf.java:1032)
		at xtdb.arrow.ExtensibleBuffer.close(Buffers.kt:180)
		at xtdb.arrow.FixedWidthVector.close(FixedWidthVector.kt:248)
		at xtdb.util.IOUtilKt.closeAll(IOUtil.kt:31)
		at xtdb.arrow.RelationWriter.close(RelationWriter.kt:61)
		at xtdb.util$close.invokeStatic(util.clj:90)
		at xtdb.util$close.invoke(util.clj:73)
		at xtdb.node.impl$then_execute_prepared_query$fn__26064$fn__26065.invoke(impl.clj:69)
		at xtdb.node.impl$then_execute_prepared_query$fn__26064.invoke(impl.clj:69)
		at xtdb.node.impl$then_execute_prepared_query.invokeStatic(impl.clj:69)
		at xtdb.node.impl$then_execute_prepared_query.invoke(impl.clj:68)
		at xtdb.node.impl.Node.open_sql_query(impl.clj:197)
		at xtdb.node.impl$await_msg_result.invokeStatic(impl.clj:85)
		at xtdb.node.impl$await_msg_result.invoke(impl.clj:75)
		at xtdb.node.impl.Node.executeTx(impl.clj:172)
		at xtdb.pgwire$cmd_commit$fn__28720.invoke(pgwire.clj:576)
		at xtdb.pgwire$cmd_commit.invokeStatic(pgwire.clj:565)
		at xtdb.pgwire$cmd_commit.invoke(pgwire.clj:552)
		at xtdb.pgwire$eval28782$fn__28784$fn__28787.invoke(pgwire.clj:677)
		at xtdb.pgwire$eval28782$fn__28784.invoke(pgwire.clj:673)
		at clojure.lang.MultiFn.invoke(MultiFn.java:234)
		at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1702)
		at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1696)
		at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1749)
		at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1720)
		at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1795)
		at xtdb.pgwire$connect.invoke(pgwire.clj:1753)
		at xtdb.pgwire$accept_loop$fn__29505$fn__29506$fn__29507.invoke(pgwire.clj:1842)
		at clojure.lang.AFn.run(AFn.java:22)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by refset** [comment]
@egg-juxt sounds like yours may be a slightly different issue if the OOM was the trigger
