### ISSUE TITLE
pgwire should correctly return any DML errors synchronously

### ISSUE THREAD

**Issue by dekkers** [xtdb/crux#3563]
When an exception is thrown such as in #3562 there isn't a proper error message:

```
test=> INSERT INTO "test" ("_id", "date") VALUES (1, '2005-07-31 12:30:30'::timestamp);
INSERT 0 0
test=> 
```

**Comment by refset** [comment]
Thanks for opening the issue @dekkers - transaction processing in pgwire is fully asynchronous currently, but you should at least be able to inspect the error using `SELECT * FROM _txs ORDER BY _id`

**Comment by refset** [comment]
Noting that while #3562 remains unresolved it serves as a good example of the wider stray tx error/session lifecycle handling bug:

```
jdt=> INSERT INTO "test" ("_id", "date") VALUES (1, TIMESTAMP '2005-07-31T12:30:45');
INSERT 0 0
jdt=> UPDATE test SET "date" = '2005-07-31 12:30:30'::timestamp WHERE _id = 1;
UPDATE 0
jdt=> INSERT INTO "test" ("_id", "date") VALUES (2, TIMESTAMP '2005-07-31T12:30:45');
INSERT 0 0
jdt=> select * from test;
 _id |        date         
-----+---------------------
   2 | 2005-07-31 12:30:45
   1 | 2005-07-31 12:30:45
(2 rows)
jdt=> select * from _txs;
 _id  | committed |                                                                          error                                                                           |             tx_time              
------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------
 1365 | f         | {"error-key":"xtdb.expression\/invalid-temporal-string","message":"String '2005-07-31 12:30:30' has invalid format for type timestamp without timezone"} | 2024-08-06 11:21:20.789604+00:00
 2722 | t         |                                                                                                                                                          | 2024-08-06 11:21:36.804669+00:00
    0 | t         |                                                                                                                                                          | 2024-08-06 11:16:53.53091+00:00
(3 rows)
```

```
11:21:20 | DEBUG xtdb.indexer | aborted tx
xtdb.RuntimeException: String '2005-07-31 12:30:30' has invalid format for type timestamp without timezone
        at xtdb.error$runtime_err.invokeStatic(error.clj:21)
        at xtdb.error$runtime_err.invoke(error.clj:13)
        at xtdb.error$runtime_err.invokeStatic(error.clj:17)
        at xtdb.error$runtime_err.invoke(error.clj:13)
        at xtdb.expression.temporal$parse_with_error_handling.invokeStatic(temporal.clj:281)
        at xtdb.expression.temporal$parse_with_error_handling.invoke(temporal.clj:277)
        at clojure.core$eval34257$fn__34258.invoke(NO_SOURCE_FILE:0)
        at xtdb.expression$$reify__13915.project(expression.clj:1555)
        at xtdb.operator.project.ProjectCursor$reify__20819.accept(project.clj:124)
        at xtdb.operator.rename.RenameCursor$reify__21628.accept(rename.clj:39)
        at xtdb.operator.scan.TrieCursor$fn__19489.invoke(scan.clj:309)
        at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:260)
        at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:116)
        at xtdb.query$wrap_cursor$reify__25716.tryAdvance(query.clj:78)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at xtdb.indexer$query_indexer$eval_query__25954.invoke(indexer.clj:396)
        at xtdb.indexer$wrap_sql_args$fn__25961.invoke(indexer.clj:430)
        at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:413)
        at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
        at xtdb.indexer$$reify__25966.indexOp(indexer.clj:401)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019$fn__26032.invoke(indexer.clj:623)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019.invoke(indexer.clj:620)
        at xtdb.indexer.Indexer$fn__26016$fn__26040.invoke(indexer.clj:634)
        at xtdb.indexer.Indexer$fn__26016.invoke(indexer.clj:633)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:597)
        at xtdb.log.watcher$watch_log_BANG_$reify__26256.acceptRecord(watcher.clj:53)
        at xtdb.log$tx_handler$fn__17626.invoke(log.clj:37)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at xtdb.log.NotifyingSubscriberHandler$fn__17659.invoke(log.clj:96)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by refset** [comment]
Another test case:
```
jdt=> INSERT INTO tbl1 (_id, foo) VALUES ($1, $2);
INSERT 0 0
jdt=> SELECT * FROM _txs;
 _id | committed |                                                                          error                                                                          |             tx_time              
-----+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------
   0 | f         | {"param-count":2,"arg-count":0,"error-key":"xtdb.indexer\/incorrect-sql-arg-count","message":"0 arguments were provided and 2 arguments were provided"} | 2024-08-06 12:38:42.795969+00:00
(1 row)
```

```
12:38:42 | DEBUG xtdb.indexer | aborted tx
xtdb.RuntimeException: 0 arguments were provided and 2 arguments were provided
        at xtdb.error$runtime_err.invokeStatic(error.clj:21)
        at xtdb.error$runtime_err.invoke(error.clj:13)
        at xtdb.error$runtime_err.invokeStatic(error.clj:17)
        at xtdb.error$runtime_err.invoke(error.clj:13)
        at xtdb.indexer$wrap_sql_args$fn__25961.invoke(indexer.clj:426)
        at xtdb.indexer$foreach_arg_row.invokeStatic(indexer.clj:413)
        at xtdb.indexer$foreach_arg_row.invokePrim(indexer.clj)
        at xtdb.indexer$$reify__25966.indexOp(indexer.clj:401)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019$fn__26032.invoke(indexer.clj:623)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
        at xtdb.indexer.Indexer$fn__26016$index_tx_ops__26019.invoke(indexer.clj:620)
        at xtdb.indexer.Indexer$fn__26016$fn__26040.invoke(indexer.clj:634)
        at xtdb.indexer.Indexer$fn__26016.invoke(indexer.clj:633)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:597)
        at xtdb.log.watcher$watch_log_BANG_$reify__26256.acceptRecord(watcher.clj:53)
        at xtdb.log$tx_handler$fn__17626.invoke(log.clj:37)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6885)
        at clojure.core$reduce.invoke(core.clj:6868)
        at xtdb.log.NotifyingSubscriberHandler$fn__17659.invoke(log.clj:96)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by jarohen** [comment]
Cheers for raising this one @dekkers - will go into our next snapshot 🙂
