### ISSUE TITLE
Resource Temporarily Unavailable on Azure Benchmark

### ISSUE THREAD

**Issue by tggreene** [xtdb/crux#3564]
We're seeing a `java.nio.file.FileSystemException: Resource Temporarily Unavailable` thrown after several hours running auctionmark on azure with the following configuration:
 - Local txlog
 - Azure object storage
 - Single Node
 - 24H Run with 0.01 scale factor
 - Azure File Share mounted on /var/lib/xtdb

```
23:56:37.208 [core2-benchmark-pool-12-thread-2] ERROR xtdb.bench - Error while executing xtdb.bench.auctionmark$index_item_status_groups@70adf86d
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: Ingestion stopped: java.nio.file.FileSystemException: /var/lib/xtdb/disk-cache/cache-1/tables/item/data/log-l01-fr512c10f-nr5258216-rs413b1.arrow: Resource temporarily unavailable {}
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at clojure.core$deref_future.invokeStatic(core.clj:2317)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at xtdb.indexer.Indexer.awaitTx(indexer.clj:568)
        at xtdb.node.impl.Node.prepareQuery(impl.clj:140)
        at xtdb.node.impl.Node.open_xtql_query(impl.clj:120)
        at xtdb.api$plan_q$reify__7739.reduce(api.clj:82)
        at clojure.core$reduce.invokeStatic(core.clj:6885)
        at clojure.core$run_BANG_.invokeStatic(core.clj:7778)
        at clojure.core$run_BANG_.invoke(core.clj:7778)
        at xtdb.bench.auctionmark$item_status_groups.invokeStatic(auctionmark.clj:434)
        at xtdb.bench.auctionmark$item_status_groups.invoke(auctionmark.clj:429)
        at xtdb.bench.auctionmark$index_item_status_groups.invokeStatic(auctionmark.clj:465)
        at xtdb.bench.auctionmark$index_item_status_groups.invoke(auctionmark.clj:462)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at xtdb.bench$wrap_in_catch$fn__5962.doInvoke(bench.clj:19)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at xtdb.bench.measurement$wrap_transaction$instrumented_transaction__8123$fn__8124.invoke(measurement.clj:32)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
        at xtdb.bench.measurement$wrap_transaction$instrumented_transaction__8123.invoke(measurement.clj:32)
        at xtdb.bench$compile_benchmark$compile_task__6075$run_freq_job__6100.invoke(bench.clj:291)
        at xtdb.bench$compile_benchmark$compile_task__6075$start_thread__6116$fn__6117.invoke(bench.clj:260)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by tggreene** [comment]
Working on a possible solution for this here: https://github.com/tggreene/xtdb/tree/retry-file-channel

**Comment by tggreene** [comment]
I think we can close this as it appears to be quite specific to this type of storage (azure, file share).
