### ISSUE TITLE
AtomicMoveNotSupportedException during live trie writer

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3566]
```09:35:21 | DEBUG xtdb.pgwire | Error on execute-tx
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: Ingestion stopped: /tmp/buffer-pool-tmp-dir10717814171995985226/upload17145298293499960592.arrow -> /var/lib/xtdb/buffers/v03/tables/docs/data/log-l00-fr00-nr419308-rs19089.arrow: Invalid cross-device link {}
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at clojure.core$deref_future.invokeStatic(core.clj:2317)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at xtdb.indexer.Indexer.awaitTx(indexer.clj:568)
        at xtdb.node.impl.Node.prepareQuery(impl.clj:133)
        at xtdb.node.impl.Node.open_sql_query(impl.clj:115)
        at xtdb.node.impl.Node.execute_tx(impl.clj:105)
        at xtdb.api$execute_tx.invokeStatic(api.clj:208)
        at xtdb.api$execute_tx.invoke(api.clj:180)
        at xtdb.pgwire$execute_tx.invokeStatic(pgwire.clj:1077)
        at xtdb.pgwire$execute_tx.invoke(pgwire.clj:1072)
        at xtdb.pgwire$cmd_exec_dml.invokeStatic(pgwire.clj:1109)
        at xtdb.pgwire$cmd_exec_dml.invoke(pgwire.clj:1095)
        at xtdb.pgwire$cmd_execute.invokeStatic(pgwire.clj:1437)
        at xtdb.pgwire$cmd_execute.invoke(pgwire.clj:1418)
        at xtdb.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1467)
        at xtdb.pgwire$cmd_simple_query.invoke(pgwire.clj:1442)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1494)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1475)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1561)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1514)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1597)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1564)
        at xtdb.pgwire$accept_loop$fn__34137$fn__34138$fn__34139.invoke(pgwire.clj:1652)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: clojure.lang.ExceptionInfo: Ingestion stopped: /tmp/buffer-pool-tmp-dir10717814171995985226/upload17145298293499960592.arrow -> /var/lib/xtdb/buffers/v03/tables/docs/data/log-l00-fr00-nr419308-rs19089.arrow: Invalid cross-device link
        at xtdb.await$__GT_ingester_ex.invokeStatic(await.clj:18)
        at xtdb.await$__GT_ingester_ex.invoke(await.clj:17)
        at xtdb.await$await_tx_async$fn__9262.invoke(await.clj:31)
        at xtdb.await$await_tx_async.invokeStatic(await.clj:26)
        at xtdb.await$await_tx_async.invoke(await.clj:22)
        at xtdb.indexer.Indexer.awaitTx(indexer.clj:679)
        ... 26 common frames omitted
Caused by: java.nio.file.AtomicMoveNotSupportedException: /tmp/buffer-pool-tmp-dir10717814171995985226/upload17145298293499960592.arrow -> /var/lib/xtdb/buffers/v03/tables/docs/data/log-l00-fr00-nr419308-rs19089.arrow: Invalid cross-device link
        at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:871)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
        at java.base/java.nio.file.Files.move(Files.java:1430)
        at xtdb.util$atomic_move.invokeStatic(util.clj:298)
        at xtdb.util$atomic_move.invoke(util.clj:297)
        at xtdb.buffer_pool.LocalBufferPool$reify__9467.end(buffer_pool.clj:221)
        at xtdb.trie$open_trie_writer$reify__16844.end(trie.clj:194)
        at xtdb.trie$write_live_trie_BANG_$fn__16895.invoke(trie.clj:243)
        at xtdb.trie$write_live_trie_BANG_.invokeStatic(trie.clj:235)
        at xtdb.trie$write_live_trie_BANG_.invoke(trie.clj:232)
        at xtdb.indexer.live_index.LiveTable$fn__17468.invoke(live_index.clj:186)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

This occurred after ~76930 rows were inserted using the following (ChatGPT-generated) script:
```
#!/bin/bash

# Replace with your database connection details
DB_NAME="your_database"

# Initialize id counter
_id=1

while true; do
  SQL="INSERT INTO docs (_id, foo) VALUES"
  
  # Loop to generate 1000 rows
  for i in $(seq 1 1000); do
    # Generate a random value type (1 = int, 2 = float, 3 = utf8, 4 = NULL)
    VAL_TYPE=$(( ( RANDOM % 4 ) + 1 ))

    # Initialize _foo variable
    _foo=""

    case $VAL_TYPE in
      1)
        # Generate a random integer
        _foo=$(( RANDOM % 100 ))
        SQL+=" ($_id, $_foo)"
        ;;
      2)
        # Generate a random float
        _foo=$(printf "%.6f" "$(echo "scale=6; $RANDOM/32767 * 100" | bc)")
        SQL+=" ($_id, $_foo)"
        ;;
      3)
        # Generate a random utf8 string (3 random characters)
        _foo=$(head /dev/urandom | tr -dc A-Za-z | head -c 3 ; echo '')
        SQL+=" ($_id, '$_foo')"
        ;;
      4)
        # Set foo to NULL
        _foo="NULL"
        SQL+=" ($_id, NULL)"
        ;;
    esac

    # Add a comma if not the last entry
    if [ $i -lt 1000 ]; then
      SQL+=","
    fi

    # Increment the id
    _id=$((_id + 1))
  done
  
  SQL+=";"

  # Execute the SQL statement using psql
  psql -h localhost -p 5432 -d $DB_NAME -c "$SQL"

  # Sleep for a short period to avoid overwhelming the database
  sleep 1
done
```

Using `docker run -it --pull=always -p 6548:3000 -p 5432:5432 ghcr.io/xtdb/xtdb-standalone-ea:latest` on Arch.

**Comment by refset** [comment]
I also observed something similar looking in another context - here I was not trying to insert much data, just working on a small repro for [this](https://github.com/xtdb/xtdb/issues/3572) and I left the node running for a while without any activity, then came back later and spotted:
```
16:38:29 | INFO  xtdb.stagnant-log-flusher | last chunk tx-id null, flushing any pending writes
16:38:29 | DEBUG xtdb.log.watcher | received flush-chunk signal: -1
16:38:29 | ERROR xtdb.util | Uncaught exception:
java.nio.file.AtomicMoveNotSupportedException: /tmp/buffer-pool-tmp-dir17299553459292300519/upload6029787683351082808.arrow -> /var/lib/xtdb/buffers/v03/tables/xt$txs/data/log-l00-fr00-nr06-rs6.arrow: Invalid cross-device link
        at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:871)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
        at java.base/java.nio.file.Files.move(Files.java:1430)
        at xtdb.util$atomic_move.invokeStatic(util.clj:298)
        at xtdb.util$atomic_move.invoke(util.clj:297)
        at xtdb.buffer_pool.LocalBufferPool$reify__9467.end(buffer_pool.clj:221)
        at xtdb.trie$open_trie_writer$reify__16844.end(trie.clj:194)
        at xtdb.trie$write_live_trie_BANG_$fn__16895.invoke(trie.clj:243)
        at xtdb.trie$write_live_trie_BANG_.invokeStatic(trie.clj:235)
        at xtdb.trie$write_live_trie_BANG_.invoke(trie.clj:232)
        at xtdb.indexer.live_index.LiveTable$fn__17468.invoke(live_index.clj:186)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by FiV0** [comment]
Faulty commit https://github.com/xtdb/xtdb/commit/5514c22d3b3380ac39bf37dd4d868f61a0d6feb7

**Comment by FiV0** [comment]
Fixed in https://github.com/xtdb/xtdb/commit/3add7a3de50ef88c99eaaf5890e99521ab791a5f
