### ISSUE TITLE
pgwire string parameters should be usable from Python via Psycopg 3

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3589]
EDIT: new minimum repro - blocked by https://github.com/xtdb/xtdb/issues/3411

Reproduce as follows...

```
python3 -m pip install "psycopg[binary]"
```

script.py:
```python
import psycopg as pg

conn_str = 'user=admin password=quest host=127.0.0.1 port=5432 dbname=qdb'
with pg.connect(conn_str, autocommit=True) as connection:

    # connection.adapters.register_dumper(str, pg.types.string.StrDumperVarchar) # this is a workaround

    with connection.cursor() as cur:

        for x in range(10):

            cur.execute('''
                INSERT INTO test_pg (_id, name)
                    VALUES (%s::INTEGER, %s::VARCHAR);
        ''',
                (x, str(x)))

        #Query the database and obtain data as Python objects.

        cur.execute('SELECT * FROM test_pg;')
        records = cur.fetchall()
        for row in records:
            print(row)
```

Run using `python script.py`

Output:
```
Traceback (most recent call last):
  File "/home/jdt/python-psycopg-test/string-param-test.py", line 24, in <module>
    cur.execute('''
  File "/home/jdt/python-psycopg-test/foo/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.ProtocolViolation: Missing types for params - Client must specify types for all params in DML statements

```

**Comment by refset** [comment]
Following @mbutlerw's change in https://github.com/xtdb/xtdb/commit/0c0010e9f860197230ecbd43a3de0e6aa25b4ac7#diff-1a8ccbf1b5d5b6dd1cb8a2c0200c29a783994c1c1e59b78d8aa82e0e6f3f6003R1592 - the code above now errors intentionally with "Missing types for params"

However note there's an "Uncaught exception"/NPE logged on the server:
```
16:18:03 | ERROR xtdb.pgwire | Missing types for params in DML statement
16:18:03 | ERROR xtdb.pgwire | Uncaught exception in handle-msg
java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object, Object)" because "read_text" is null
        at xtdb.pgwire$__GT_xtify_param$xtify_param__34005.invoke(pgwire.clj:1095)
        at clojure.core$map_indexed$mapi__8676$fn__8677.invoke(core.clj:7500)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
        at clojure.core$vec.invokeStatic(core.clj:379)
        at clojure.core$vec.invoke(core.clj:369)
        at xtdb.pgwire$cmd_exec_dml.invokeStatic(pgwire.clj:1107)
        at xtdb.pgwire$cmd_exec_dml.invoke(pgwire.clj:1097)
        at xtdb.pgwire$cmd_execute.invokeStatic(pgwire.clj:1472)
        at xtdb.pgwire$cmd_execute.invoke(pgwire.clj:1452)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1535)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1510)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1596)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1549)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1632)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1599)
        at xtdb.pgwire$accept_loop$fn__34233$fn__34234$fn__34235.invoke(pgwire.clj:1687)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by refset** [comment]
As a satisfactory workaround (vs. attempting any upstream changes to psycopg), strings can now be used ~normally by simply configuring to use the varchar OID code path instead, using `connection.adapters.register_dumper(str, pg.types.string.StrDumperVarchar)`

Note also that other types like numbers and datetimes seem to translate back and forth just fine now.

**Comment by jarohen** [comment]
let's write this up as a test in our Python test-harness

**Comment by refset** [comment]
Related bug, attempting to writing a boolean `True` will (silently) result in:
```
java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object, Object)" because "read_binary" is null
        at xtdb.pgwire$__GT_xtify_param$xtify_param__34005.invoke(pgwire.clj:1094)
        at clojure.core$map_indexed$mapi__8676$fn__8677.invoke(core.clj:7500)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
        at clojure.core$vec.invokeStatic(core.clj:379)
        at clojure.core$vec.invoke(core.clj:369)
        at xtdb.pgwire$cmd_exec_dml.invokeStatic(pgwire.clj:1107)
        at xtdb.pgwire$cmd_exec_dml.invoke(pgwire.clj:1097)
        at xtdb.pgwire$cmd_execute.invokeStatic(pgwire.clj:1472)
        at xtdb.pgwire$cmd_execute.invoke(pgwire.clj:1452)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1535)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1510)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1596)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1549)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1632)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1599)
        at xtdb.pgwire$accept_loop$fn__34233$fn__34234$fn__34235.invoke(pgwire.clj:1687)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

Attempting to workaround by avoiding the BoolBinaryDumper using `connection.adapters.register_dumper(bool, pg.types.bool.BoolDumper)` always inserts `false`.

Also, possibly related to this (suggesting it's not a Python-specific issue) - with postgres.js and the following default type mapping I also only observe `false` being inserted:
```
  boolean: {
    to: 16,
    from: 16,
    serialize: x => x === true ? 't' : 'f',
    parse: x => x === 't'
  },
```

...on the other hand JDBC seems to handle `true` just fine: https://github.com/xtdb/xtdb/blob/4e116da6952a2913a38120f7b21176bb0a94e856/src/test/clojure/xtdb/pgwire_test.clj#L1297

**Comment by FiV0** [comment]
https://github.com/xtdb/xtdb/pull/3747 solves the issue from the top of the card.

**Comment by FiV0** [comment]
The boolean issue should be fixed in 7091ce40565a70bfeffa7eb691163445bec0c462, if I correctly understood your issue.

**Comment by FiV0** [comment]
Solution from #3411 favoured instead of #3747.

**Comment by jarohen** [comment]
@refset, @FiV0 can we get the card title/description updated to the current state of this issue? cheers :) 🙏

**Comment by refset** [comment]
@jarohen done - also noted the workaround in the example. I believe it's simply now the ~same issue as with attempting to use Node's `pg`, where no type info is being explicitly provided by the driver - the current preferred resolution being https://github.com/xtdb/xtdb/issues/3411 (IIUC)

Meta: might be faster to diagnose and resolve in future if we land the test harness work https://github.com/xtdb/xtdb/pull/3741

True/False definitely now work fine :slightly_smiling_face:

**Comment by jarohen** [comment]
righto, cheers mate :pray: will close this one as done, and link your new repro on the other card
