### ISSUE TITLE
Support xtdb.types.ZonedDateTimeRange in pgwire

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3681]
With the following query:
```sql
INSERT INTO docs (_id, foo) VALUES (1, 'bar');

SELECT _valid_time FROM docs;
```

I got the following exception thrown:
```
java.lang.Exception: Unexpected type encountered by pgwire (class xtdb.types.ZonedDateTimeRange)
        at xtdb.pgwire$json_clj.invokeStatic(pgwire.clj:463)
        at xtdb.pgwire$json_clj.invoke(pgwire.clj:384)
        at clojure.core$comp$fn__5893.invoke(core.clj:2586)
        at xtdb.pgwire$write_json.invokeStatic(pgwire.clj:986)
        at xtdb.pgwire$write_json.invoke(pgwire.clj:985)
        at xtdb.pgwire$cmd_send_query_result$reify__34458$fn__34460.invoke(pgwire.clj:1025)
        at clojure.core$map_indexed$mapi__8676$fn__8677.invoke(core.clj:7500)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.lang.RT.countFrom(RT.java:670)
        at clojure.lang.RT.count(RT.java:663)
        at xtdb.pgwire$io_list$fn__34065.invoke(pgwire.clj:541)
        at xtdb.pgwire$io_record$write_record__34076.invoke(pgwire.clj:586)
        at xtdb.pgwire$cmd_write_msg.invokeStatic(pgwire.clj:793)
        at xtdb.pgwire$cmd_write_msg.invoke(pgwire.clj:781)
        at xtdb.pgwire$cmd_send_query_result$reify__34458.accept(pgwire.clj:1027)
        at xtdb.operator.project.ProjectCursor$reify__23710.accept(project.clj:133)
        at xtdb.operator.rename.RenameCursor$reify__24503.accept(rename.clj:39)
        at xtdb.operator.scan.TrieCursor$fn__22253.invoke(scan.clj:293)
        at xtdb.operator.scan.TrieCursor.tryAdvance(scan.clj:244)
        at xtdb.operator.rename.RenameCursor.tryAdvance(rename.clj:29)
        at xtdb.operator.project.ProjectCursor.tryAdvance(project.clj:119)
        at xtdb.query$wrap_cursor$reify__26233.tryAdvance(query.clj:80)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at xtdb.pgwire$cmd_send_query_result.invokeStatic(pgwire.clj:996)
        at xtdb.pgwire$cmd_send_query_result.invoke(pgwire.clj:988)
        at xtdb.pgwire$cmd_exec_query.invokeStatic(pgwire.clj:1140)
        at xtdb.pgwire$cmd_exec_query.invoke(pgwire.clj:1123)
        at xtdb.pgwire$cmd_execute.invokeStatic(pgwire.clj:1489)
        at xtdb.pgwire$cmd_execute.invoke(pgwire.clj:1470)
        at xtdb.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1518)
        at xtdb.pgwire$cmd_simple_query.invoke(pgwire.clj:1495)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1545)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1526)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1608)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1564)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1649)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1611)
        at xtdb.pgwire$accept_loop$fn__34708$fn__34709$fn__34710.invoke(pgwire.clj:1704)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by jarohen** [comment]
thanks @Akeboshiwind - think this is #3652?
