### ISSUE TITLE
`INSERT INTO docs VALUES (1, 'bar')` crashes indexer

### ISSUE THREAD

**Issue by FiV0** [xtdb/crux#3752]
The insert statement from the title crashes the indexer.

`visitInsertValues` expects a `columnNameList` to be present on the ctx

```
10:16:05.309 [xtdb-tx-subscription-pool-25-thread-23] ERROR xtdb.indexer - error in indexer
java.lang.NullPointerException: Cannot invoke "xtdb.antlr.Sql$ColumnNameListContext.columnName()" because the return value of "xtdb.antlr.Sql$InsertValuesContext.columnNameList()" is null
	at xtdb.sql.plan.QueryPlanVisitor.visitInsertValues(plan.clj:2340)
	at xtdb.antlr.Sql$InsertValuesContext.accept(Sql.java:18004)
	at xtdb.sql.plan.StmtVisitor.visitInsertStatement(plan.clj:2506)
	at xtdb.antlr.Sql$InsertStatementContext.accept(Sql.java:17902)
	at xtdb.sql.plan.StmtVisitor.visitInsertStmt(plan.clj:2502)
	at xtdb.antlr.Sql$InsertStmtContext.accept(Sql.java:516)
	at xtdb.sql.plan.StmtVisitor.visitDirectSqlStatement(plan.clj:2477)
	at xtdb.antlr.Sql$DirectSqlStatementContext.accept(Sql.java:374)
	at xtdb.sql.plan$plan_statement.invokeStatic(plan.clj:2799)
	at xtdb.sql.plan$plan_statement.invoke(plan.clj:2782)
	at xtdb.sql$compile_query__86791.invoke(sql.clj:10)
	at xtdb.util$lru_memoize$fn__69074.invoke(util.clj:555)
	at xtdb.indexer$$reify__88362$fn__88363.invoke(indexer.clj:446)
	at xtdb.indexer$$reify__88362.indexOp(indexer.clj:444)
	at xtdb.indexer.Indexer$fn__88425$index_tx_ops__88430$fn__88443.invoke(indexer.clj:621)
	at clojure.lang.AFn.call(AFn.java:18)
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175)
	at xtdb.indexer.Indexer$fn__88425$index_tx_ops__88430.invoke(indexer.clj:618)
	at xtdb.indexer.Indexer$fn__88425$fn__88451.invoke(indexer.clj:632)
	at xtdb.indexer.Indexer$fn__88425.invoke(indexer.clj:631)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:593)
	at xtdb.log.watcher$watch_log_BANG_$reify__89707.accept(watcher.clj:55)
	at xtdb.log$tx_handler$fn__85360.invoke(log.clj:38)
	at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
	at clojure.core.protocols$fn__8252.invokeStatic(protocols.clj:74)
	at clojure.core.protocols$fn__8252.invoke(protocols.clj:74)
	at clojure.core.protocols$fn__8199$G__8194__8212.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6965)
	at clojure.core$reduce.invoke(core.clj:6947)
	at xtdb.log.NotifyingSubscriberHandler$fn__85393.invoke(log.clj:97)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by FiV0** [comment]
Erroring in the indexer for now. If we want to add erroring pre-submit this also affects other errors and should get its own ticket.
