### ISSUE TITLE
Metabase Enterprise - Failing queries when syncing database schema

### ISSUE THREAD

**Issue by egg-juxt** [xtdb/crux#3771]
### Substring

There are several queries that fail because of  SUBSTRING arguments:

```
SELECT SUBSTRING("public"."system"."orchestration_system_id", 1, 1234) AS "substring4077", SUBSTRING("public"."system"."nmi", 1, 1234) AS "substring4078", SUBSTRING("public"."system"."orchestration_system", 1, 1234) AS "substring4079", SUBSTRING("public"."system"."_id", 1, 1234) AS "substring4080" FROM "public"."system" LIMIT 10000
```

with error:

```
xtdb.IllegalArgumentException: Errors parsing SQL statement:
  - line 2:60 no viable alternative at input 'SUBSTRING("public"."system"."orchestration_system_id",'
        at xtdb.error$illegal_arg.invokeStatic(error.clj:11)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.error$illegal_arg.invokeStatic(error.clj:7)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.sql.plan$add_throwing_error_listener$fn__22295.invoke(plan.clj:2692)
        at xtdb.sql.plan.proxy$org.antlr.v4.runtime.BaseErrorListener$ff19274a.syntaxError(Unknown Source)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
        at xtdb.antlr.Sql.selectList(Sql.java:14330)
        at xtdb.antlr.Sql.selectClause(Sql.java:14067)
[...]
```

The SQL standard substring function (already supported by XTDB) currently only accepts `FROM start FOR length` syntax.

## pg_get_indexdef?

Query:
```
SELECT     tmp.TABLE_CAT,     tmp.TABLE_SCHEM,     tmp.TABLE_NAME,     tmp.NON_UNIQUE,     tmp.INDEX_QUALIFIER,     tmp.INDEX_NAME,     tmp.TYPE,     tmp.ORDINAL_POSITION,     trim(both '"' from pg_catalog.pg_get_indexdef(tmp.CI_OID, tmp.ORDINAL_POSITION, false)) AS COLUMN_NAME,   CASE tmp.AM_NAME     WHEN 'btree' THEN CASE tmp.I_INDOPTION[tmp.ORDINAL_POSITION - 1] & 1::smallint       WHEN 1 THEN 'D'       ELSE 'A'     END     ELSE NULL   END AS ASC_OR_DESC,     tmp.CARDINALITY,     tmp.PAGES,     tmp.FILTER_CONDITION FROM (SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM,   ct.relname AS TABLE_NAME, NOT i.indisunique AS NON_UNIQUE,   NULL AS INDEX_QUALIFIER, ci.relname AS INDEX_NAME,   CASE i.indisclustered     WHEN true THEN 1    ELSE CASE am.amname       WHEN 'hash' THEN 2      ELSE 3    END   END AS TYPE,   (information_schema._pg_expandarray(i.indkey)).n AS ORDINAL_POSITION,   ci.reltuples AS CARDINALITY,   ci.relpages AS PAGES,   pg_catalog.pg_get_expr(i.indpred, i.indrelid) AS FILTER_CONDITION,   ci.oid AS CI_OID,   i.indoption AS I_INDOPTION,   am.amname AS AM_NAME FROM pg_catalog.pg_class ct   JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)   JOIN pg_catalog.pg_index i ON (ct.oid = i.indrelid)   JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid)   JOIN pg_catalog.pg_am am ON (ci.relam = am.oid) WHERE true  AND n.nspname = E'public' AND ct.relname = E'device_model') AS tmp ORDER BY NON_UNIQUE, TYPE, INDEX_NAME, ORDINAL_POSITION
```

error:

```
Errors parsing SQL statement:
  - line 1:221 no viable alternative at input 'tmp.TABLE_CAT,tmp.TABLE_SCHEM,tmp.TABLE_NAME,tmp.NON_UNIQUE,tmp.INDEX_QUALIFIER,tmp.INDEX_NAME,tmp.TYPE,tmp.ORDINAL_POSITION,trim(both'"'frompg_catalog.pg_get_indexdef('
        at xtdb.error$illegal_arg.invokeStatic(error.clj:11)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.error$illegal_arg.invokeStatic(error.clj:7)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.sql.plan$add_throwing_error_listener$fn__22295.invoke(plan.clj:2692)
        at xtdb.sql.plan.proxy$org.antlr.v4.runtime.BaseErrorListener$ff19274a.syntaxError(Unknown Source)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
        at xtdb.antlr.Sql.selectList(Sql.java:14330)
        at xtdb.antlr.Sql.selectClause(Sql.java:14067)
[...]
```

This should be okay to support as a no-op function since there is no index information to return currently

**Comment by FiV0** [comment]
Fixed in https://github.com/xtdb/xtdb/compare/3f0cf1f4973cc382d3bd6f51e3325be97497d968...c641edff692b044f99d3c76f2ddc99d323cf5ddc
