### ISSUE TITLE
xtdb.pgwire `error on conn startup`

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3858]
Enabled trace logs to get:

```
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 R, :name :msg-auth}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 S, :name :msg-parameter-status}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 K, :name :msg-backend-key-data}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 Z, :name :msg-ready}
13:20:54 | TRACE xtdb.pgwire | Starting connection loop {:port 5432, :cid 1}
13:20:54 | TRACE xtdb.pgwire | Read client msg {:cid 1, :msg {:stmt-name u1etbd5ab3c1, :query INSERT INTO "xxx" RECORDS $1, :param-oids [16384], :msg-name :msg-parse}}
13:20:54 | DEBUG xtdb.pgwire | Interpreting SQL:  INSERT INTO "xxx" RECORDS $1
13:20:54 | TRACE xtdb.pgwire | Writing server message {:char8 1, :name :msg-parse-complete}
13:20:54 | TRACE xtdb.pgwire | Read client msg {:cid 1, :msg {:describe-type :prepared-stmt, :describe-name u1etbd5ab3c1, :msg-name :msg-describe}}
13:20:54 | TRACE xtdb.pgwire | sending parameter description -  {:param-fields ({:typname transit, :oid 16384, :typsend transit_send, :typreceive transit_recv, :read-text #object[xtdb.types$fn__6092 0x782dd54e xtdb.types$fn__6092@782dd54e], :read-binary #object[xtdb.types$fn__6094 0x5f783984 xtdb.types$fn__6094@5f783984], :write-text #object[xtdb.types$fn__6096 0x611568fd xtdb.types$fn__6096@611568fd], :write-binary #object[xtdb.types$fn__6098 0xe0c6b04 xtdb.types$fn__6098@e0c6b04]})}
13:20:54 | TRACE xtdb.pgwire | Writing server message (with body) {:char8 t, :name :msg-parameter-description}
13:20:54 | TRACE xtdb.pgwire | Writing server message {:char8 n, :name :msg-no-data}
13:20:54 | TRACE xtdb.pgwire | Read client msg {:cid 1, :msg {:msg-name :msg-flush}}
13:20:54 | TRACE xtdb.pgwire | Read client msg {:cid 1, :msg {:portal-name , :stmt-name u1etbd5ab3c1, :param-format [], :params [#object[[B 0x4c2f240b [B@4c2f240b]], :result-format [], :msg-name :msg-bind}}
13:20:54 | TRACE xtdb.pgwire | Writing server message {:char8 2, :name :msg-bind-complete}
13:20:54 | TRACE xtdb.pgwire | Read client msg {:cid 1, :msg {:portal-name , :limit 0, :msg-name :msg-execute}}
13:21:01 | WARN  xtdb.pgwire | error on conn startup
java.io.EOFException: null
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:210)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:385)
	at xtdb.pgwire$read_untyped_msg.invokeStatic(pgwire.clj:1037)
	at xtdb.pgwire$read_untyped_msg.invoke(pgwire.clj:1036)
	at xtdb.pgwire$read_version.invokeStatic(pgwire.clj:1043)
	at xtdb.pgwire$read_version.invoke(pgwire.clj:1042)
	at xtdb.pgwire$cmd_startup.invokeStatic(pgwire.clj:1073)
	at xtdb.pgwire$cmd_startup.invoke(pgwire.clj:1071)
	at xtdb.pgwire$connect$fn__29038.invoke(pgwire.clj:1627)
	at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1615)
	at xtdb.pgwire$connect.invoke(pgwire.clj:1606)
	at xtdb.pgwire$accept_loop$fn__29056$fn__29057$fn__29058.invoke(pgwire.clj:1681)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
13:21:10 | WARN  xtdb.pgwire | error on conn startup
java.io.EOFException: null
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:210)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:385)
	at xtdb.pgwire$read_untyped_msg.invokeStatic(pgwire.clj:1037)
	at xtdb.pgwire$read_untyped_msg.invoke(pgwire.clj:1036)
	at xtdb.pgwire$read_version.invokeStatic(pgwire.clj:1043)
	at xtdb.pgwire$read_version.invoke(pgwire.clj:1042)
	at xtdb.pgwire$cmd_startup.invokeStatic(pgwire.clj:1073)
	at xtdb.pgwire$cmd_startup.invoke(pgwire.clj:1071)
	at xtdb.pgwire$connect$fn__29038.invoke(pgwire.clj:1627)
	at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1615)
	at xtdb.pgwire$connect.invoke(pgwire.clj:1606)
	at xtdb.pgwire$accept_loop$fn__29056$fn__29057$fn__29058.invoke(pgwire.clj:1681)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Akeboshiwind** [comment]
Tried setting up metabase like below, but **wasn't** able to replicate this issue.

<details><summary>docker-compose.yml</summary>

```yaml
services:

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword

  xtdb:
    image: ghcr.io/xtdb/xtdb:latest
    container_name: xtdb
    hostname: xtdb
```

</details>

We have a number of other connections to the database using the [npm postges library](https://www.npmjs.com/package/postgres).

**Comment by Akeboshiwind** [comment]
**Wasn't** able to reproduce with:


Steps:
1. `mkdir my-test && cd my-test`
2. `npm init -y`
3. `npm install postgres`
4. Create the below file
5. `node index.js`

<details><summary>index.js</summary>

```js
import postgres from 'postgres'
import crypto from 'crypto';

const sql = postgres({
    host: "localhost",
    port: 5432,
    username: "xtdb",
    password: "xtdb",
    database: "xtdb",
    fetch_types: false, // currently required https://github.com/xtdb/xtdb/issues/3607
  types: {
    int: {
        to: 20,
        from: [23, 20], // int4, int8
        parse: parseInt
    }
  }
})

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

function new_id() {
    return crypto.randomBytes(16).readUInt32LE();
}

while (true) {
    console.log("Inserting");
    await sql`INSERT INTO docs (_id, value) VALUES (${sql.typed.int(new_id())}, ${sql.typed.int(new_id())})`

    console.log("Querying");
    await sql`SELECT * FROM docs LIMIT 1`

    console.log("Sleeping");
    await sleep(1000)
}
```

</details>
