### ISSUE TITLE
INSERT with transit parameter causes unexpected error

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3907]
The following has been reported by a user. I haven't successfully confirmed the repro yet (...stumped on ` java.lang.Exception: namespace 'xtdb.next.jdbc' not found` and have to park it for the moment).

JDBC error:
```
#error {:cause "ERROR: unexpected error on tx submit (report as a bug)"
        :via
        [{:type org.postgresql.util.PSQLException
          :message "ERROR: unexpected error on tx submit (report as a bug)"
          :at [org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2733]}]
        :trace
        [[org.postgresql.core.v3.QueryExecutorImpl receiveErrorResponse "QueryExecutorImpl.java" 2733]
         [org.postgresql.core.v3.QueryExecutorImpl processResults "QueryExecutorImpl.java" 2420]
         [org.postgresql.core.v3.QueryExecutorImpl execute "QueryExecutorImpl.java" 372]
         [org.postgresql.jdbc.PgStatement executeInternal "PgStatement.java" 517]
         [org.postgresql.jdbc.PgStatement execute "PgStatement.java" 434]
         [org.postgresql.jdbc.PgPreparedStatement executeWithFlags "PgPreparedStatement.java" 194]
         [org.postgresql.jdbc.PgPreparedStatement execute "PgPreparedStatement.java" 180]
         [next.jdbc.result_set$stmt__GT_result_set invokeStatic "result_set.clj" 667]
         [next.jdbc.result_set$stmt__GT_result_set invoke "result_set.clj" 662]
         [next.jdbc.result_set$eval2258$fn__2266 invoke "result_set.clj" 895]
         [next.jdbc.protocols$eval1330$fn__1346$G__1321__1355 invoke "protocols.clj" 34]
         [next.jdbc$execute_BANG_ invokeStatic "jdbc.clj" 257]
         [next.jdbc$execute_BANG_ invoke "jdbc.clj" 241]
         [xtdb_demo.core$jdbc_insert_records invokeStatic "core.clj" 312]
         [xtdb_demo.core$jdbc_insert_records invoke "core.clj" 311]
         [xtdb_demo.core$eval50825 invokeStatic "form-init17406523132236897824.clj" 317]
         [xtdb_demo.core$eval50825 invoke "form-init17406523132236897824.clj" 316]
         [clojure.lang.Compiler eval "Compiler.java" 7700]
         [clojure.lang.Compiler eval "Compiler.java" 7655]
         [clojure.core$eval invokeStatic "core.clj" 3232]
         [clojure.core$eval invoke "core.clj" 3228]
         [nrepl.middleware.interruptible_eval$evaluate$fn__41258$fn__41259 invoke "interruptible_eval.clj" 87]
         [clojure.lang.AFn applyToHelper "AFn.java" 152]
         [clojure.lang.AFn applyTo "AFn.java" 144]
         [clojure.core$apply invokeStatic "core.clj" 667]
         [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1990]
         [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1990]
         [clojure.lang.RestFn invoke "RestFn.java" 428]
         [nrepl.middleware.interruptible_eval$evaluate$fn__41258 invoke "interruptible_eval.clj" 87]
         [clojure.main$repl$read_eval_print__9244$fn__9247 invoke "main.clj" 437]
         [clojure.main$repl$read_eval_print__9244 invoke "main.clj" 437]
         [clojure.main$repl$fn__9253 invoke "main.clj" 459]
         [clojure.main$repl invokeStatic "main.clj" 459]
         [clojure.main$repl doInvoke "main.clj" 368]
         [clojure.lang.RestFn invoke "RestFn.java" 1526]
         [nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 84]
         [nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 56]
         [nrepl.middleware.interruptible_eval$interruptible_eval$fn__41291$fn__41295 invoke "interruptible_eval.clj" 152]
         [clojure.lang.AFn run "AFn.java" 22]
         [nrepl.middleware.session$session_exec$main_loop__41361$fn__41365 invoke "session.clj" 218]
         [nrepl.middleware.session$session_exec$main_loop__41361 invoke "session.clj" 217]
         [clojure.lang.AFn run "AFn.java" 22]
         [java.lang.Thread run "Thread.java" 1570]]}
```

Server error:
```
12:26:39 | ERROR xtdb.indexer | error in indexer, indexing #xt/tx-key {:tx-id 0, :system-time #time/instant "2024-11-25T12:26:39.541498Z"}
Cannot invoke "Object.getClass()" because "x" is null
        at clojure.lang.Numbers.ops(Numbers.java:1099)
        at clojure.lang.Numbers.dec(Numbers.java:147)
        at xtdb.sql.plan.TableRowsVisitor$reify__21975.visitPostgresParameter(plan.clj:2056)
        at xtdb.antlr.Sql$PostgresParameterContext.accept(Sql.java:8522)
        at xtdb.sql.plan.TableRowsVisitor$reify__21975.visitParameterRecord(plan.clj:2053)
        at xtdb.antlr.Sql$ParameterRecordContext.accept(Sql.java:11476)
        at xtdb.sql.plan$accept_visitor.invokeStatic(plan.clj:1978)
        at xtdb.sql.plan$accept_visitor.invoke(plan.clj:1977)
        at clojure.core$partial$fn__5927.invoke(core.clj:2641)
        at clojure.core$map$fn__5950$fn__5951.invoke(core.clj:2759)
        at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
        at clojure.core.protocols$fn__8256.invokeStatic(protocols.clj:74)
        at clojure.core.protocols$fn__8256.invoke(protocols.clj:74)
        at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
        at clojure.core$transduce.invokeStatic(core.clj:7026)
        at clojure.core$into.invokeStatic(core.clj:7042)
        at clojure.core$into.invoke(core.clj:7029)
        at xtdb.sql.plan.TableRowsVisitor.visitRecordsValueList(plan.clj:2051)
        at xtdb.antlr.Sql$RecordsValueListContext.accept(Sql.java:11540)
        at xtdb.sql.plan.QueryPlanVisitor.visitRecordsValueList(plan.clj:2315)
        at xtdb.antlr.Sql$RecordsValueListContext.accept(Sql.java:11540)
        at xtdb.sql.plan.QueryPlanVisitor.visitRecordsValueConstructor(plan.clj:2311)
        at xtdb.antlr.Sql$RecordsValueConstructorContext.accept(Sql.java:11597)
        at xtdb.sql.plan.QueryPlanVisitor.visitInsertRecords(plan.clj:2327)
        at xtdb.antlr.Sql$InsertRecordsContext.accept(Sql.java:18433)
        at xtdb.sql.plan.StmtVisitor.visitInsertStatement(plan.clj:2520)
        at xtdb.antlr.Sql$InsertStatementContext.accept(Sql.java:18365)
        at xtdb.sql.plan.StmtVisitor.visitInsertStmt(plan.clj:2516)
        at xtdb.antlr.Sql$InsertStmtContext.accept(Sql.java:519)
        at xtdb.sql.plan$eval22632$fn__22634.invoke(plan.clj:2800)
        at xtdb.sql.plan$eval22608$fn__22609$G__22599__22616.invoke(plan.clj:2777)
        at xtdb.sql.plan$eval22628$fn__22629.invoke(plan.clj:2784)
        at xtdb.sql.plan$eval22608$fn__22609$G__22599__22616.invoke(plan.clj:2777)
        at xtdb.sql.plan$plan_statement.invokeStatic(plan.clj:2818)
        at xtdb.sql.plan$plan_statement.invoke(plan.clj:2816)
        at xtdb.sql$compile_query__26502.invoke(sql.clj:10)
        at xtdb.util$lru_memoize$fn__4286.invoke(util.clj:555)
        at xtdb.indexer$$reify__27751$fn__27752.invoke(indexer.clj:471)
        at xtdb.indexer$$reify__27751.indexOp(indexer.clj:469)
        at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821$fn__27834.invoke(indexer.clj:647)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
        at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821.invoke(indexer.clj:644)
        at xtdb.indexer.Indexer$fn__27816$fn__27842.invoke(indexer.clj:658)
        at xtdb.indexer.Indexer$fn__27816.invoke(indexer.clj:657)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:619)
        at xtdb.log.watcher$watch_log_BANG_$reify__29180.accept(watcher.clj:55)
        at xtdb.log$tx_handler$fn__22745.invoke(log.clj:40)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:418)
        at clojure.core$reduce.invokeStatic(core.clj:6964)
        at clojure.core$reduce.invoke(core.clj:6947)
        at xtdb.log.NotifyingSubscriberHandler$fn__22778.invoke(log.clj:99)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:1583)
12:26:39 | ERROR xtdb.util | Uncaught exception:
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "x" is null
        at clojure.lang.Numbers.ops(Numbers.java:1099)
        at clojure.lang.Numbers.dec(Numbers.java:147)
        at xtdb.sql.plan.TableRowsVisitor$reify__21975.visitPostgresParameter(plan.clj:2056)
        at xtdb.antlr.Sql$PostgresParameterContext.accept(Sql.java:8522)
        at xtdb.sql.plan.TableRowsVisitor$reify__21975.visitParameterRecord(plan.clj:2053)
        at xtdb.antlr.Sql$ParameterRecordContext.accept(Sql.java:11476)
        at xtdb.sql.plan$accept_visitor.invokeStatic(plan.clj:1978)
        at xtdb.sql.plan$accept_visitor.invoke(plan.clj:1977)
        at clojure.core$partial$fn__5927.invoke(core.clj:2641)
        at clojure.core$map$fn__5950$fn__5951.invoke(core.clj:2759)
        at clojure.core.protocols$iterator_reduce_BANG_.invokeStatic(protocols.clj:42)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:52)
        at clojure.core.protocols$fn__8256.invokeStatic(protocols.clj:74)
        at clojure.core.protocols$fn__8256.invoke(protocols.clj:74)
        at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
        at clojure.core$transduce.invokeStatic(core.clj:7026)
        at clojure.core$into.invokeStatic(core.clj:7042)
        at clojure.core$into.invoke(core.clj:7029)
        at xtdb.sql.plan.TableRowsVisitor.visitRecordsValueList(plan.clj:2051)
        at xtdb.antlr.Sql$RecordsValueListContext.accept(Sql.java:11540)
        at xtdb.sql.plan.QueryPlanVisitor.visitRecordsValueList(plan.clj:2315)
        at xtdb.antlr.Sql$RecordsValueListContext.accept(Sql.java:11540)
        at xtdb.sql.plan.QueryPlanVisitor.visitRecordsValueConstructor(plan.clj:2311)
        at xtdb.antlr.Sql$RecordsValueConstructorContext.accept(Sql.java:11597)
        at xtdb.sql.plan.QueryPlanVisitor.visitInsertRecords(plan.clj:2327)
        at xtdb.antlr.Sql$InsertRecordsContext.accept(Sql.java:18433)
        at xtdb.sql.plan.StmtVisitor.visitInsertStatement(plan.clj:2520)
        at xtdb.antlr.Sql$InsertStatementContext.accept(Sql.java:18365)
        at xtdb.sql.plan.StmtVisitor.visitInsertStmt(plan.clj:2516)
        at xtdb.antlr.Sql$InsertStmtContext.accept(Sql.java:519)
        at xtdb.sql.plan$eval22632$fn__22634.invoke(plan.clj:2800)
        at xtdb.sql.plan$eval22608$fn__22609$G__22599__22616.invoke(plan.clj:2777)
        at xtdb.sql.plan$eval22628$fn__22629.invoke(plan.clj:2784)
        at xtdb.sql.plan$eval22608$fn__22609$G__22599__22616.invoke(plan.clj:2777)
        at xtdb.sql.plan$plan_statement.invokeStatic(plan.clj:2818)
        at xtdb.sql.plan$plan_statement.invoke(plan.clj:2816)
        at xtdb.sql$compile_query__26502.invoke(sql.clj:10)
        at xtdb.util$lru_memoize$fn__4286.invoke(util.clj:555)
        at xtdb.indexer$$reify__27751$fn__27752.invoke(indexer.clj:471)
        at xtdb.indexer$$reify__27751.indexOp(indexer.clj:469)
        at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821$fn__27834.invoke(indexer.clj:647)
        at clojure.lang.AFn.call(AFn.java:18)
        at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
        at xtdb.indexer.Indexer$fn__27816$index_tx_ops__27821.invoke(indexer.clj:644)
        at xtdb.indexer.Indexer$fn__27816$fn__27842.invoke(indexer.clj:658)
        at xtdb.indexer.Indexer$fn__27816.invoke(indexer.clj:657)
        at xtdb.indexer.Indexer.indexTx(indexer.clj:619)
        at xtdb.log.watcher$watch_log_BANG_$reify__29180.accept(watcher.clj:55)
        at xtdb.log$tx_handler$fn__22745.invoke(log.clj:40)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:418)
        at clojure.core$reduce.invokeStatic(core.clj:6964)
        at clojure.core$reduce.invoke(core.clj:6947)
        at xtdb.log.NotifyingSubscriberHandler$fn__22778.invoke(log.clj:99)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

Code:
```clj
(defn ->serialised-records [records]
  (map transit->pgobject records))

(defn jdbc-insert-txn [table records]
  (let [total (count records)
        into-table (partial str "INSERT INTO " table " RECORDS ")
        args (interpose ", " (repeat total "?"))
        pg-objects (->serialised-records records)]
    (into [(apply into-table args)] pg-objects)))

(defn jdbc-insert-records [conn table records]
  (jdbc/execute! conn (jdbc-insert-txn table records) {:builder-fn builder-fn}))
```

Example record:
```clj
{:_id       "payee::1:1"
    :application {
                  :personal-details    {:first-name    "Alice"
                                        :middle-name   "P."
                                        :last-name     "Rogamer"
                                        :date-of-birth "1968-08-12"
                                        :address       {:line-1 "22 Azing Loop"
                                                        :city   "Lambda Town"}
                                        :ni            "AB325468"}
                  :account-details     {:account-name   "Alice P. Rogamer"
                                        :account-number "12893476"
                                        :sort-code      "00-00-00"}
                  :payroll-details     {:company-id       "1"
                                        :payroll-id       "1"
                                        :pay-date         (str (tick/date))
                                        :annual-gross-pay 50000}
                  :banking-details     {:beneficiary-id  "1"
                                        :ledger-id       "ledger-1"
                                        :spend-ledger-id "spend-ledger-1"
                                        :limit-ledger-id "limit-ledger-1"}}}
```

**Comment by jarohen** [comment]
@refset - can't repro with the linked test-case, any idea what differs between the repro above and the actual situation?

**Comment by jarohen** [comment]
separately, I'd recommend using `jdbc/execute-batch!` rather than constructing the correct number of `?`s:

```clojure
(defn- jdbc-insert-records [conn table records]
  (jdbc/with-transaction [tx conn]
    (jdbc/execute-batch! tx (str "INSERT INTO " table " RECORDS ?")
                         (mapv (comp vector xt-jdbc/->pg-obj) records)
                         {})))
```

**Comment by jarohen** [comment]
ignore me, got it - repro required having `INSERT INTO foo RECORDS ?, ?` as a prepared statement - I guess IRL they were hitting the prepare threshold, whereas my test case wasn't.
