### ISSUE TITLE
Unknown/unresolvable UNNEST column reference throws `java.lang.UnsupportedOperationException` and breaks the current watermark

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3924]
`FROM docs, UNNEST(docs.col1) AS a(b);` works [play](https://play.xtdb.com/?version=2.0.0-beta3&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgUkVDT1JEUyB7X2lkOiAyLCBjb2wxOiBbJ2JhciddLCBjb2wyOicgYmF6J307In1d&query=RlJPTSBkb2NzLCBVTk5FU1QoZG9jcy5jb2wxKSBBUyBhKGIpOw%3D%3D)

`FROM UNNEST(docs.col1) AS a(b);` errors [play](https://play.xtdb.com/?version=2.0.0-beta3&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgUkVDT1JEUyB7X2lkOiAyLCBjb2wxOiBbJ2JhciddLCBjb2wyOicgYmF6J307In1d&query=RlJPTSBVTk5FU1QoZG9jcy5jb2wxKSBBUyBhKGIpOw%3D%3D) (similarly when trying to use a table/column that doesn't exist) (aside: should `docs.col1` be resolvable? ANSWER: no - due to SQL scoping rules, but you can do `SELECT (FROM UNNEST(d.col1) AS a(b)) FROM docs d`)

Beyond the error impacting the current query, it also prevents subsequent queries from working until a new transaction is made (and a new watermark is created).

Related stack traces:
```
18:11:23 | ERROR xtdb.pgwire | #error {
 :cause org.apache.arrow.vector.NullVector
 :via
 [{:type java.lang.UnsupportedOperationException
   :message org.apache.arrow.vector.NullVector
   :at [xtdb.vector.ValueVectorReader unsupported ValueVectorReader.java 91]}]
 :trace
 [[xtdb.vector.ValueVectorReader unsupported ValueVectorReader.java 91]
  [xtdb.vector.ValueVectorReader listElementReader ValueVectorReader.java 183]
  [xtdb.operator.table$emit_col_table$fn__27217$fn__27219 invoke table.clj 157]
  [xtdb.operator.table$emit_col_table$fn__27217 invoke table.clj 153]
  [xtdb.operator.table$eval27295$fn__27297$fn__27305 invoke table.clj 207]
  [xtdb.logical_plan$unary_expr$fn__20285 invoke logical_plan.clj 119]
  [xtdb.logical_plan$unary_expr$fn__20285 invoke logical_plan.clj 119]
  [xtdb.logical_plan$binary_expr$fn__20293 invoke logical_plan.clj 131]
  [xtdb.logical_plan$unary_expr$fn__20285 invoke logical_plan.clj 119]
  [xtdb.query$prepare_ra$reify$reify__28692 openCursor query.clj 219]
  [xtdb.pgwire$cmd_exec_query invokeStatic pgwire.clj 1247]
  [xtdb.pgwire$cmd_exec_query invoke pgwire.clj 1245]
  [xtdb.pgwire$execute_portal invokeStatic pgwire.clj 1589]
  [xtdb.pgwire$execute_portal invoke pgwire.clj 1551]
  [xtdb.pgwire$eval30233$fn__30236 invoke pgwire.clj 1599]
  [clojure.lang.MultiFn invoke MultiFn.java 234]
  [xtdb.pgwire$handle_msg invokeStatic pgwire.clj 1659]
  [xtdb.pgwire$handle_msg invoke pgwire.clj 1653]
  [xtdb.pgwire$conn_loop invokeStatic pgwire.clj 1695]
  [xtdb.pgwire$conn_loop invoke pgwire.clj 1666]
  [xtdb.pgwire$connect invokeStatic pgwire.clj 1740]
  [xtdb.pgwire$connect invoke pgwire.clj 1705]
  [xtdb.pgwire$accept_loop$fn__30316$fn__30317$fn__30318 invoke pgwire.clj 1784]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.Executors$RunnableAdapter call Executors.java 572]
  [java.util.concurrent.FutureTask run FutureTask.java 317]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1144]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 642]
  [java.lang.Thread run Thread.java 1583]]}
18:11:23 | ERROR xtdb.pgwire | Uncaught exception processing message
java.lang.IllegalStateException: watermark closed
        at xtdb.watermark.Watermark.retain(IWatermark.kt:29)
        at xtdb.indexer.live_index.LiveIndex.openWatermark(live_index.clj:332)
        at xtdb.indexer.Indexer.openWatermark(indexer.clj:748)
        at xtdb.operator.scan$tables_with_cols.invokeStatic(scan.clj:112)
        at xtdb.operator.scan$tables_with_cols.invoke(scan.clj:111)
        at xtdb.query$eval28717$fn$reify__28721.planQuery(query.clj:258)
        at xtdb.node.impl.Node.prepare_sql(impl.clj:138)
        at xtdb.pgwire$prep_stmt.invokeStatic(pgwire.clj:1456)
        at xtdb.pgwire$prep_stmt.invoke(pgwire.clj:1432)
        at xtdb.pgwire$eval30174$fn__30177.invoke(pgwire.clj:1495)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1659)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1653)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1695)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1666)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1740)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1705)
        at xtdb.pgwire$accept_loop$fn__30316$fn__30317$fn__30318.invoke(pgwire.clj:1784)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
18:11:23 | ERROR xtdb.pgwire | #error {
 :cause org.apache.arrow.vector.NullVector
 :via
 [{:type java.lang.UnsupportedOperationException
   :message org.apache.arrow.vector.NullVector
   :at [xtdb.vector.ValueVectorReader unsupported ValueVectorReader.java 91]}]
 :trace
 [[xtdb.vector.ValueVectorReader unsupported ValueVectorReader.java 91]
  [xtdb.vector.ValueVectorReader listElementReader ValueVectorReader.java 183]
  [xtdb.operator.table$emit_col_table$fn__27217$fn__27219 invoke table.clj 157]
  [xtdb.operator.table$emit_col_table$fn__27217 invoke table.clj 153]
  [xtdb.operator.table$eval27295$fn__27297$fn__27305 invoke table.clj 207]
  [xtdb.logical_plan$unary_expr$fn__20285 invoke logical_plan.clj 119]
  [xtdb.logical_plan$unary_expr$fn__20285 invoke logical_plan.clj 119]
  [xtdb.logical_plan$binary_expr$fn__20293 invoke logical_plan.clj 131]
  [xtdb.logical_plan$unary_expr$fn__20285 invoke logical_plan.clj 119]
  [xtdb.query$prepare_ra$reify$reify__28692 openCursor query.clj 219]
  [xtdb.pgwire$cmd_exec_query invokeStatic pgwire.clj 1247]
  [xtdb.pgwire$cmd_exec_query invoke pgwire.clj 1245]
  [xtdb.pgwire$execute_portal invokeStatic pgwire.clj 1589]
  [xtdb.pgwire$execute_portal invoke pgwire.clj 1551]
  [xtdb.pgwire$eval30233$fn__30236 invoke pgwire.clj 1599]
  [clojure.lang.MultiFn invoke MultiFn.java 234]
  [xtdb.pgwire$handle_msg invokeStatic pgwire.clj 1659]
  [xtdb.pgwire$handle_msg invoke pgwire.clj 1653]
  [xtdb.pgwire$conn_loop invokeStatic pgwire.clj 1695]
  [xtdb.pgwire$conn_loop invoke pgwire.clj 1666]
  [xtdb.pgwire$connect invokeStatic pgwire.clj 1740]
  [xtdb.pgwire$connect invoke pgwire.clj 1705]
  [xtdb.pgwire$accept_loop$fn__30316$fn__30317$fn__30318 invoke pgwire.clj 1784]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.Executors$RunnableAdapter call Executors.java 572]
  [java.util.concurrent.FutureTask run FutureTask.java 317]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1144]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 642]
  [java.lang.Thread run Thread.java 1583]]}
```

**Comment by refset** [comment]
Complete example of this now working (for my own reference):
```sql
INSERT INTO products (_id, name, tags) VALUES (1, 'Laptop', ARRAY[10, 20, 30]);
INSERT INTO products (_id, name, tags) VALUES (2, 'Phone', ARRAY[20, 40]);
INSERT INTO products (_id, name, tags) VALUES (3, 'Tablet', ARRAY[10, 50]);

SELECT p.*
FROM products p
WHERE 20 IN (SELECT tag_id FROM UNNEST(p.tags) AS x(tag_id))
```
[Play](https://play.xtdb.com/?version=2.x-SNAPSHOT&type=sql-v2&enc=2&txs=NobwRAjgrgpgTgTzALjAFzrMAadAPAZxTAEkA5AZQFEAlAFQAJy6B5BgBzgHsATKAYzQEGACgD6ASx7YGAOwCGAWxgy08gOYEAlAwBqAQQAyAVSoVRARhkByQ-PZou7azP00a%2BgJrALABhkATP4MAMy%2BALpaANwAOrLk1PRMZKwc3HyCwuJSMgrKqhraekam5iIBNgAKABZcsjAuDG4e3kEyACwR0XEJtIzMbJy8AkKiktJySioMapo6BiZmoiE2dPIARgA2MGiNzV4%2BwQCsXVFgAL7Y4GiExNSGVADCjOwAdABUcQBiNCwAsmlhpkOHEAOoACVoVAYQWSonuT0Ys3GDB%2B-wYxjIZDMdBEb1mRX05jwImRUi00RwYAICAIaBgigAtGgJMoULIoJtNudwkA)
