### ISSUE TITLE
`CONTAINS` predicate not working with `_valid_time` and TIMESTAMP (local)

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3935]
`VALID_TIME CONTAINS TIMESTAMP ...` was working previously. This must have broken during the move to _valid_time and tstz-range.

```
17:10:09 | DEBUG xtdb.pgwire | Interpreting SQL:  SELECT *, _valid_time
FROM trades FOR ALL VALID_TIME
WHERE _valid_time CONTAINS TIMESTAMP '2024-01-15 17:00:00'
ORDER BY _id;
17:10:09 | ERROR xtdb.pgwire | Uncaught exception processing message
xtdb.IllegalArgumentException: contains? not applicable to types tstz-range and timestamp-local
        at xtdb.error$illegal_arg.invokeStatic(error.clj:11)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.error$illegal_arg.invokeStatic(error.clj:7)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.expression$eval8058$fn__8060.invoke(expression.clj:544)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at xtdb.expression$codegen_call_STAR_$iter__8129__8133$fn__8134.invoke(expression.clj:619)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.core$seq__5486.invokeStatic(core.clj:139)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
        at clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74)
        at clojure.core.protocols$fn__8262.invoke(protocols.clj:74)
        at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6965)
        at clojure.core$into.invokeStatic(core.clj:7038)
        at clojure.core$into.invoke(core.clj:7029)
        at xtdb.expression$codegen_call_STAR_.invokeStatic(expression.clj:623)
        at xtdb.expression$codegen_call_STAR_.invoke(expression.clj:605)
        at xtdb.expression$eval8164$fn__8166.invoke(expression.clj:666)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.expression$eval8164$fn__8166$iter__8168__8172$fn__8173$fn__8174.invoke(expression.clj:660)
        at xtdb.expression$eval8164$fn__8166$iter__8168__8172$fn__8173.invoke(expression.clj:659)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.core$seq__5486.invokeStatic(core.clj:139)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
        at clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74)
        at clojure.core.protocols$fn__8262.invoke(protocols.clj:74)
        at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6965)
        at clojure.core$reduce.invoke(core.clj:6947)
        at xtdb.expression$codegen_call_STAR_.invokeStatic(expression.clj:608)
        at xtdb.expression$codegen_call_STAR_.invoke(expression.clj:605)
        at xtdb.expression$eval8164$fn__8166.invoke(expression.clj:666)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.expression$fn__9750.invokeStatic(expression.clj:1685)
        at xtdb.expression$fn__9750.invoke(expression.clj:1683)
        at xtdb.util$lru_memoize$fn__5290.invoke(util.clj:555)
        at xtdb.expression$wrap_zone_id_cache_buster$fn__9743.invoke(expression.clj:1663)
        at xtdb.expression$__GT_expression_projection_spec.invokeStatic(expression.clj:1716)
        at xtdb.expression$__GT_expression_projection_spec.invoke(expression.clj:1714)
        at xtdb.expression$__GT_expression_selection_spec.invokeStatic(expression.clj:1749)
        at xtdb.expression$__GT_expression_selection_spec.invoke(expression.clj:1748)
        at xtdb.operator.select$eval26860$fn__26863$fn__26866.invoke(select.clj:44)
        at xtdb.logical_plan$unary_expr.invokeStatic(logical_plan.clj:116)
        at xtdb.logical_plan$unary_expr.invoke(logical_plan.clj:114)
        at xtdb.operator.select$eval26860$fn__26863.invoke(select.clj:40)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.operator.rename$eval26783$fn__26785.invoke(rename.clj:45)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.operator.project$eval25996$fn__25999.invoke(project.clj:145)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.operator.order_by$eval26717$fn__26719.invoke(order_by.clj:272)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.operator.project$eval25996$fn__25999.invoke(project.clj:145)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.query$emit_expr$reify__28672.apply(query.clj:117)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at xtdb.query$emit_expr.invokeStatic(query.clj:105)
        at xtdb.query$emit_expr.invoke(query.clj:103)
        at xtdb.query$prepare_ra$reify__28711.columnFields(query.clj:178)
        at xtdb.pgwire$prep_stmt.invokeStatic(pgwire.clj:1512)
        at xtdb.pgwire$prep_stmt.invoke(pgwire.clj:1478)
        at xtdb.pgwire$eval30307$fn__30310$fn__30313$fn__30318.invoke(pgwire.clj:1695)
        at xtdb.pgwire$eval30307$fn__30310$fn__30313.invoke(pgwire.clj:1694)
        at xtdb.pgwire$eval30307$fn__30310.invoke(pgwire.clj:1686)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1743)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1737)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1779)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1750)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1824)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1789)
        at xtdb.pgwire$accept_loop$fn__30385$fn__30386$fn__30387.invoke(pgwire.clj:1868)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by jarohen** [comment]
works with timestamp-tz, added support for timestamp-local and date
