### ISSUE TITLE
Duplicate column names returns an empty result over psql rather than an error

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3960]
In XTDB:
```
xtdb=> SELECT username, username FROM pg_user;
xtdb=>
```
(The correct error is logged in the xtdb container)

<details><summary>Error</summary>

```
14:43:25 | ERROR xtdb.pgwire | Uncaught exception processing message
xtdb.IllegalArgumentException: Errors planning SQL statement:
  - Duplicate column projection: username
        at xtdb.error$illegal_arg.invokeStatic(error.clj:11)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.error$illegal_arg.invokeStatic(error.clj:7)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.sql.plan$eval24068$fn__24070.invoke(plan.clj:2895)
        at xtdb.sql.plan$eval24044$fn__24045$G__24035__24052.invoke(plan.clj:2870)
        at xtdb.sql.plan$plan_statement.invokeStatic(plan.clj:2911)
        at xtdb.sql.plan$plan_statement.invoke(plan.clj:2909)
        at xtdb.sql$compile_query__28018.invoke(sql.clj:10)
        at xtdb.util$lru_memoize$fn__5353.invoke(util.clj:580)
        at xtdb.query$eval29077$fn$reify$reify__29084.apply(query.clj:274)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
        at xtdb.query$eval29077$fn$reify__29081.planQuery(query.clj:268)
        at xtdb.node.impl.Node.prepare_sql(impl.clj:136)
        at xtdb.pgwire$prep_stmt.invokeStatic(pgwire.clj:1507)
        at xtdb.pgwire$prep_stmt.invoke(pgwire.clj:1481)
        at xtdb.pgwire$eval30666$fn__30669$fn__30672$fn__30677.invoke(pgwire.clj:1698)
        at xtdb.pgwire$eval30666$fn__30669$fn__30672.invoke(pgwire.clj:1697)
        at xtdb.pgwire$eval30666$fn__30669.invoke(pgwire.clj:1689)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1746)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1740)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1782)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1753)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1827)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1792)
        at xtdb.pgwire$accept_loop$fn__30744$fn__30745$fn__30746.invoke(pgwire.clj:1871)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

In Postgres:
```
postgres=# SELECT usename, usename FROM pg_user;
 usename  | usename
----------+----------
 postgres | postgres
(1 row)
postgres=#
```

I would expect at least the error to be propagated.

---

Discovered through: https://github.com/xtdb/xt-fiddle/issues/56

**Comment by Akeboshiwind** [comment]
I had the same problem with [this query too](https://play.xtdb.com/?version=2.0.0-beta3&type=sql-beta&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKF9pZCwgY29sMSkgVkFMVUVTICgxLCAnZm9vJyk7In1d&query=U0VMRUNUIF9pZCwgY29sMQpGUk9NIGRvY3MKR1JPVVAgQlkgX2lk):
```sql
INSERT INTO docs (_id, col1) VALUES (1, 'foo');

SELECT _id, col1
FROM docs
GROUP BY _id
```

**Comment by jarohen** [comment]
is this caused by #3936, perhaps?
