### ISSUE TITLE
Clarify default ERROR logging for invalid queries

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/crux#3971]
I think this logging level is too high considering it's a user error.

---

To reproduce:
```sh
$ docker run -it --pull=always -p 3000:3000 -p 5432:5432 ghcr.io/xtdb/xtdb
```

```sh
$ psql -h localhost -p 5433 -U xtdb
psql (14.15 (Homebrew), server 16)
WARNING: psql major version 14, server major version 16.
         Some psql features might not work.
Type "help" for help.

xtdb=> SELECTing * FROM pg_user;
ERROR:  Errors parsing SQL statement:
  - line 1:0 mismatched input 'SELECTing' expecting {'(', 'ALTER', 'ASSERT', 'BEGIN', 'COMMIT', 'CREATE', 'DELETE', 'ERASE', 'EXECUTE', 'FROM', 'INSERT', 'PATCH', 'PREPARE', 'RECORDS', 'ROLLBACK', 'SELECT', 'SET', 'SETTING', 'SHOW', 'START', 'UPDATE', 'VALUES', 'WITH'}
xtdb=>
```

<details><summary>Logs:</summary>

```
Starting XTDB 2.x @ 2.0.0-beta4 @ 5aafb16 ...
13:04:51 | INFO  xtdb.metrics | tagging all metrics with node-id: xtdb-node-1ecae5
13:04:52 | INFO  xtdb.pgwire | Server started on port: 5432
13:04:53 | INFO  xtdb.healthz | Healthz server started on port: 8080
13:04:57 | INFO  xtdb.server | HTTP server started on port: 3000
13:04:57 | INFO  xtdb.cli | Node started
13:06:58 | ERROR xtdb.pgwire | Error parsing SQL
xtdb.IllegalArgumentException: Errors parsing SQL statement:
  - line 1:0 mismatched input 'SELECTing' expecting {'(', 'ALTER', 'ASSERT', 'BEGIN', 'COMMIT', 'CREATE', 'DELETE', 'ERASE', 'EXECUTE', 'FROM', 'INSERT', 'PATCH', 'PREPARE', 'RECORDS', 'ROLLBACK', 'SELECT', 'SET', 'SETTING', 'SHOW', 'START', 'UPDATE', 'VALUES', 'WITH'}
        at xtdb.error$illegal_arg.invokeStatic(error.clj:11)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.error$illegal_arg.invokeStatic(error.clj:7)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.antlr$add_throwing_error_listener$fn__2196.invoke(antlr.clj:20)
        at xtdb.antlr.proxy$org.antlr.v4.runtime.BaseErrorListener$ff19274a.syntaxError(Unknown Source)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
        at xtdb.antlr.Sql.directlyExecutableStatement(Sql.java:1223)
        at xtdb.antlr.Sql.multiSqlStatement(Sql.java:456)
        at xtdb.antlr$parse_multi_statement$fn__2209.invoke(antlr.clj:43)
        at clojure.lang.FnInvokers.invokeOO(FnInvokers.java:247)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
        at xtdb.antlr$parse_multi_statement.invokeStatic(antlr.clj:40)
        at xtdb.antlr$parse_multi_statement.invoke(antlr.clj:39)
        at xtdb.pgwire$interpret_sql.invokeStatic(pgwire.clj:416)
        at xtdb.pgwire$interpret_sql.invoke(pgwire.clj:404)
        at xtdb.pgwire$parse.invokeStatic(pgwire.clj:1477)
        at xtdb.pgwire$parse.invoke(pgwire.clj:1470)
        at xtdb.pgwire$eval30687$fn__30690$fn__30693.invoke(pgwire.clj:1693)
        at xtdb.pgwire$eval30687$fn__30690.invoke(pgwire.clj:1689)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at xtdb.pgwire$handle_msg.invokeStatic(pgwire.clj:1746)
        at xtdb.pgwire$handle_msg.invoke(pgwire.clj:1740)
        at xtdb.pgwire$conn_loop.invokeStatic(pgwire.clj:1782)
        at xtdb.pgwire$conn_loop.invoke(pgwire.clj:1753)
        at xtdb.pgwire$connect.invokeStatic(pgwire.clj:1827)
        at xtdb.pgwire$connect.invoke(pgwire.clj:1792)
        at xtdb.pgwire$accept_loop$fn__30765$fn__30766$fn__30767.invoke(pgwire.clj:1871)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

**Comment by refset** [comment]
Agreed in many scenarios this is may not be ERROR-worthy, but in others it might be - it really depends on who's connected and the use cases they have for submitting arbitrary (untested) queries - perhaps some client connection configuration is best? 🤔

**Comment by jarohen** [comment]
agreed - so long as the error message is propagated correctly back to the client, we shouldn't be logging ERROR here

**Comment by jarohen** [comment]
this particular case downgraded to debug in 01e85fa670baa6c941a97d1e78049f51fd5f5665, part of #3972 - re-open if we find others?
