### ISSUE TITLE
Support Postgres `standard_conforming_strings` SQL variable

### ISSUE THREAD

**Issue by refset** [xtdb/crux#3972]
https://www.postgresql.org/docs/current/runtime-config-compatible.html#GUC-STANDARD-CONFORMING-STRINGS

Ruby's Sequel (by default) tries to set this parameter on startup - let's ensure that we can cope with it, even if it's a no-op.

https://github.com/jeremyevans/sequel/blob/7a520bb9c013947bd60d9170e727fb52a2287ba1/lib/sequel/adapters/shared/postgres.rb#L1246

Spotted via https://github.com/eval/sequel-xtdb/blob/b00977075408aa72dcdce863931a2e1eacf92d45/lib/sequel/adapters/xtdb.rb#L14

**Comment by jarohen** [comment]
@refset we have a test for this already - what's the repro here?

**Comment by eval** [comment]
@jarohen with gems sequel and pg^1 installed:

```ruby
$ ruby -rsequel -e 'Sequel.connect("postgres://localhost:5432/xtdb", force_standard_strings: true)'
``` 
flipping to `false` prevents it.

^1: can be a bit tricky. From bash-history:
```bash
gem install pg -- --with-pg-confg=/Applications/Postgres.app/Contents/Versions/16/bin/pg_config \
--with-pg-include=/Applications/Postgres.app/Contents/Versions/16/include \
--with-pg-lib=/Applications/Postgres.app/Contents/Versions/16/lib
```

**Comment by jarohen** [comment]
cheers @eval 🙏  have you got the logs from XT to show the actual query it's sending?

(kick it off with `XTDB_LOGGING_LEVEL_PGWIRE=debug`, there should be 'interpreting SQL' lines)

**Comment by eval** [comment]
```
18:30:08 | DEBUG xtdb.pgwire | Interpreting SQL:  SET standard_conforming_strings = ON
18:30:08 | ERROR xtdb.pgwire | Error parsing SQL
xtdb.IllegalArgumentException: Errors parsing SQL statement:
  - line 1:4 no viable alternative at input 'SETstandard_conforming_strings'
        at xtdb.error$illegal_arg.invokeStatic(error.clj:11)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
        at xtdb.error$illegal_arg.invokeStatic(error.clj:7)
        at xtdb.error$illegal_arg.invoke(error.clj:3)
```

As indicated to @refset over chat that, yes, this errors prevent connecting to xtdb using sequel with the postgres-adapter, though when solved, you'd hardly get a viable setup: lots of `if server_version > 12345 <decide what SQL to support>`. (As `server_version` fires of a query that returns nothing really, `0` is assumed, which puts you at < PG9 capabilities). So an XTDB-adapter is needed.

**Comment by jarohen** [comment]
aha, it needs to _set_ the variable 🙂 right, yep, we can potentially make that a no-op as I don't think we support _non_-standard conforming strings
